/* Build the single self-contained HTML file that gets published and handed out.
 *
 * src/ is the source of truth: an HTML shell plus ES modules that resolve
 * `three` from a CDN importmap, which is convenient to develop against but
 * has two costs when sharing — ES modules are blocked on file://, and it
 * needs network access.
 *
 * So: esbuild bundles the app (three included, from node_modules) into one
 * classic script, and that gets inlined into the shell.
 */
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const SRC = 'src/index.html';
const OUT = 'docs/index.html';

const result = await build({
  entryPoints: ['src/main.js'],
  bundle: true,
  format: 'iife',
  minify: true,
  legalComments: 'none',
  target: 'es2020',
  write: false,
});
const app = result.outputFiles[0].text;

let html = readFileSync(SRC, 'utf8');

const sub = (s, pat, to, what) => {
  /* replacement is always a function: a string replacement would expand `$&`,
     "$'" and '$`' inside the minified bundle and silently corrupt it */
  const out = s.replace(pat, () => to);
  if(out === s){ console.error(`build.mjs: could not find ${what} in ${SRC}`); process.exit(1); }
  return out;
};

/* the importmap only exists for the dev server */
html = sub(html, /\n<!-- Dev: bare specifiers[\s\S]*?<\/script>\n/, '\n', 'the dev importmap block');

/* `</script` inside JS would close the tag early */
const safe = app.replace(/<\/script/gi, '<\\/script').replace(/<!--/g, '<\\!--');
html = sub(html, '<script type="module" src="./main.js"></script>',
  '<script>/* bundled app + three.js r160 (MIT, (c) three.js authors) */\n' + safe + '\n</script>',
  'the app script tag');

html = sub(html, '<title>',
  '<!-- Generated by build.mjs from src/. Edit src/, not this file. -->\n<title>',
  'the title tag');

mkdirSync(dirname(OUT), {recursive:true});
writeFileSync(OUT, html);
writeFileSync(resolve(dirname(OUT), '.nojekyll'), '');
console.log(`wrote ${OUT}  (${(html.length/1024/1024).toFixed(2)} MB, no ES modules, no CDN)`);
