/* Build a single self-contained HTML file from index.html.
 *
 * index.html is the source of truth. It loads three from a CDN as an ES module,
 * which is convenient to develop against but has two costs when sharing:
 *   - ES modules are blocked on file://, so double-clicking the file shows nothing
 *   - it needs network access to unpkg
 *
 * This inlines a pre-bundled three (see `npm run bundle`) and downgrades the app
 * script from `type="module"` to a classic script, which file:// allows.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SRC    = resolve(here, 'index.html');
const BUNDLE = resolve(here, 'three-bundle.js');
/* docs/ so GitHub Pages can serve it straight from the main branch,
   and so the published URL has no filename in it. */
const OUT    = resolve(here, 'docs/index.html');

if(!existsSync(BUNDLE)){
  console.error('missing three-bundle.js — run:\n  npm run bundle');
  process.exit(1);
}

let html = readFileSync(SRC, 'utf8');
const bundle = readFileSync(BUNDLE, 'utf8');

function must(cond, what){
  if(!cond){ console.error(`build.mjs: could not find ${what} in index.html`); process.exit(1); }
}

/* Every replacement below passes a FUNCTION as the replacement, never a string.
 * A string replacement would expand `$&`, "$'" and '$`' inside the minified
 * three bundle and silently corrupt it. */
const sub = (s, pat, to, what) => {
  const out = s.replace(pat, () => to);
  must(out !== s, what);
  return out;
};

/* 1. drop the importmap — nothing resolves by bare specifier any more */
html = sub(html, /\n<script type="importmap">[\s\S]*?<\/script>\n/, '\n', 'the importmap block');

/* 2. swap the two bare imports for the bundle's globals */
html = sub(html,
  /import \* as THREE from 'three';\s*\nimport \{ OrbitControls \} from 'three\/addons\/controls\/OrbitControls\.js';/,
  "const THREE = THREEBUNDLE;\nconst OrbitControls = THREEBUNDLE.OrbitControls;",
  'the THREE / OrbitControls import lines');

/* 3. classic script instead of a module, wrapped so it keeps its own scope */
html = sub(html, '<script type="module">', '<script>\n(function(){\n"use strict";',
  'the app module script tag');

const tail = "\nsetTimeout(()=> document.getElementById('hint').classList.add('gone'), 9000);\n</script>";
html = sub(html, tail, tail.replace('</script>', '})();\n</script>'), 'the end of the app script');

/* 4. inline the bundle ahead of the app.
 *    `</script` inside JS would close the tag early — neutralise it. */
const safeBundle = bundle.replace(/<\/script/gi, '<\\/script').replace(/<!--/g, '<\\!--');
html = sub(html, '<script>\n(function(){',
  '<script>/* three.js r160 + OrbitControls — bundled, MIT (c) three.js authors */\n'
  + safeBundle + '\n</script>\n\n<script>\n(function(){',
  'the app script open tag');

/* 5. note the provenance in the source */
html = sub(html, '<title>',
  '<!-- self-contained build — generated by build.mjs from index.html. edit index.html, not this file. -->\n<title>',
  'the title tag');

mkdirSync(dirname(OUT), {recursive:true});
writeFileSync(OUT, html);
console.log(`wrote ${OUT}  (${(html.length/1024/1024).toFixed(2)} MB, no ES modules, no CDN for three)`);
