/* Build docs/ — the directory GitHub Pages publishes and itch.io gets zipped.
 *
 * This used to produce ONE self-contained HTML file, because the deliverable
 * had to survive being double-clicked from a file:// URL, where ES modules are
 * blocked. That cost a pile of string surgery on the shell: strip the importmap,
 * demote `type="module"` to a classic script, inline a minified three.js while
 * dodging `$&` expansion in String.replace. Every one of those steps was a
 * chance to corrupt the bundle silently.
 *
 * file:// and offline are no longer requirements (2026-07-31): the outlets are
 * Pages and a zip, both of which serve a directory over http(s) perfectly well.
 * So this is now a plain build:
 *
 *   src/main.js  --esbuild-->  docs/main.js     (ES module, three bundled in)
 *   src/index.html  --copy-->  docs/index.html  (byte-identical)
 *   src/assets/**   --copy-->  docs/assets/**   (if it exists)
 *
 * There is no string surgery left at all. `src/index.html` already points at
 * `./main.js` as a module, so the shell that ships is exactly the shell we
 * develop against — the "two different index.html files" hazard is gone.
 *
 * The dev importmap is copied along with it. That is deliberate and costs
 * nothing: an import map is only consulted when something imports a bare
 * specifier, and the bundle has none, so no request is ever made for it.
 *
 * SOURCEMAP=1 emits docs/main.js.map. Off by default — a source map is only
 * fetched when devtools is open, so it costs nothing at load, but it does ship
 * readable sources, and this is going on sale.
 */
import { build } from 'esbuild';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { join } from 'node:path';

const SRC = 'src';
const OUT = 'docs';
const SOURCEMAP = process.env.SOURCEMAP === '1';

/* Start from empty so a renamed asset cannot linger and get published. */
rmSync(OUT, {recursive:true, force:true});
mkdirSync(OUT, {recursive:true});

const result = await build({
  entryPoints: [join(SRC, 'main.js')],
  outfile: join(OUT, 'main.js'),
  bundle: true,
  format: 'esm',
  minify: true,
  legalComments: 'none',
  target: 'es2020',
  sourcemap: SOURCEMAP,
  banner: {js: '/* falco-city — bundled app + three.js r160 (MIT, (c) three.js authors).\n   Generated by build.mjs from src/. Edit src/, not this file. */'},
  metafile: true,
});

/* the shell, verbatim */
cpSync(join(SRC, 'index.html'), join(OUT, 'index.html'));
/* anything hand-authored that has to travel with it */
if(existsSync(join(SRC, 'assets')))
  cpSync(join(SRC, 'assets'), join(OUT, 'assets'), {recursive:true});
/* Pages would otherwise run the output through Jekyll */
writeFileSync(join(OUT, '.nojekyll'), '');

/* ---- report what a first load actually costs ---- */
const kb = n => (n/1024).toFixed(1) + ' KB';
const shipped = [];
let total = 0, wire = 0;
for(const [f, o] of Object.entries(result.metafile.outputs)){
  if(f.endsWith('.map')){ total += o.bytes; continue; }
  shipped.push([f, o.bytes]);
}
shipped.push([join(OUT, 'index.html'), statSync(join(OUT, 'index.html')).size]);
for(const [f, bytes] of shipped.sort((a,b)=>b[1]-a[1])){
  const gz = gzipSync(readFileSync(f)).length;
  total += bytes; wire += gz;
  console.log(`  ${f.padEnd(22)} ${kb(bytes).padStart(10)}   ${kb(gz).padStart(10)} gzipped`);
}
console.log(`\nwrote ${OUT}/  —  ${kb(total)} on disk, ${kb(wire)} over the wire (gzip)`);
if(SOURCEMAP) console.log('  (+ main.js.map, fetched only when devtools is open)');
