/* Generated by the module split. See README §開発の分担. */
import * as THREE from 'three';
import { C } from './palette.js';
import { DISTRICTS } from './layout.js';
import { box, edgeMat, put } from './mesh.js';
import { world } from './scene.js';
import { BUILDERS } from './districts.build.js';


/* ============================================================
   5. districts — geometry per stage
   ============================================================ */

const districtObjs = {};   // id -> {group, hit, anchor}
const hitTargets = [];

/* wire each district to its builder. Declaring a district in
   districts.data.js and forgetting to register a builder in
   districts.build.js is the one way to break this file, so say so loudly. */
for(const d of DISTRICTS){
  d.build = BUILDERS[d.id];
  if(typeof d.build !== 'function')
    throw new Error(`district "${d.id}" has no builder — add BUILD_${d.id} to src/districts.build.js and register it in BUILDERS`);
}

DISTRICTS.forEach(d=>{
  const g = new THREE.Group();
  const cx = (d.x0+d.x1)/2, cz = (d.z0+d.z1)/2;
  const w = d.x1-d.x0, dp = d.z1-d.z0;
  const baseY = d.y ?? 0;
  g.position.y = baseY;

  /* floor patch */
  const patch = new THREE.Mesh(
    new THREE.PlaneGeometry(w, dp),
    new THREE.MeshBasicMaterial({color:d.color, transparent:true, opacity:0.13, depthWrite:false})
  );
  patch.rotation.x = -Math.PI/2; patch.position.set(cx, 0.03, cz);
  g.add(patch);
  const pOut = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.PlaneGeometry(w,dp)),
    new THREE.LineBasicMaterial({color:d.color, transparent:true, opacity:0.55})
  );
  pOut.rotation.x = -Math.PI/2; pOut.position.set(cx, 0.04, cz); g.add(pOut);

  d.build(g, d, cx, cz);

  /* invisible hover/click volume — kept tight so the floating Sysdig deck
     doesn't swallow clicks aimed at the districts below it */
  const hh = d.floating ? d.top+4 : d.top+10;
  const hit = box(w+3, hh, dp+3, 0xffffff, 0);
  hit.material.depthWrite = false;
  hit.position.set(cx, hh/2, cz);
  hit.userData.district = d;
  g.add(hit); hitTargets.push(hit);

  world.add(g);
  districtObjs[d.id] = {
    group:g, hit,
    anchor:new THREE.Vector3(cx, baseY + d.top + 7, cz),
    center:new THREE.Vector3(cx, baseY + d.top/2, cz)
  };
});

export {
  districtObjs,
  hitTargets
};
