/* Generated by the module split. See README §開発の分担. */
import { C } from './palette.js';
import { DISTRICTS, byId, isFlow, ST } from './layout.js';
import { ENV_AXES, ENV_SEL, DRIVERS, DEPLOY_PRESETS, DEPLOYMENTS,
         CLUSTER_NODES, NODE_CPUS, nodeCpus, setNodeCpus, bufferCount,
         currentEnv, setEnvAxis } from './districts.data.js';
import { S, GAME, TUNE_DEFAULTS, PRESET_MIB, model } from './state.js';
import { districtObjs } from './city.js';
import { ringRefs, outRefs, stateRefs, deployRefs, driverSlabs, sysdigGroup,
         applyEnvironment, applyCpus } from './districts.build.js';
import { spawn, spawnPolicy, polMat, PN, N } from './sim.js';
import { revive } from './log.js';
import { updateTags, updateVerdict, tagEls, select, closeDrawer } from './ui.js';
import { goHome } from './scene.js';
import { play } from './audio.js';


/* ============================================================
   14. controls: mode / driver / load / console
   ============================================================ */
/* fade a whole subtree without touching anyone else's materials */
function setDim(root, f){
  if(!root) return;
  root.traverse(o=>{
    if(o.material && o.material.opacity !== undefined){
      if(o.userData._o0 === undefined) o.userData._o0 = o.material.opacity;
      o.material.transparent = true;
      o.material.opacity = o.userData._o0 * f;
    }
  });
}

/* The command you would actually be looking at. Which one that is follows from
   the composed environment's attributes rather than from any environment id:
   no kernel path means the driver was never injected, and a cluster means the
   agent is a DaemonSet you reach with kubectl instead of a service on one box. */
function consoleTitle(){
  const env = currentEnv();
  if(!env.kernelPath)
    return S.mode==='sysdig' ? 'sysdig · plugin sources only (no driver)'
                             : 'falco --engine nodriver · plugin sources only';
  if(S.mode === 'sysdig')
    return env.cluster ? 'sysdig agent (DaemonSet) · policies from Sysdig Secure'
                       : 'sysdig agent (host) · policies from Sysdig Secure';
  return env.cluster ? 'kubectl logs -n falco ds/falco'
                     : 'systemctl status falco · falco.service';
}

function setMode(m){
  S.mode = m;
  [...document.querySelectorAll('#modeSeg button')].forEach(b=>
    b.classList.toggle('on', b.dataset.mode===m));
  document.getElementById('ctitle').textContent = consoleTitle();
  setDim(sysdigGroup, m==='sysdig' ? 1 : 0.16);
  /* the rule stream changes both source and colour with the stack */
  polMat.uniforms.uColor.value.setHex(m==='sysdig' ? C.lumin : 0xC9AEDA);
  for(let i=0;i<PN;i++) spawnPolicy(i);
  applyShield();
  /* the platform layer arriving is worth hearing. In campaign mode the build
     event carries this, but in explore mode the STACK lever is the only way it
     happens, and that notification never reaches the campaign feed. */
  if(m === 'sysdig') play('layer');
}

/* Host Shield is the driver-bearing half, so it exists wherever a driver is
   actually injected; Cluster Shield is cluster-scoped and driverless, so it
   exists wherever there is a cluster to guard. Both read the composed
   environment's `shield`, which is the whole point: managed Kubernetes keeps
   its Cluster Shield because it has a cluster, and a single host loses it
   because it does not. Pinning this to a list of environment ids is what hid
   the fourth environment. Neither Shield exists in plain OSS Falco. */
function applyShield(){
  const env = currentEnv();
  const on = S.mode === 'sysdig' && (!GAME.on || GAME.built.has('sysdig'));
  if(deployRefs.hostShield)    deployRefs.hostShield.visible    = on && env.shield.host;
  if(deployRefs.clusterShield) deployRefs.clusterShield.visible = on && env.shield.cluster;
}

/* ---------- the environment, as four independent axes ----------
   Every branch below reads an attribute the composed environment carries.
   There is deliberately no environment id in this file — not one string
   comparison — because the environment is no longer a single choice. It is:

     orchestrator    how the Kubernetes audit log is collected
     node OS         whether kmod can be loaded at all
     runtime socket  whether container.* and k8s.pod.* get attached
     k8smeta plugin  whether the API-server-derived fields exist

   and the consequences this file reacts to are:

     kernelPath      a driver was injected, so there is a ring buffer to fill.
                     False under `nodriver`: only plugins deliver events
     containerFields how much the container plugin could attach
     podFields       the runtime-derived Kubernetes fields
     k8sMeta         the API-server-derived ones
     cluster         the agent is a DaemonSet rather than a service on one box
     blockedDrivers  drivers this node OS cannot load
     shield          which Sysdig Shields have something to protect         */
function applyEnv(){
  const env = applyEnvironment(currentEnv());
  /* keep the legacy wire value fed: state.js, sim.js and campaign.js still
     compare against it and belong to other sessions this phase */
  S.deploy = env.wire;
  S.driver = env.driver.id;

  /* the scenario-facing name of where we are, kept in step so it cannot drift
     from the axes. campaign.js sets these when a scenario hands them over. */
  const named = DEPLOYMENTS.find(d => d.id === env.wire);
  if(named) S.env = named.env;
  S.nodes = env.topology === 'cluster' ? CLUSTER_NODES : (env.kernelPath ? 1 : 0);
  /* CPUs on this node — the number the buffer count is derived from. The
     scenario schema does not carry it yet (L1 is adding it), so this is the
     seam: the moment a scenario hands over a per-node CPU count on S, both the
     TUNING label and the ring district's lanes follow it with no further edit.
     Undefined today, which leaves the declared default in place. Falling back
     to NODE_CPUS rather than leaving the last value keeps it stateless — a
     scenario on a 2-vCPU node must not leak that onto the next one. */
  setNodeCpus(Number.isInteger(S.cpus) ? S.cpus : NODE_CPUS);

  const kp = env.kernelPath;
  setDim(districtObjs.driver.group,    kp ? 1 : 0.07);
  setDim(districtObjs.ring.group,      kp ? 1 : 0.07);
  setDim(districtObjs.workloads.group, kp ? 1 : 0.10);
  /* the plugin lane is the whole story with no driver, so light it up */
  setDim(districtObjs.plugins.group,   kp ? 0.72 : 1);

  /* Three gantries, three separate questions. The container one never goes
     dark while a kernel path exists, because container.id and container.type
     come off the cgroup and need no socket — it dims to show it is carrying
     two fields instead of twenty-eight. */
  const G = stateRefs.gantries;
  setDim(G.container,  kp ? (env.containerFields.length > 2 ? 1 : 0.4) : 0.08);
  setDim(G.k8sRuntime, kp && env.podFields.length ? 1 : 0.08);
  setDim(G.k8sApi,     kp && env.k8sMeta ? 1 : 0.08);

  applyShield();
  syncEnvSegs();
  syncDriverSeg();

  document.getElementById('ctitle').textContent = consoleTitle();
  tagEls.sysdig && updateTags();
  for(let i=0;i<N;i++) spawn(i, Math.random()*2.2);   // reroute everything
  onTuneChange();
  return env;
}

/* Pick one axis value. Two guards, both from the node OS axis:

   - a driver this node OS cannot load is simply not selectable. This is the
     authoritative check, not the disabled attribute, because ui.js re-derives
     `disabled` on the driver row from its own allow-list and would hand a
     blocked button back
   - and a node OS that outlaws the driver already in use moves to the first
     legal one rather than leaving an impossible configuration on screen  */
function setEnv(axis, value){
  if(axis === 'driver' && currentEnv().blockedDrivers.includes(value)) return currentEnv();
  let env = setEnvAxis(axis, value);
  if(env.blockedDrivers.includes(env.driver.id))
    env = setEnvAxis('driver', DRIVERS.find(d => !env.blockedDrivers.includes(d.id)).id);
  return applyEnv();
}

/* Named starting points, so `setDeploy('k8s')` still works for main.js and the
   console. A preset is a set of axis positions, nothing more. */
function setDeploy(id){
  const preset = DEPLOY_PRESETS[id];
  if(!preset) return;
  for(const [axis, value] of Object.entries(preset)) setEnvAxis(axis, value);
  /* A scenario sets S.driver before handing over the environment, and that
     choice has to survive the preset's default — an inherited host running an
     older kernel is a `kmod` story. What it may not do is contradict the
     preset about whether there is a kernel path at all, or ask for a driver
     this node OS cannot load. */
  const want = DRIVERS.find(d => d.id === S.driver);
  const env  = currentEnv();
  if(want && want.kernelPath === env.kernelPath && !env.blockedDrivers.includes(want.id))
    setEnvAxis('driver', want.id);
  applyEnv();
}

/* ---------- lever rendering ----------
   The DEPLOY panel is generated from ENV_AXES instead of being written out in
   index.html, which listed three of the four old environments — precisely why
   managed Kubernetes had no way in. Now it is one row per axis, and adding a
   value anywhere means a button appears for free. index.html is another
   session's file, so the rows are laid out from here. */
function renderEnvSegs(){
  const seg = document.getElementById('deploySeg');
  if(!seg) return;
  seg.textContent = '';
  seg.style.flexDirection = 'column';
  seg.style.alignItems = 'stretch';
  seg.style.gap = '1px';
  /* four stacked rows are taller than the STACK and DRIVER segments beside
     them, and flex would otherwise stretch those to match */
  if(seg.parentElement) seg.parentElement.style.alignItems = 'flex-start';

  for(const ax of ENV_AXES){
    const row = document.createElement('div');
    row.style.display = 'flex';
    row.style.alignItems = 'center';
    row.style.gap = '2px';
    const lbl = document.createElement('span');
    lbl.className = 'caplbl';
    lbl.textContent = ax.lbl;
    lbl.style.minWidth = '92px';
    lbl.style.padding = '5px 6px 5px 6px';
    lbl.title = ax.hint;
    row.appendChild(lbl);
    for(const v of ax.values){
      const b = document.createElement('button');
      b.dataset.axis = ax.id;
      b.dataset.val  = v.id;
      b.textContent  = v.lbl;
      b.title = v.why || '';
      b.style.padding = '5px 8px';
      b.style.fontSize = '9.5px';
      b.onclick = () => setEnv(ax.id, v.id);
      row.appendChild(b);
    }
    seg.appendChild(row);
  }
}

/* which button is lit, and which axis currently has nothing to cause.
   Each selected button also mirrors the wire value into `data-dep`, because
   ui.js re-derives the DEPLOY row's lit state and its scenario lock from that
   attribute (`on('#deploySeg','dep',S.deploy)` / `gate(...)`). Mirroring means
   ui.js's pass reproduces exactly this state instead of clearing it, and a
   scenario — where the environment is the place you were given rather than a
   lever — still locks the whole row without ui.js knowing about axes. */
function syncEnvSegs(){
  const env = currentEnv();
  document.querySelectorAll('#deploySeg button').forEach(b=>{
    const sel = ENV_SEL[b.dataset.axis] === b.dataset.val;
    b.classList.toggle('on', sel);
    b.dataset.dep = sel ? env.wire : '';
  });
  /* k8s-metacollector watches the API server, so without one the k8smeta axis
     keeps its selection and loses its effect. Say so rather than hiding it. */
  const inert = env.k8sMetaAsked && !env.k8sMeta;
  document.querySelectorAll('#deploySeg button[data-axis="k8sMeta"]').forEach(b=>{
    b.style.textDecoration = inert && b.dataset.val === 'on' ? 'line-through' : '';
    if(inert && b.dataset.val === 'on')
      b.title = 'apiserver が無いので k8s-metacollector が話す相手がいない';
  });
}

function renderDriverSeg(){
  const seg = document.getElementById('drvSeg');
  if(!seg) return;
  seg.querySelectorAll('button').forEach(b => b.remove());
  for(const dv of DRIVERS){
    const b = document.createElement('button');
    b.dataset.drv = dv.id;
    b.textContent = dv.lbl;
    b.title = dv.note;
    b.onclick = () => setEnv('driver', dv.id);
    seg.appendChild(b);
  }
}

/* A driver the node OS cannot load is disabled here — and it is the NODE OS
   axis this reads, not the orchestrator. That is the correction: the only
   documented case of kmod being impossible is COS, and COS is a node image. */
function syncDriverSeg(){
  const env = currentEnv();
  document.querySelectorAll('#drvSeg button').forEach(b=>{
    const dv = DRIVERS.find(x => x.id === b.dataset.drv);
    const blocked = env.blockedDrivers.includes(b.dataset.drv);
    b.disabled = blocked;
    b.style.opacity = blocked ? '.3' : '';
    b.style.cursor  = blocked ? 'not-allowed' : '';
    b.style.textDecoration = blocked ? 'line-through' : '';
    /* ui.js re-derives `disabled` from its own allow-list, so the visible
       state of a node-OS block rides on something it does not touch */
    b.style.pointerEvents = blocked ? 'none' : '';
    b.title = blocked ? env.nodeOs.why : (dv?.note || '');
    b.classList.toggle('on', b.dataset.drv === env.driver.id);
  });
  driverSlabs.forEach(s=>{
    const on = s.userData.drvName === env.driver.id;
    const mm = s.userData.mesh;
    mm.material.color.setHex(on ? C.falco : C.g20);
    mm.material.opacity = on ? 0.95 : 0.4;
  });
}

renderEnvSegs();
renderDriverSeg();
document.querySelectorAll('#modeSeg button').forEach(b=>
  b.onclick = ()=>setMode(b.dataset.mode));

const loadRange = document.getElementById('loadRange');
const loadVal = document.getElementById('loadVal');
loadRange.oninput = ()=>{
  S.load = loadRange.value/100;
  loadVal.textContent = '×'+S.load.toFixed(1);
  onTuneChange();
};

/* ---------- tuning panel ---------- */
const BUF_LBL = document.getElementById('tBufV');
const SET_LBL = document.getElementById('tSetV');
const CPU_LBL = document.getElementById('tCpuV');
const rngBuf  = document.getElementById('rngBuf');

function segWire(sel, attr, apply){
  document.querySelectorAll(sel+' button').forEach(b=>{
    b.onclick = ()=>{
      document.querySelectorAll(sel+' button').forEach(x=>x.classList.toggle('on', x===b));
      apply(b.dataset[attr]);
      onTuneChange();
    };
  });
}
segWire('#segSet', 'set', v => S.tune.syscallSet = v);
segWire('#segCpu', 'cpu', v => S.tune.cpusPerBuf = +v);
segWire('#segAct', 'act', v => { S.tune.dropAction = v; S.deadDrops = 0; });

rngBuf.oninput = ()=>{ S.tune.bufPreset = +rngBuf.value; onTuneChange(); };
document.getElementById('chkSlow').onchange = e=>{
  S.tune.slowOutput = e.target.checked; onTuneChange();
};
document.getElementById('tReset').onclick = ()=>{
  S.tune = {...TUNE_DEFAULTS};
  S.load = 1.0; loadRange.value = 100; loadVal.textContent = '×1.0';
  rngBuf.value = TUNE_DEFAULTS.bufPreset;
  document.getElementById('chkSlow').checked = false;
  const on = (sel, attr, val)=> document.querySelectorAll(sel+' button').forEach(b=>
    b.classList.toggle('on', b.dataset[attr] === String(val)));
  on('#segSet','set',TUNE_DEFAULTS.syscallSet);
  on('#segCpu','cpu',TUNE_DEFAULTS.cpusPerBuf);
  on('#segAct','act',TUNE_DEFAULTS.dropAction);
  onTuneChange();
};

/* any tuning change is also the way out of the `exit` state */
function onTuneChange(){
  const t = S.tune;
  /* per BUFFER, not per CPU: the default modern_ebpf shares one buffer between
     cpus_for_each_buffer CPUs, so the count is ceil(nCPU ÷ that) and the size
     is the size of one buffer (which the kernel double-maps, so it costs 2×) */
  BUF_LBL.textContent = `${t.bufPreset} · ${PRESET_MIB(t.bufPreset)} MiB/buffer`;
  SET_LBL.textContent = t.syscallSet === 'custom' ? 'custom_set' : t.syscallSet;
  /* Derived from the DECLARED CPU count of the node you are standing on, never
     from a literal. This label used to read "2 → 4 buffers" on every node in
     every environment, which is a units error the model was teaching and which
     contradicts the nodes-are-not-buffers diagnosis outright: on the 2-vCPU
     node that scenario puts you on, the default 2 gives ceil(2/2) = 1 buffer,
     not 4. Saying the vCPU count out loud is the point — it is the number the
     player has to notice, and the one nothing else on screen was showing. */
  const cpus = nodeCpus();
  const bufs = bufferCount(t.cpusPerBuf, cpus);
  CPU_LBL.textContent =
    `${t.cpusPerBuf} CPU/buffer × ${cpus} vCPU → ${bufs} buffer${bufs===1?'':'s'}`;
  revive();
  applyTuneVisuals();
  updateVerdict(model());     // don't wait for the next HUD tick
}

/* reshape the ring buffer district so the config is visible in the model */
function applyTuneVisuals(){
  const t = S.tune;
  /* how many lanes there are at all. Cheap when the count has not moved, and
     it has to run here so the district can never be drawing a different
     machine from the one the label above is describing. */
  applyCpus();
  // buffer size → depth of the shared-memory volume and the lane walls
  const s = 0.45 + (t.bufPreset-1) * 0.30;
  if(ringRefs.shm){
    ringRefs.shm.scale.y = s;
    ringRefs.shm.position.y = 3.9 * s;
  }
  ringRefs.walls.forEach(w=>{ w.scale.y = s; w.position.y = 0.9 * s; });

  // cpus_for_each_buffer → which CPU lanes share one buffer
  ringRefs.troughs.forEach((tr,i)=>{
    const grp = Math.floor(i / t.cpusPerBuf);
    tr.material.color.setHex(grp % 2 ? 0xD3D7DA : C.g10);
  });
  ringRefs.caps.forEach((c,i)=>{
    const grp = Math.floor(i / t.cpusPerBuf);
    c.material.color.setHex(grp % 2 ? C.g40 : C.g30);
  });

  // a synchronous output blocks the consumer — mark the pipes
  outRefs.pipes.forEach((p,i)=>{
    if(i === 2) return;                       // falcosidekick lane stays green
    p.material.color.setHex(t.slowOutput ? C.redUi : C.g20);
  });
}

const cbox = document.getElementById('consoleBox');
document.getElementById('ctoggle').onclick = ()=> cbox.classList.toggle('open');
cbox.classList.add('open');

addEventListener('keydown', e=>{
  const i = parseInt(e.key,10);
  if(i>=1 && i<=DISTRICTS.length) select(DISTRICTS[i-1].id);
  if(e.key==='Escape') closeDrawer();
  if(e.key==='0'){ closeDrawer(); goHome(); }
});

export {
  setMode,
  setDeploy,
  setEnv,
  applyEnv,
  setDim,
  applyShield,
  onTuneChange,
  applyTuneVisuals,
  consoleTitle
};
