/* Generated by the module split. See README §開発の分担. */
import { C } from './palette.js';
import { DISTRICTS, byId, isFlow, ST } from './layout.js';
import { DEPLOYMENTS, byDeployId } from './districts.data.js';
import { S, GAME, TUNE_DEFAULTS, PRESET_MIB, model } from './state.js';
import { districtObjs } from './city.js';
import { ringRefs, outRefs, stateRefs, deployRefs, driverSlabs, sysdigGroup,
         applyDeployment } from './districts.build.js';
import { spawn, spawnPolicy, polMat, PN, N } from './sim.js';
import { revive } from './log.js';
import { updateTags, updateVerdict, tagEls, select, closeDrawer } from './ui.js';
import { goHome } from './scene.js';


/* ============================================================
   14. controls: mode / driver / load / console
   ============================================================ */
/* fade a whole subtree without touching anyone else's materials */
function setDim(root, f){
  if(!root) return;
  root.traverse(o=>{
    if(o.material && o.material.opacity !== undefined){
      if(o.userData._o0 === undefined) o.userData._o0 = o.material.opacity;
      o.material.transparent = true;
      o.material.opacity = o.userData._o0 * f;
    }
  });
}

/* The command you would actually be looking at. Which one that is follows from
   the environment's declared attributes rather than its id: no kernel path
   means the syscall source is switched off, and a cluster means the agent is a
   DaemonSet you reach with kubectl instead of a service on one box. */
function consoleTitle(){
  const dep = byDeployId(S.deploy);
  if(dep && !dep.kernelPath)
    return S.mode==='sysdig' ? 'sysdig · plugin sources only (no driver)'
                             : 'falco --disable-source syscall';
  if(S.mode === 'sysdig')
    return dep?.cluster ? 'sysdig agent (DaemonSet) · policies from Sysdig Secure'
                        : 'sysdig agent (host) · policies from Sysdig Secure';
  return dep?.cluster ? 'kubectl logs -n falco ds/falco'
                      : 'systemctl status falco · falco.service';
}

function setMode(m){
  S.mode = m;
  [...document.querySelectorAll('#modeSeg button')].forEach(b=>
    b.classList.toggle('on', b.dataset.mode===m));
  document.getElementById('ctitle').textContent = consoleTitle();
  setDim(sysdigGroup, m==='sysdig' ? 1 : 0.16);
  /* the rule stream changes both source and colour with the stack */
  polMat.uniforms.uColor.value.setHex(m==='sysdig' ? C.lumin : 0xC9AEDA);
  for(let i=0;i<PN;i++) spawnPolicy(i);
  applyShield();
}

/* Host Shield exists wherever there are hosts to run on; Cluster Shield only
   where there is a cluster to guard. Both read the deployment's declared
   `shield`, which is the whole point: managed Kubernetes keeps its Cluster
   Shield because it has a cluster, and `Host (systemd)` still loses it because
   it does not. Pinning this to an id list is what hid the fourth environment.
   Neither Shield exists in plain OSS Falco. */
function applyShield(){
  const dep = byDeployId(S.deploy);
  const on = S.mode === 'sysdig' && (!GAME.on || GAME.built.has('sysdig'));
  if(deployRefs.hostShield)    deployRefs.hostShield.visible    = on && !!dep?.shield.host;
  if(deployRefs.clusterShield) deployRefs.clusterShield.visible = on && !!dep?.shield.cluster;
}

/* ---------- deployment topology ----------
   Every branch below reads an attribute the environment declares in
   districts.data.js. There is deliberately no list of environment ids in this
   file: a fifth topology is a declaration in DEPLOYMENTS plus a button this
   module renders for free.

     kernelPath  a driver and a ring buffer exist at all. False for
                 serverless / unprivileged: only plugin sources feed the rules
                 engine, which is how you run Falco without touching the kernel
     k8sMeta     Kubernetes metadata is available to enrich events with
     cluster     the agent is a DaemonSet rather than a service on one machine
     shield      which Sysdig Shields have something to protect              */
function setDeploy(id){
  const dep = byDeployId(id);
  if(!dep) return;
  S.deploy = id;
  [...document.querySelectorAll('#deploySeg button')].forEach(b=>
    b.classList.toggle('on', b.dataset.dep===id));

  const kernelPath = !!dep.kernelPath;
  setDim(districtObjs.driver.group,    kernelPath ? 1 : 0.07);
  setDim(districtObjs.ring.group,      kernelPath ? 1 : 0.07);
  setDim(districtObjs.workloads.group, kernelPath ? 1 : 0.10);
  /* the k8s gantry enriches syscall-derived events, so it needs both a kernel
     path to carry them and Kubernetes metadata to attach */
  setDim(stateRefs.gantries.k8s,       kernelPath && dep.k8sMeta ? 1 : 0.08);
  /* the plugin lane is the whole story in kernel-less mode, so light it up */
  setDim(districtObjs.plugins.group,   kernelPath ? 0.72 : 1);

  /* the big one: the whole west end, plus the API server. One generic call
     handles every declared topology, including ones added later. */
  applyDeployment(id);
  applyShield();

  // the driver choice is meaningless without a driver
  document.querySelectorAll('#drvSeg button').forEach(b=>{
    b.disabled = !kernelPath;
    b.style.opacity = kernelPath ? '' : '.35';
    b.style.cursor  = kernelPath ? '' : 'not-allowed';
  });

  document.getElementById('ctitle').textContent = consoleTitle();
  tagEls.sysdig && updateTags();
  for(let i=0;i<N;i++) spawn(i, Math.random()*2.2);   // reroute everything
  onTuneChange();
}

/* The DEPLOY segment is rendered from DEPLOYMENTS instead of being written out
   in index.html. The markup listed three of the four environments, which is
   precisely why managed Kubernetes had no way in — the topology existed and was
   unreachable. Generating the buttons means the array is the only place an
   environment has to be declared. */
function renderDeploySeg(){
  const seg = document.getElementById('deploySeg');
  if(!seg) return;
  seg.querySelectorAll('button').forEach(b => b.remove());
  for(const dep of DEPLOYMENTS){
    const b = document.createElement('button');
    b.dataset.dep = dep.id;
    b.textContent = dep.jp;
    b.classList.toggle('on', dep.id === S.deploy);
    b.onclick = () => setDeploy(dep.id);
    seg.appendChild(b);
  }
}
renderDeploySeg();
document.querySelectorAll('#modeSeg button').forEach(b=>
  b.onclick = ()=>setMode(b.dataset.mode));

document.querySelectorAll('#drvSeg button').forEach(b=>
  b.onclick = ()=>{
    S.driver = b.dataset.drv;
    [...document.querySelectorAll('#drvSeg button')].forEach(x=>
      x.classList.toggle('on', x===b));
    driverSlabs.forEach(s=>{
      const on = s.userData.drvName === S.driver;
      const mm = s.userData.mesh;
      mm.material.color.setHex(on ? C.falco : C.g20);
      mm.material.opacity = on ? 0.95 : 0.4;
    });
    onTuneChange();          // driver choice also changes drain capacity
  });

const loadRange = document.getElementById('loadRange');
const loadVal = document.getElementById('loadVal');
loadRange.oninput = ()=>{
  S.load = loadRange.value/100;
  loadVal.textContent = '×'+S.load.toFixed(1);
  onTuneChange();
};

/* ---------- tuning panel ---------- */
const BUF_LBL = document.getElementById('tBufV');
const SET_LBL = document.getElementById('tSetV');
const CPU_LBL = document.getElementById('tCpuV');
const rngBuf  = document.getElementById('rngBuf');

function segWire(sel, attr, apply){
  document.querySelectorAll(sel+' button').forEach(b=>{
    b.onclick = ()=>{
      document.querySelectorAll(sel+' button').forEach(x=>x.classList.toggle('on', x===b));
      apply(b.dataset[attr]);
      onTuneChange();
    };
  });
}
segWire('#segSet', 'set', v => S.tune.syscallSet = v);
segWire('#segCpu', 'cpu', v => S.tune.cpusPerBuf = +v);
segWire('#segAct', 'act', v => { S.tune.dropAction = v; S.deadDrops = 0; });

rngBuf.oninput = ()=>{ S.tune.bufPreset = +rngBuf.value; onTuneChange(); };
document.getElementById('chkSlow').onchange = e=>{
  S.tune.slowOutput = e.target.checked; onTuneChange();
};
document.getElementById('tReset').onclick = ()=>{
  S.tune = {...TUNE_DEFAULTS};
  S.load = 1.0; loadRange.value = 100; loadVal.textContent = '×1.0';
  rngBuf.value = TUNE_DEFAULTS.bufPreset;
  document.getElementById('chkSlow').checked = false;
  const on = (sel, attr, val)=> document.querySelectorAll(sel+' button').forEach(b=>
    b.classList.toggle('on', b.dataset[attr] === String(val)));
  on('#segSet','set',TUNE_DEFAULTS.syscallSet);
  on('#segCpu','cpu',TUNE_DEFAULTS.cpusPerBuf);
  on('#segAct','act',TUNE_DEFAULTS.dropAction);
  onTuneChange();
};

/* any tuning change is also the way out of the `exit` state */
function onTuneChange(){
  const t = S.tune;
  BUF_LBL.textContent = `${t.bufPreset} · ${PRESET_MIB(t.bufPreset)} MiB/CPU`;
  SET_LBL.textContent = t.syscallSet === 'custom' ? 'custom_set' : t.syscallSet;
  CPU_LBL.textContent = `${t.cpusPerBuf} → ${8/t.cpusPerBuf} buffers`;
  revive();
  applyTuneVisuals();
  updateVerdict(model());     // don't wait for the next HUD tick
}

/* reshape the ring buffer district so the config is visible in the model */
function applyTuneVisuals(){
  const t = S.tune;
  // buffer size → depth of the shared-memory volume and the lane walls
  const s = 0.45 + (t.bufPreset-1) * 0.30;
  if(ringRefs.shm){
    ringRefs.shm.scale.y = s;
    ringRefs.shm.position.y = 3.9 * s;
  }
  ringRefs.walls.forEach(w=>{ w.scale.y = s; w.position.y = 0.9 * s; });

  // cpus_for_each_syscall_buffer → which lanes share one buffer
  ringRefs.troughs.forEach((tr,i)=>{
    const grp = Math.floor(i / t.cpusPerBuf);
    tr.material.color.setHex(grp % 2 ? 0xD3D7DA : C.g10);
  });
  ringRefs.caps.forEach((c,i)=>{
    const grp = Math.floor(i / t.cpusPerBuf);
    c.material.color.setHex(grp % 2 ? C.g40 : C.g30);
  });

  // a synchronous output blocks the consumer — mark the pipes
  outRefs.pipes.forEach((p,i)=>{
    if(i === 2) return;                       // falcosidekick lane stays green
    p.material.color.setHex(t.slowOutput ? C.redUi : C.g20);
  });
}

const cbox = document.getElementById('consoleBox');
document.getElementById('ctoggle').onclick = ()=> cbox.classList.toggle('open');
cbox.classList.add('open');

addEventListener('keydown', e=>{
  const i = parseInt(e.key,10);
  if(i>=1 && i<=DISTRICTS.length) select(DISTRICTS[i-1].id);
  if(e.key==='Escape') closeDrawer();
  if(e.key==='0'){ closeDrawer(); goHome(); }
});

export {
  setMode,
  setDeploy,
  setDim,
  applyShield,
  onTuneChange,
  applyTuneVisuals,
  consoleTitle
};
