/* Generated by the module split. See README §開発の分担. */
import { C } from './palette.js';
import { DISTRICTS, byId, isFlow, ST } from './layout.js';
import { S, GAME, TUNE_DEFAULTS, PRESET_MIB, model } from './state.js';
import { districtObjs } from './city.js';
import { ringRefs, outRefs, stateRefs, deployRefs, driverSlabs, sysdigGroup } from './districts.build.js';
import { spawn, spawnPolicy, polMat, PN, N } from './sim.js';
import { revive } from './log.js';
import { updateTags, updateVerdict, tagEls, select, closeDrawer } from './ui.js';
import { goHome } from './scene.js';


/* ============================================================
   14. controls: mode / driver / load / console
   ============================================================ */
/* fade a whole subtree without touching anyone else's materials */
function setDim(root, f){
  if(!root) return;
  root.traverse(o=>{
    if(o.material && o.material.opacity !== undefined){
      if(o.userData._o0 === undefined) o.userData._o0 = o.material.opacity;
      o.material.transparent = true;
      o.material.opacity = o.userData._o0 * f;
    }
  });
}

function consoleTitle(){
  if(S.deploy === 'plugins')
    return S.mode==='sysdig' ? 'sysdig · plugin sources only (no driver)'
                             : 'falco --disable-source syscall';
  if(S.mode === 'sysdig')
    return S.deploy==='host' ? 'sysdig agent (host) · policies from Sysdig Secure'
                             : 'sysdig agent (DaemonSet) · policies from Sysdig Secure';
  return S.deploy==='host' ? 'systemctl status falco · falco.service'
                           : 'kubectl logs -n falco ds/falco';
}

function setMode(m){
  S.mode = m;
  [...document.querySelectorAll('#modeSeg button')].forEach(b=>
    b.classList.toggle('on', b.dataset.mode===m));
  document.getElementById('ctitle').textContent = consoleTitle();
  setDim(sysdigGroup, m==='sysdig' ? 1 : 0.16);
  /* the rule stream changes both source and colour with the stack */
  polMat.uniforms.uColor.value.setHex(m==='sysdig' ? C.lumin : 0xC9AEDA);
  for(let i=0;i<PN;i++) spawnPolicy(i);
  applyShield();
}

/* Host Shield exists in every Sysdig deployment; Cluster Shield only where
   there is a cluster to guard. Neither exists in plain OSS Falco. */
function applyShield(){
  const on = S.mode === 'sysdig' && (!GAME.on || GAME.built.has('sysdig'));
  if(deployRefs.hostShield)    deployRefs.hostShield.visible    = on && S.deploy !== 'plugins';
  if(deployRefs.clusterShield) deployRefs.clusterShield.visible = on && S.deploy === 'k8s';
}

/* ---------- deployment topology ----------
   host     : package + systemd on a node. No k8s metadata to enrich with.
   k8s      : DaemonSet. container + k8s metadata both available.
   plugins  : no driver, no ring buffer at all — only plugin event sources
              feed the rules engine. This is how you run Falco where you
              cannot touch the kernel. */
function setDeploy(dep){
  S.deploy = dep;
  [...document.querySelectorAll('#deploySeg button')].forEach(b=>
    b.classList.toggle('on', b.dataset.dep===dep));

  const kernelPath = dep !== 'plugins';
  setDim(districtObjs.driver.group,    kernelPath ? 1 : 0.07);
  setDim(districtObjs.ring.group,      kernelPath ? 1 : 0.07);
  setDim(districtObjs.workloads.group, kernelPath ? 1 : 0.10);
  setDim(stateRefs.gantries.k8s,       dep === 'k8s' ? 1 : 0.08);
  /* the plugin lane is the whole story in kernel-less mode, so light it up */
  setDim(districtObjs.plugins.group,   dep === 'plugins' ? 1 : 0.72);

  /* the big one: a cluster of nodes, or a single machine */
  if(deployRefs.wlK8s)  deployRefs.wlK8s.visible  = dep === 'k8s';
  if(deployRefs.wlHost) deployRefs.wlHost.visible = dep === 'host';
  /* k8s audit has no meaning without an API server to audit */
  if(deployRefs.apiServer) deployRefs.apiServer.visible = dep !== 'host';
  applyShield();

  // the driver choice is meaningless without a driver
  document.querySelectorAll('#drvSeg button').forEach(b=>{
    b.disabled = !kernelPath;
    b.style.opacity = kernelPath ? '' : '.35';
    b.style.cursor  = kernelPath ? '' : 'not-allowed';
  });

  document.getElementById('ctitle').textContent = consoleTitle();
  tagEls.sysdig && updateTags();
  for(let i=0;i<N;i++) spawn(i, Math.random()*2.2);   // reroute everything
  onTuneChange();
}
document.querySelectorAll('#deploySeg button').forEach(b=>
  b.onclick = ()=> setDeploy(b.dataset.dep));
document.querySelectorAll('#modeSeg button').forEach(b=>
  b.onclick = ()=>setMode(b.dataset.mode));

document.querySelectorAll('#drvSeg button').forEach(b=>
  b.onclick = ()=>{
    S.driver = b.dataset.drv;
    [...document.querySelectorAll('#drvSeg button')].forEach(x=>
      x.classList.toggle('on', x===b));
    driverSlabs.forEach(s=>{
      const on = s.userData.drvName === S.driver;
      const mm = s.userData.mesh;
      mm.material.color.setHex(on ? C.falco : C.g20);
      mm.material.opacity = on ? 0.95 : 0.4;
    });
    onTuneChange();          // driver choice also changes drain capacity
  });

const loadRange = document.getElementById('loadRange');
const loadVal = document.getElementById('loadVal');
loadRange.oninput = ()=>{
  S.load = loadRange.value/100;
  loadVal.textContent = '×'+S.load.toFixed(1);
  onTuneChange();
};

/* ---------- tuning panel ---------- */
const BUF_LBL = document.getElementById('tBufV');
const SET_LBL = document.getElementById('tSetV');
const CPU_LBL = document.getElementById('tCpuV');
const rngBuf  = document.getElementById('rngBuf');

function segWire(sel, attr, apply){
  document.querySelectorAll(sel+' button').forEach(b=>{
    b.onclick = ()=>{
      document.querySelectorAll(sel+' button').forEach(x=>x.classList.toggle('on', x===b));
      apply(b.dataset[attr]);
      onTuneChange();
    };
  });
}
segWire('#segSet', 'set', v => S.tune.syscallSet = v);
segWire('#segCpu', 'cpu', v => S.tune.cpusPerBuf = +v);
segWire('#segAct', 'act', v => { S.tune.dropAction = v; S.deadDrops = 0; });

rngBuf.oninput = ()=>{ S.tune.bufPreset = +rngBuf.value; onTuneChange(); };
document.getElementById('chkSlow').onchange = e=>{
  S.tune.slowOutput = e.target.checked; onTuneChange();
};
document.getElementById('tReset').onclick = ()=>{
  S.tune = {...TUNE_DEFAULTS};
  S.load = 1.0; loadRange.value = 100; loadVal.textContent = '×1.0';
  rngBuf.value = TUNE_DEFAULTS.bufPreset;
  document.getElementById('chkSlow').checked = false;
  const on = (sel, attr, val)=> document.querySelectorAll(sel+' button').forEach(b=>
    b.classList.toggle('on', b.dataset[attr] === String(val)));
  on('#segSet','set',TUNE_DEFAULTS.syscallSet);
  on('#segCpu','cpu',TUNE_DEFAULTS.cpusPerBuf);
  on('#segAct','act',TUNE_DEFAULTS.dropAction);
  onTuneChange();
};

/* any tuning change is also the way out of the `exit` state */
function onTuneChange(){
  const t = S.tune;
  BUF_LBL.textContent = `${t.bufPreset} · ${PRESET_MIB(t.bufPreset)} MiB/CPU`;
  SET_LBL.textContent = t.syscallSet === 'custom' ? 'custom_set' : t.syscallSet;
  CPU_LBL.textContent = `${t.cpusPerBuf} → ${8/t.cpusPerBuf} buffers`;
  revive();
  applyTuneVisuals();
  updateVerdict(model());     // don't wait for the next HUD tick
}

/* reshape the ring buffer district so the config is visible in the model */
function applyTuneVisuals(){
  const t = S.tune;
  // buffer size → depth of the shared-memory volume and the lane walls
  const s = 0.45 + (t.bufPreset-1) * 0.30;
  if(ringRefs.shm){
    ringRefs.shm.scale.y = s;
    ringRefs.shm.position.y = 3.9 * s;
  }
  ringRefs.walls.forEach(w=>{ w.scale.y = s; w.position.y = 0.9 * s; });

  // cpus_for_each_syscall_buffer → which lanes share one buffer
  ringRefs.troughs.forEach((tr,i)=>{
    const grp = Math.floor(i / t.cpusPerBuf);
    tr.material.color.setHex(grp % 2 ? 0xD3D7DA : C.g10);
  });
  ringRefs.caps.forEach((c,i)=>{
    const grp = Math.floor(i / t.cpusPerBuf);
    c.material.color.setHex(grp % 2 ? C.g40 : C.g30);
  });

  // a synchronous output blocks the consumer — mark the pipes
  outRefs.pipes.forEach((p,i)=>{
    if(i === 2) return;                       // falcosidekick lane stays green
    p.material.color.setHex(t.slowOutput ? C.redUi : C.g20);
  });
}

const cbox = document.getElementById('consoleBox');
document.getElementById('ctoggle').onclick = ()=> cbox.classList.toggle('open');
cbox.classList.add('open');

addEventListener('keydown', e=>{
  const i = parseInt(e.key,10);
  if(i>=1 && i<=DISTRICTS.length) select(DISTRICTS[i-1].id);
  if(e.key==='Escape') closeDrawer();
  if(e.key==='0'){ closeDrawer(); goHome(); }
});

export {
  setMode,
  setDeploy,
  setDim,
  applyShield,
  onTuneChange,
  applyTuneVisuals,
  consoleTitle
};
