/* Generated by the module split. See README §開発の分担. */
import * as THREE from 'three';
import { C } from './palette.js';
import { DISTRICTS, byId, isFlow } from './layout.js';
import { ORCH, TOPOLOGIES, DRIVERS, currentEnv, nodeCount, nodeOffsets,
         CLUSTER_NODES, NODE_PAD_W, NODE_PAD_D, POD_PITCH } from './districts.data.js';
import { edgeMat, box, edged, put, chevron, groundText } from './mesh.js';
import { world } from './scene.js';


/* ============================================================
   6. builders
   ============================================================ */
/* shared handles the builders (section 6) fill in.
   Declared here because the build loop below runs before their bodies. */
const driverSlabs = [];
const RING_LANES  = [];
const RULE_BLOCKS = [];
const OUT_PIPES   = [];
let sysdigGroup = null;
/* pieces the tuning panel reshapes at runtime */
const ringRefs  = { shm:null, troughs:[], walls:[], caps:[] };
const outRefs   = { pipes:[] };
/* three enrichment gantries, and the field lists each one can attach.
   `labels` holds the alternative captions applyEnvironment switches between. */
const stateRefs  = { gantries:{}, labels:{} };
/* the Sysdig Shield overlay, toggled by stack / environment */
const deployRefs = { clusterShield:null, hostShield:null, auditRoutes:{} };
/* topology id -> west-end group (null when that topology draws none) */
const topoVariants = {};
/* orchestrator id -> the ground caption under the west end */
const captionRefs = {};

/* ---------- west-end variants, one per declared topology ----------
   A cluster and a single host are not the same picture, so the west end is
   rebuilt rather than relabelled. There are three shapes and forty-odd
   environments, because geometry only depends on the projection: is there a
   kernel path, and is it a cluster. Both shapes below read their node count,
   pod count and process list from TOPOLOGIES — nothing here knows the
   number three, and nothing here knows an environment id. */

/* a cluster: N node pads, pods on each, one agent per node */
function buildNodesVariant(dep, d, cx, cz){
  const grp = new THREE.Group();
  const pods = dep.podsPerNode ?? 0;
  const n8 = nodeCount(dep);
  nodeOffsets(n8).forEach((nz, n)=>{
    const pad = box(NODE_PAD_W, 0.9, NODE_PAD_D, C.g10, 0.95);
    put(pad, cx, 0.45, nz); grp.add(pad);
    const rim = new THREE.LineSegments(
      new THREE.EdgesGeometry(new THREE.BoxGeometry(NODE_PAD_W, 0.9, NODE_PAD_D)),
      edgeMat(C.g20, 0.7));
    put(rim, cx, 0.45, nz); grp.add(rim);

    for(let c=0;c<pods;c++){
      const x = cx + (c - (pods-1)/2) * POD_PITCH;
      const h = 3.2 + ((n*7+c*13)%5)*1.5;
      const b = edged(3.2, h, 4.4, c%4===0 ? 0xF3C99A : C.g20, 0.52);
      put(b, x, 0.9+h/2, nz); grp.add(b);
      const a = box(0.9,0.9,0.9, c%3===0 ? C.orange : C.g40, 1);
      put(a, x, 0.9+h+0.9, nz); grp.add(a);
    }
    /* an agent on every node — that is what a DaemonSet is */
    const ds = edged(2.6, 2.6, 2.6, C.falco, 0.92);
    put(ds, cx+11.0, 0.9+1.3, nz); grp.add(ds);
    grp.add(groundText('node-'+(n+1), cx-13.6, nz, 1.7,
      {color:'#8A8C8E', mono:true, opacity:0.95, y:0.12}));
  });

  if(dep.boundary){
    /* the boundary grows with the district, so more nodes stay enclosed */
    const cw = NODE_PAD_W + 6, cd = d.d + 4;
    const cb = new THREE.Mesh(
      new THREE.PlaneGeometry(cw, cd),
      new THREE.MeshBasicMaterial({color:C.falco, transparent:true, opacity:0.05, depthWrite:false}));
    cb.rotation.x = -Math.PI/2; cb.position.set(cx, 0.02, cz); grp.add(cb);
    const cbl = new THREE.LineSegments(
      new THREE.EdgesGeometry(new THREE.PlaneGeometry(cw, cd)), edgeMat(C.falco, 0.5));
    cbl.rotation.x = -Math.PI/2; cbl.position.set(cx, 0.03, cz); grp.add(cbl);
  }
  return grp;
}

/* one machine: a slab carrying named, taller processes and a single agent */
function buildMachineVariant(dep, d, cx, cz){
  const grp = new THREE.Group();
  const sw = dep.slabW, sd = dep.slabD;
  const slab = box(sw, 1.4, sd, C.g10, 0.96);
  put(slab, cx, 0.7, cz); grp.add(slab);
  const slabRim = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.BoxGeometry(sw, 1.4, sd)), edgeMat(C.g30, 0.6));
  put(slabRim, cx, 0.7, cz); grp.add(slabRim);

  const per = dep.procsPerRow;
  const rows = Math.ceil(dep.procs.length / per);
  dep.procs.forEach(([nm,h],i)=>{
    const x = cx + ((i%per) - (per-1)/2) * 6.3;
    const z = cz + (Math.floor(i/per) - (rows-1)/2) * 15;
    const b = edged(4.0, h, 5.0, i%3===0 ? C.g30 : C.g20, 0.55);
    put(b, x, 1.4+h/2, z); grp.add(b);
    const a = box(1.2,1.2,1.2, C.g50, 1);
    put(a, x, 1.4+h+1.0, z); grp.add(a);
    grp.add(groundText(nm, x-2.4, z+3.4, 1.5,
      {color:'#8A8C8E', mono:true, opacity:0.9, y:1.5}));
  });

  const svc = edged(4.4, 4.4, 4.4, C.falco, 0.92);
  put(svc, cx+11.4, 1.4+2.2, cz); grp.add(svc);
  return grp;
}

const SHAPES = { nodes:buildNodesVariant, machine:buildMachineVariant };

function BUILD_workloads(g,d,cx,cz){
  for(const topo of TOPOLOGIES){
    const make = SHAPES[topo.shape];
    /* shape:'none' is a real answer — with no driver there is no
       syscall-emitting west end to draw, so the district is left bare */
    const v = make ? make(topo, d, cx, cz) : null;
    if(v){ v.visible = false; g.add(v); }
    topoVariants[topo.id] = v;
  }

  /* The caption belongs to the orchestrator, not to the geometry: EKS and
     self-managed draw the same pads and say different things about them. One
     per declared orchestrator, plus the one for having no driver at all. */
  const cap = (txt, key)=>{
    const t = groundText(txt, cx-16, d.z1+4, 2.0,
      {color:'#00A8BC', mono:true, opacity:0.95});
    t.visible = false; g.add(t); captionRefs[key] = t;
  };
  for(const o of ORCH) cap(o.caption(CLUSTER_NODES), o.id);
  cap('NO DRIVER (nodriver) · プラグイン入力だけがイベントを運ぶ', 'bare');

  g.add(groundText('SYSCALLS', cx-1, d.z1+8, 5.0, {color:'#BBBDBF', opacity:0.4}));
  g.add(groundText('kernel boundary →', d.x1+3, d.z0-5, 2.6,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
}

/* ---------- the one geometric switch ----------
   Everything the composed environment changes about the city, in one place.
   It takes the environment, not an id, and it never asks which environment
   this is — only what is true of it. Adding an axis value cannot reach this
   function unless it declares a consequence, which is the point. */
function applyEnvironment(env = currentEnv()){
  /* the west end: cluster pads, one host slab, or nothing */
  for(const k in topoVariants)
    if(topoVariants[k]) topoVariants[k].visible = k === env.topology;

  /* its caption: the orchestrator's, unless there is no driver to caption */
  const capKey = env.kernelPath ? env.orch.id : 'bare';
  for(const k in captionRefs) captionRefs[k].visible = k === capKey;

  /* the audit route: an apiserver plus however that provider is collected.
     No orchestrator means no audit log to collect, and therefore no route. */
  for(const k in deployRefs.auditRoutes)
    deployRefs.auditRoutes[k].visible = !!env.audit && k === env.orch.id;

  /* the two k8s gantries are separate questions, so they get separate
     captions: runtime-derived fields need the socket, API-derived fields need
     the k8smeta plugin, and the deprecated spellings read <NA> without it */
  const L = stateRefs.labels;
  if(L.container){
    /* two fields is the floor: container.id and container.type come off the
       cgroup, so they survive with no socket at all */
    const rich = env.containerFields.length > 2;
    L.container.full.visible = rich;
    L.container.min.visible  = !rich;
  }
  if(L.k8sRuntime){
    L.k8sRuntime.on.visible  = env.podFields.length > 0;
    L.k8sRuntime.off.visible = env.podFields.length === 0;
  }
  if(L.k8sApi){
    L.k8sApi.on.visible  = env.k8sMeta;
    L.k8sApi.off.visible = !env.k8sMeta;
  }

  /* a driver the node OS cannot load is drawn as a slab you cannot stand on */
  for(const s of driverSlabs){
    const blocked = env.blockedDrivers.includes(s.userData.drvName);
    s.userData.blocked = blocked;
    s.visible = !blocked;
  }
  return env;
}

function BUILD_driver(g,d,cx,cz){
  // gate wall with tracepoint pillars
  const wall = edged(3.2, d.top, d.z1-d.z0-2, C.falco, 0.2, C.falco);
  put(wall, cx+3.4, d.top/2, cz); g.add(wall);
  for(let z=d.z0+3; z<=d.z1-3; z+=4.2){
    const h = 5 + (Math.abs(z)%7);
    const p = box(1.5,h,1.5, C.falco, 0.85);
    put(p, cx-3.2, h/2, z); g.add(p);
  }
  /* one selectable slab per driver that actually injects something. nodriver
     has no slab on purpose — it is the absence of one. */
  driverSlabs.length = 0;
  DRIVERS.filter(dv => dv.slab).forEach((dv,i)=>{
    const slab = edged(7.6, 1.5, 8.2, C.g20, 0.75);
    put(slab, cx-1, 1.1 + i*4.4, d.z0-6.5 - i*0.2);
    slab.userData.drvName = dv.id;
    g.add(slab); driverSlabs.push(slab);
  });
  g.add(groundText('DRIVER', cx-5, d.z1+8, 5.0, {color:'#7FD9E6', opacity:0.5}));
}

function BUILD_ring(g,d,cx,cz){
  // per-cpu lanes = troughs
  RING_LANES.length = 0;
  ringRefs.troughs.length = 0; ringRefs.walls.length = 0; ringRefs.caps.length = 0;
  const laneSpan = d.d*0.74;
  for(let i=0;i<8;i++){
    const z = -laneSpan/2 + i*(laneSpan/7);
    RING_LANES.push(z);
    const trough = box(d.x1-d.x0-1, 0.55, 2.5, C.g10, 0.95);
    put(trough, cx, 0.3, z); g.add(trough);
    ringRefs.troughs.push(trough);
    // lane wall — its height tracks buf_size_preset
    const wl = box(d.x1-d.x0-1, 1.5, 0.22, C.g20, 0.34);
    put(wl, cx, 0.9, z+1.42); g.add(wl);
    ringRefs.walls.push(wl);
    // cpu plate
    const cap = box(1.5, 1.4, 2.5, C.g30, 0.9);
    put(cap, d.x0+0.4, 0.85, z); g.add(cap);
    ringRefs.caps.push(cap);
  }
  // shared-memory volume — scales with buf_size_preset
  const shm = edged(d.x1-d.x0+1, 7.4, d.z1-d.z0-1, 0x9FB4BC, 0.14, C.g30);
  put(shm, cx, 3.9, cz); g.add(shm);
  ringRefs.shm = shm;
  // drop pit
  const pit = new THREE.Mesh(
    new THREE.PlaneGeometry(d.x1-d.x0-2, 5),
    new THREE.MeshBasicMaterial({color:C.redUi, transparent:true, opacity:0.15, depthWrite:false})
  );
  pit.rotation.x = -Math.PI/2; pit.position.set(cx, 0.06, d.z1+4.5); g.add(pit);
  g.add(groundText('n_drops', cx+3, d.z1+4.4, 2.4, {color:'#EA5255', mono:true, opacity:0.95}));
  g.add(groundText('BUFFERS', cx-4, d.z1+11, 5.0, {color:'#BBBDBF', opacity:0.4}));
  /* NOT "8 MiB / CPU": 8 MiB is one buffer, and the default modern_ebpf
     shares each buffer between two CPUs — ceil(nCPU / cpus_for_each_buffer) */
  g.add(groundText('1 buffer = 8 MiB (preset 4) · ceil(nCPU ÷ 2) buffers · timestamp-ordered read',
    d.x0, d.z0-6, 2.0, {color:'#A3A5A7', mono:true, opacity:0.9}));
  /* cpu index plates at the head of each lane — the lanes are CPUs, and the
     buffer they share is shown by the trough colour (see applyTuneVisuals) */
  RING_LANES.forEach((z,i)=>{
    g.add(groundText('cpu'+i, d.x0-5.6, z, 1.9,
      {color:'#8A8C8E', mono:true, opacity:0.95}));
  });
}

function BUILD_state(g,d,cx,cz){
  // thread table = dense tower grid
  for(let r=0;r<5;r++) for(let c=0;c<7;c++){
    const x = d.x0+2.6 + c*2.9;
    const z = d.z0+3.4 + r*3.1;
    const h = 3 + ((r*7+c*13)%11)*1.1;
    const t = box(1.7,h,1.7, 0x7FC7DA, 0.62);
    put(t, x, h/2, z); g.add(t);
  }
  // fd table block
  const fd = edged(7, 5, 9, 0x9AD9E8, 0.42);
  put(fd, d.x1-4.2, 2.5, d.z0+6); g.add(fd);
  /* ---- enrichment gantries: three, because there are three sources ----
     One reads the container runtime socket for container.*, one reads the
     same socket for the pod fields, and one reads the API server through the
     k8smeta plugin. Splitting the second and third is the whole point: they
     look like one "Kubernetes metadata" feature and they fail separately.
     Each carries two captions and applyEnvironment picks one. */
  const GANTRIES = [
    { key:'container', z:d.z1-4.5,  col:C.falco, h:13,
      on:'container.* ← socket (約28)',
      off:'container.id / .type のみ ← cgroup' },
    { key:'k8sRuntime', z:d.z1-10.5, col:0x00A8BC, h:11,
      on:'k8s.ns.name · k8s.pod.* ← socket',
      off:'k8s.pod.* なし (socket 不可)' },
    { key:'k8sApi', z:d.z1-16.5, col:C.purple, h:9,
      on:'k8smeta.deployment.name ← apiserver',
      off:'k8s.deployment.name = <NA>' }
  ];
  GANTRIES.forEach(gd=>{
    const gantry = new THREE.Group();
    const span = d.x1-d.x0-3;
    const beam = box(span, 0.8, 1.0, gd.col, 0.8);
    put(beam, cx, gd.h, gd.z); gantry.add(beam);
    [-1,1].forEach(s=>{
      const leg = box(0.8, gd.h, 0.8, gd.col, 0.42);
      put(leg, cx + s*span/2, gd.h/2, gd.z); gantry.add(leg);
    });
    g.add(gantry);
    stateRefs.gantries[gd.key] = gantry;

    const mk = txt => {
      const t = groundText(txt, cx, gd.z+2.2, 1.3,
        {color:'#8A8C8E', mono:true, opacity:0.92, y:0.14});
      t.visible = false; g.add(t); return t;
    };
    const pair = { on:mk(gd.on), off:mk(gd.off) };
    /* the container gantry's two states are "everything" and "the two the
       kernel can answer", so name them for what they are */
    stateRefs.labels[gd.key] = gd.key === 'container'
      ? { full:pair.on, min:pair.off } : pair;
  });
  // enclosing volume
  const vol = edged(d.x1-d.x0+1, d.top, d.z1-d.z0+1, 0x9AD9E8, 0.09, C.g30);
  put(vol, cx, d.top/2, cz); g.add(vol);
  g.add(groundText('ENRICH', cx-2, d.z1+8, 5.0, {color:'#7FD9E6', opacity:0.5}));
  g.add(groundText('thread table · fd table · container · k8s', d.x0, d.z0-6, 2.3,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
}

function BUILD_rules(g,d,cx,cz){
  // priority towers (right side)
  const prios = [
    ['EMERGENCY',C.purple,15],['CRITICAL',C.purple,13],['ERROR',C.redUi,11],
    ['WARNING',C.orange,9],['NOTICE',C.falco,7],['INFO',C.g30,5]
  ];
  prios.forEach((p,i)=>{
    const h = p[2]*1.5;
    const t = edged(2.7, h, 2.7, p[1], 0.72);
    put(t, d.x1-3.2, h/2, d.z0+3.2 + i*3.1); g.add(t);
  });
  // rule blocks grid = ruleset
  RULE_BLOCKS.length = 0;
  for(let r=0;r<6;r++) for(let c=0;c<6;c++){
    const x = d.x0+3.2 + c*2.7;
    const z = d.z0+3.6 + r*3.0;
    const h = 2.2 + ((r*5+c*11)%6)*0.8;
    const b = box(1.9,h,1.9, 0xC9AEDA, 0.5);
    put(b, x, h/2, z); g.add(b);
    RULE_BLOCKS.push(b);
  }
  // engine shell
  const shell = edged(d.x1-d.x0+1, d.top, d.z1-d.z0+1, 0xD9C0E4, 0.1, C.g30);
  put(shell, cx, d.top/2, cz); g.add(shell);
  // condition arch
  const arch = box(1.2, d.top-4, d.z1-d.z0-2, C.purple, 0.13);
  put(arch, d.x0+1.2, (d.top-4)/2, cz); g.add(arch);
  g.add(groundText('MATCH', cx-1, d.z1+8, 5.0, {color:'#CA87DA', opacity:0.45}));
  g.add(groundText('per-event-type ruleset · macros · lists · exceptions', d.x0, d.z0-6, 2.3,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
}

function BUILD_outputs(g,d,cx,cz){
  // three output pipes
  const pipes = [['stdout / file / syslog', 8],['gRPC output API', 0],['falcosidekick', -8]];
  OUT_PIPES.length = 0; outRefs.pipes.length = 0;
  pipes.forEach(([lbl,z],i)=>{
    const p = box(d.x1-d.x0-2, 2.2, 3.2, i===2?C.lumin:C.g20, i===2?0.9:0.7);
    put(p, cx, 2.4, z); g.add(p);
    OUT_PIPES.push(z);
    outRefs.pipes.push(p);
  });
  // sidekick fan-out towers
  for(let i=0;i<6;i++){
    const h = 3 + (i%3)*2.4;
    const t = box(1.5,h,1.5, C.lumin, 0.9);
    put(t, d.x1-1.5, h/2, d.z0+2.5 + i*2.4); g.add(t);
  }
  // talon block
  const talon = edged(5.2, 6, 5.2, C.lumin, 0.55);
  put(talon, d.x0+3.6, 3, d.z1-4); g.add(talon);
  const vol = edged(d.x1-d.x0+1, d.top, d.z1-d.z0+1, C.lumin, 0.1, C.g30);
  put(vol, cx, d.top/2, cz); g.add(vol);
  g.add(groundText('ALERT', cx, d.z1+8, 5.0, {color:'#9FD66A', opacity:0.5}));
  g.add(groundText('slack · loki · elastic · alertmanager · s3 · kafka', d.x0-2, d.z0-6, 2.2,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
}

/* ---------- one audit route per orchestrator ----------
   The k8saudit lane is where the orchestrator axis is actually visible, and
   the shapes genuinely differ:

     self-managed  the apiserver pushes over a webhook into the Falco that is
                   already watching syscalls. No second installation.
     managed       the apiserver's flags are not yours, so no webhook can be
                   pointed anywhere. A provider plugin PULLS from the log sink,
                   and that means a separate installation that collects.

   For EKS the official Helm values pin that installation exactly:
   controller.kind: deployment / replicas: 1 / driver.enabled: false /
   collectors.enabled: false — one pod, no driver, no collectors, because two
   pods would pull the same CloudWatch stream twice and duplicate every alert.
   GKE says the opposite (Pub/Sub exactly-once lets you run several) and AKS
   says nothing, so only EKS draws the disabled slots and the "replicas: 1"
   plate. A model that generalised this would be teaching a false constraint. */
function buildAuditRoute(orch, d){
  const a = orch.audit;
  if(!a) return null;
  const grp = new THREE.Group();
  const x = ax => d.x0 + ax, z = az => d.z0 + az;

  /* the apiserver, and the sink or webhook the audit events leave through */
  const srv = edged(4.2, 9, 4.2, C.falco, 0.6);
  put(srv, x(16), 0.7+4.5, z(6)); grp.add(srv);
  grp.add(groundText('kube-apiserver', x(11.4), z(1.4), 1.4,
    {color:'#00A8BC', mono:true, opacity:0.95, y:0.75}));

  const sink = edged(3.6, a.pull ? 6 : 4, 3.6, 0xF3C99A, 0.7);
  put(sink, x(16), 0.7+(a.pull?3:2), z(15)); grp.add(sink);
  grp.add(groundText(a.transport, x(15), z(20), 1.35,
    {color:'#A3A5A7', mono:true, opacity:0.92, y:0.75}));
  /* pull points east into the collector, push points west into the DaemonSet */
  for(let i=0;i<3;i++)
    grp.add(chevron(x(a.pull ? 19.5+i*2.4 : 12.5-i*2.4), z(15), 1.5,
      0xF3C99A, 0.45, a.pull ? 0 : Math.PI));

  if(a.controller === 'deployment'){
    /* a Deployment, drawn as a deck carrying exactly as many pods as the
       sources permit — one for EKS, several for GKE */
    const n = a.replicas ?? 1;
    const dw = 13, dd = 13, dx = x(27), dz = z(11);
    const deck = box(dw, 1.0, dd, C.g10, 0.95);
    put(deck, dx, 0.36+0.5, dz); grp.add(deck);
    const rim = new THREE.LineSegments(
      new THREE.EdgesGeometry(new THREE.BoxGeometry(dw, 1.0, dd)), edgeMat(C.purple, 0.7));
    put(rim, dx, 0.36+0.5, dz); grp.add(rim);

    for(let i=0;i<n;i++){
      const pz = dz + (i - (n-1)/2) * 3.6;
      const pod = edged(4.4, 5.2, 3.0, C.falco, 0.9);
      put(pod, dx-1.6, 1.36+2.6, pz); grp.add(pod);
    }
    grp.add(groundText(a.lbl, x(20), z(21.8), 1.35,
      {color:'#B15FC4', mono:true, opacity:0.95, y:0.75}));

    /* the two things this installation explicitly does NOT have, drawn as
       empty slots so the absence is a building and not a missing label */
    const off = [];
    if(a.driver === false)     off.push('driver.enabled: false');
    if(a.collectors === false) off.push('collectors.enabled: false');
    off.forEach((lbl,i)=>{
      const slot = box(3.8, 3.4, 2.6, C.redUi, 0.06);
      put(slot, dx+3.4, 1.36+1.7, dz - 3.2 + i*4.6); grp.add(slot);
      const cage = new THREE.LineSegments(
        new THREE.EdgesGeometry(new THREE.BoxGeometry(3.8, 3.4, 2.6)),
        edgeMat(C.redUi, 0.55));
      put(cage, dx+3.4, 1.36+1.7, dz - 3.2 + i*4.6); grp.add(cage);
      /* the caption goes north of the deck rather than beside the slot: at
         1280×720 a label on the east edge runs out of the district */
      grp.add(groundText(lbl, dx+1, z(3.4 + i*2.2), 1.0,
        {color:'#B23A3D', mono:true, opacity:0.95, y:1.5}));
    });
    if(a.single)
      grp.add(groundText('単一インスタンス必須 — 2つ動かすとアラートが重複する',
        x(19), z(24.4), 1.4, {color:'#B23A3D', mono:true, opacity:0.95, y:0.75}));
  } else {
    /* no separate installation at all: the webhook lands on the Falco that is
       already there, so the route is a label and an arrow pointing west */
    grp.add(groundText(a.lbl, x(19), z(9.5), 1.5,
      {color:'#00A8BC', mono:true, opacity:0.95, y:0.75}));
    grp.add(groundText('監査用の別インスタンスは要らない', x(19), z(13), 1.4,
      {color:'#A3A5A7', mono:true, opacity:0.9, y:0.75}));
  }
  return grp;
}

function BUILD_plugins(g,d,cx,cz){
  const plat = box(d.x1-d.x0-1, 0.7, d.z1-d.z0-1, C.g10, 0.85);
  put(plat, cx, 0.36, cz); g.add(plat);

  /* cloud / identity sources — available whatever the environment is */
  ['cloudtrail','okta','github','gcpaudit'].forEach((nm,i)=>{
    const h = 4 + (i%3)*2.2;
    const b = edged(3.4, h, 3.4, 0xF3C99A, 0.62);
    put(b, d.x0+3.5 + (i%2)*6.2, 0.7+h/2, d.z0+4 + Math.floor(i/2)*7.5);
    g.add(b);
    g.add(groundText(nm, d.x0+1.7 + (i%2)*6.2, d.z0+7.6 + Math.floor(i/2)*7.5, 1.35,
      {color:'#A3A5A7', mono:true, opacity:0.9, y:0.75}));
  });

  /* the k8saudit half, once per declared orchestrator. Adding a provider is a
     declaration in ORCH; this loop and applyEnvironment need nothing. */
  for(const orch of ORCH){
    const route = buildAuditRoute(orch, d);
    if(!route) continue;
    route.visible = false;
    g.add(route);
    deployRefs.auditRoutes[orch.id] = route;
  }

  g.add(groundText('PLUGINS', cx-1, d.z1+5.5, 4.2, {color:'#E0B183', opacity:0.5}));
  g.add(groundText('no driver · no ring buffer · ルールはソース間で相関しない',
    cx-8, d.z0-4.5, 2.2, {color:'#A3A5A7', mono:true, opacity:0.9}));
}

function BUILD_falcoctl(g,d,cx,cz){
  const plat = box(d.x1-d.x0-1, 0.7, d.z1-d.z0-1, C.g10, 0.9);
  put(plat, cx, 0.36, cz); g.add(plat);

  // the registry the artifacts come from
  const reg = edged(3.6, 11, 3.6, C.g40, 0.7);
  put(reg, d.x0+3.2, 0.7+5.5, cz); g.add(reg);
  g.add(groundText('OCI registry', d.x0+0.8, d.z0+1.4, 1.4,
    {color:'#8A8C8E', mono:true, opacity:0.95, y:0.75}));

  // one crate per maturity level — only stable ships in the package
  [['stable',0,C.lumin,5.5,0.95],['incubating',1,0xC9AEDA,4,0.7],['sandbox',2,C.g20,2.8,0.55]]
    .forEach(([lbl,i,col,h,op])=>{
      const b = edged(3.6, h, 4.2, col, op);
      put(b, d.x0+9.4 + i*3.6, 0.7+h/2, cz); g.add(b);
      g.add(groundText(lbl, d.x0+8.0 + i*3.6, d.z1-2.2, 1.25,
        {color:'#8A8C8E', mono:true, opacity:0.9, y:0.75, rotZ:-Math.PI/2}));
    });

  // artifacts head south, into the rules engine
  for(let i=0;i<3;i++) g.add(chevron(cx+2, d.z1+2 + i*3.2, 1.9, 0xC9AEDA, 0.4, -Math.PI/2));

  g.add(groundText('falcoctl', cx-5, d.z0-3.4, 3.2, {color:'#C9AEDA', opacity:0.6}));
  g.add(groundText('artifact install / follow → rules_files', d.x0, d.z0-6.6, 1.9,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
}

function BUILD_sysdig(g,d,cx,cz){
  const w=d.x1-d.x0, dp=d.z1-d.z0;
  // deck
  const deck = box(w, 1.5, dp, C.deepSee, 0.94);
  put(deck, cx, 0.75, cz); g.add(deck);
  const rimL = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.BoxGeometry(w,1.5,dp)),
    new THREE.LineBasicMaterial({color:C.lumin, transparent:true, opacity:0.75})
  );
  put(rimL, cx, 0.75, cz); g.add(rimL);
  // capability blocks
  const caps = [
    ['Threat Detection', -16, -9, C.lumin, 6],
    ['Runtime Insights', -4, -9, C.lumin, 8.5],
    ['Posture / CIEM',    8, -9, 0x4A8C93, 5],
    ['Activity Audit', -16,  4, 0x4A8C93, 4],
    ['Captures (.scap)', -4, 4, 0x4A8C93, 5.5],
    ['Response / Sage', 10,  4, C.lumin, 7]
  ];
  caps.forEach(([lbl,ox,oz,col,h])=>{
    const b = box(9, h, 8.5, col, col===C.lumin?0.92:0.6);
    put(b, cx+ox, 1.5+h/2, cz+oz); g.add(b);
  });
  g.add(groundText('SYSDIG SECURE', cx-6, d.z1+5, 5.2,
    {color:'#01353E', opacity:0.9, y:1.6}));
  g.add(groundText('same libs · same falco engine', cx-8, d.z1+9.5, 2.3,
    {color:'#4A8C93', mono:true, opacity:0.95, y:1.6}));
  // support columns down to ground
  [[-w/2+5,-dp/2+5],[w/2-5,-dp/2+5],[-w/2+5,dp/2-5],[w/2-5,dp/2-5]].forEach(([ox,oz])=>{
    const col = box(0.6, d.y, 0.6, C.g20, 0.22);
    put(col, cx+ox, -d.y/2, cz+oz); g.add(col);
  });
  sysdigGroup = g;
}


/* ============================================================
   6b. Sysdig Shield overlay
   Per Sysdig docs, Sysdig Shield is two components replacing the classic
   agent: Host Shield (DaemonSet, standalone binary, or container — node
   scoped) and Cluster Shield (Deployment — cluster scoped: admission
   control, audit, container vulnerability management, posture).
   Host Shield is the part that owns the districts we just walked through.
   ============================================================ */
(function shieldOverlay(){
  /* HOST SHIELD — a boundary drawn around driver → outputs */
  const hs = new THREE.Group();
  const first = byId('driver'), last = byId('outputs');
  const band = Math.max(...DISTRICTS.filter(isFlow).map(k=>k.d))/2 + 1;
  const x0=first.x0-3, x1=last.x1+3, z0=-band, z1=band, h=30;
  const shell = new THREE.Mesh(
    new THREE.BoxGeometry(x1-x0, h, z1-z0),
    new THREE.MeshBasicMaterial({color:C.deepSee, transparent:true, opacity:0.035, depthWrite:false}));
  shell.position.set((x0+x1)/2, h/2, (z0+z1)/2); hs.add(shell);
  const shellL = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.BoxGeometry(x1-x0, h, z1-z0)), edgeMat(C.deepSee, 0.34));
  shellL.position.copy(shell.position); hs.add(shellL);
  hs.add(groundText('HOST SHIELD — node scoped', x0+2, z1+2.4, 2.4,
    {color:'#01353E', mono:true, opacity:0.8}));
  world.add(hs);
  deployRefs.hostShield = hs;

  /* CLUSTER SHIELD — a cluster-scoped Deployment. No source states a replica
     count, so this draws one deck and says "cluster scoped" rather than "1".
     It sits just north of the plugin district because that is the lane it
     works in (admission / audit / posture / vuln mgmt) — inside it would now
     collide with the audit route the orchestrator axis builds there. */
  const cs = new THREE.Group();
  const cp = byId('plugins');
  const csx = cp.cx, csz = cp.z0 - 9;
  const deck = box(15, 1.2, 13, C.deepSee, 0.94);
  put(deck, csx, 0.6, csz); cs.add(deck);
  const rim = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.BoxGeometry(15,1.2,13)), edgeMat(C.lumin, 0.8));
  put(rim, csx, 0.6, csz); cs.add(rim);
  [['admission',-4.6,-3.4,7],['audit',0.6,-3.4,5],
   ['posture',-4.6,3.4,6],['vuln mgmt',0.6,3.4,4.4]].forEach(([lbl,ox,oz,bh])=>{
    const b = box(4.2, bh, 4.6, C.lumin, 0.9);
    put(b, csx+ox, 1.2+bh/2, csz+oz); cs.add(b);
  });
  cs.add(groundText('CLUSTER SHIELD — cluster scoped (Deployment)', csx-11, csz+9.5, 2.1,
    {color:'#01353E', mono:true, opacity:0.9}));
  world.add(cs);
  deployRefs.clusterShield = cs;
})();

/* the registry city.js wires onto each district */
const BUILDERS = {
  workloads:BUILD_workloads, driver:BUILD_driver, ring:BUILD_ring, state:BUILD_state,
  rules:BUILD_rules, outputs:BUILD_outputs, plugins:BUILD_plugins,
  falcoctl:BUILD_falcoctl, sysdig:BUILD_sysdig
};

export {
  BUILDERS,
  applyEnvironment,
  topoVariants,
  captionRefs,
  driverSlabs,
  RING_LANES,
  RULE_BLOCKS,
  OUT_PIPES,
  ringRefs,
  outRefs,
  stateRefs,
  deployRefs,
  sysdigGroup
};
