/* Generated by the module split. See README §開発の分担. */
import * as THREE from 'three';
import { C } from './palette.js';
import { DISTRICTS, byId, isFlow } from './layout.js';
import { edgeMat, box, edged, put, chevron, groundText } from './mesh.js';
import { world } from './scene.js';


/* ============================================================
   6. builders
   ============================================================ */
/* shared handles the builders (section 6) fill in.
   Declared here because the build loop below runs before their bodies. */
const driverSlabs = [];
const RING_LANES  = [];
const RULE_BLOCKS = [];
const OUT_PIPES   = [];
let sysdigGroup = null;
/* pieces the tuning panel reshapes at runtime */
const ringRefs  = { shm:null, troughs:[], walls:[], caps:[] };
const outRefs   = { pipes:[] };
const stateRefs  = { gantries:{} };
/* west-end variants + the Sysdig Shield overlay, toggled by deploy / mode */
const deployRefs = { wlK8s:null, wlHost:null, apiServer:null, clusterShield:null, hostShield:null };

function BUILD_workloads(g,d,cx,cz){
  /* Two completely different west ends, because a cluster and a single host
     are not the same picture. Both are built once and toggled by setDeploy. */

  /* ---------- variant A: Kubernetes — three node pads in a cluster ---------- */
  const k8s = new THREE.Group();
  const NODE_Z = [-d.d/3.2, 0, d.d/3.2];
  NODE_Z.forEach((nz, n)=>{
    const pad = box(24, 0.9, 10.4, C.g10, 0.95);
    put(pad, cx, 0.45, nz); k8s.add(pad);
    const rim = new THREE.LineSegments(
      new THREE.EdgesGeometry(new THREE.BoxGeometry(24, 0.9, 10.4)),
      edgeMat(C.g20, 0.7));
    put(rim, cx, 0.45, nz); k8s.add(rim);

    // pods on the node
    for(let c=0;c<5;c++){
      const x = cx-9.6 + c*4.8;
      const h = 3.2 + ((n*7+c*13)%5)*1.5;
      const b = edged(3.2, h, 4.4, c%4===0 ? 0xF3C99A : C.g20, 0.52);
      put(b, x, 0.9+h/2, nz); k8s.add(b);
      const a = box(0.9,0.9,0.9, c%3===0 ? C.orange : C.g40, 1);
      put(a, x, 0.9+h+0.9, nz); k8s.add(a);
    }
    // Host Shield / falco pod on every node — that is what a DaemonSet is
    const ds = edged(2.6, 2.6, 2.6, C.falco, 0.92);
    put(ds, cx+11.0, 0.9+1.3, nz); k8s.add(ds);
    k8s.add(groundText('node-'+(n+1), cx-13.6, nz, 1.7,
      {color:'#8A8C8E', mono:true, opacity:0.95, y:0.12}));
  });
  // cluster boundary
  const cb = new THREE.Mesh(
    new THREE.PlaneGeometry(30, 42),
    new THREE.MeshBasicMaterial({color:C.falco, transparent:true, opacity:0.05, depthWrite:false}));
  cb.rotation.x = -Math.PI/2; cb.position.set(cx, 0.02, cz); k8s.add(cb);
  const cbl = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.PlaneGeometry(30, 42)), edgeMat(C.falco, 0.5));
  cbl.rotation.x = -Math.PI/2; cbl.position.set(cx, 0.03, cz); k8s.add(cbl);
  k8s.add(groundText('KUBERNETES CLUSTER · 3 NODES · DAEMONSET', cx-14, d.z1+4, 2.0,
    {color:'#00A8BC', mono:true, opacity:0.95}));
  g.add(k8s);

  /* ---------- variant B: one machine, no cluster ---------- */
  const host = new THREE.Group();
  const slab = box(26, 1.4, 34, C.g10, 0.96);
  put(slab, cx, 0.7, cz); host.add(slab);
  const slabRim = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.BoxGeometry(26, 1.4, 34)), edgeMat(C.g30, 0.6));
  put(slabRim, cx, 0.7, cz); host.add(slabRim);
  // fewer, taller, named host processes
  const PROCS = [['systemd',13],['sshd',7],['nginx',16],['cron',5],
                 ['postgres',19],['node',11],['dockerd',9],['rsyslog',6]];
  PROCS.forEach(([nm,h],i)=>{
    const x = cx - 9.5 + (i%4)*6.3;
    const z = cz - 7.5 + Math.floor(i/4)*15;
    const b = edged(4.0, h, 5.0, i%3===0 ? C.g30 : C.g20, 0.55);
    put(b, x, 1.4+h/2, z); host.add(b);
    const a = box(1.2,1.2,1.2, C.g50, 1);
    put(a, x, 1.4+h+1.0, z); host.add(a);
    host.add(groundText(nm, x-2.4, z+3.4, 1.5,
      {color:'#8A8C8E', mono:true, opacity:0.9, y:1.5}));
  });
  // single Host Shield / falco.service
  const svc = edged(4.4, 4.4, 4.4, C.falco, 0.92);
  put(svc, cx+11.4, 1.4+2.2, cz); host.add(svc);
  host.add(groundText('SINGLE HOST · falco.service (systemd)', cx-13, d.z1+4, 2.0,
    {color:'#00A8BC', mono:true, opacity:0.95}));
  g.add(host);

  deployRefs.wlK8s = k8s;
  deployRefs.wlHost = host;

  g.add(groundText('SYSCALLS', cx-1, d.z1+8, 5.0, {color:'#BBBDBF', opacity:0.4}));
  g.add(groundText('kernel boundary →', d.x1+3, d.z0-5, 2.6,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
}

function BUILD_driver(g,d,cx,cz){
  // gate wall with tracepoint pillars
  const wall = edged(3.2, d.top, d.z1-d.z0-2, C.falco, 0.2, C.falco);
  put(wall, cx+3.4, d.top/2, cz); g.add(wall);
  for(let z=d.z0+3; z<=d.z1-3; z+=4.2){
    const h = 5 + (Math.abs(z)%7);
    const p = box(1.5,h,1.5, C.falco, 0.85);
    put(p, cx-3.2, h/2, z); g.add(p);
  }
  // three driver slabs (selectable)
  const names = ['modern_ebpf','ebpf','kmod'];
  driverSlabs.length = 0;
  names.forEach((nm,i)=>{
    const slab = edged(7.6, 1.5, 8.2, C.g20, 0.75);
    put(slab, cx-1, 1.1 + i*4.4, d.z0-6.5 - i*0.2);
    slab.userData.drvName = nm;
    g.add(slab); driverSlabs.push(slab);
  });
  g.add(groundText('DRIVER', cx-5, d.z1+8, 5.0, {color:'#7FD9E6', opacity:0.5}));
}

function BUILD_ring(g,d,cx,cz){
  // per-cpu lanes = troughs
  RING_LANES.length = 0;
  ringRefs.troughs.length = 0; ringRefs.walls.length = 0; ringRefs.caps.length = 0;
  const laneSpan = d.d*0.74;
  for(let i=0;i<8;i++){
    const z = -laneSpan/2 + i*(laneSpan/7);
    RING_LANES.push(z);
    const trough = box(d.x1-d.x0-1, 0.55, 2.5, C.g10, 0.95);
    put(trough, cx, 0.3, z); g.add(trough);
    ringRefs.troughs.push(trough);
    // lane wall — its height tracks buf_size_preset
    const wl = box(d.x1-d.x0-1, 1.5, 0.22, C.g20, 0.34);
    put(wl, cx, 0.9, z+1.42); g.add(wl);
    ringRefs.walls.push(wl);
    // cpu plate
    const cap = box(1.5, 1.4, 2.5, C.g30, 0.9);
    put(cap, d.x0+0.4, 0.85, z); g.add(cap);
    ringRefs.caps.push(cap);
  }
  // shared-memory volume — scales with buf_size_preset
  const shm = edged(d.x1-d.x0+1, 7.4, d.z1-d.z0-1, 0x9FB4BC, 0.14, C.g30);
  put(shm, cx, 3.9, cz); g.add(shm);
  ringRefs.shm = shm;
  // drop pit
  const pit = new THREE.Mesh(
    new THREE.PlaneGeometry(d.x1-d.x0-2, 5),
    new THREE.MeshBasicMaterial({color:C.redUi, transparent:true, opacity:0.15, depthWrite:false})
  );
  pit.rotation.x = -Math.PI/2; pit.position.set(cx, 0.06, d.z1+4.5); g.add(pit);
  g.add(groundText('n_drops', cx+3, d.z1+4.4, 2.4, {color:'#EA5255', mono:true, opacity:0.95}));
  g.add(groundText('PER-CPU', cx-4, d.z1+11, 5.0, {color:'#BBBDBF', opacity:0.4}));
  g.add(groundText('8 MiB / CPU · timestamp-ordered read', d.x0, d.z0-6, 2.3,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
  /* cpu index plates at the head of each lane */
  RING_LANES.forEach((z,i)=>{
    g.add(groundText('cpu'+i, d.x0-5.6, z, 1.9,
      {color:'#8A8C8E', mono:true, opacity:0.95}));
  });
}

function BUILD_state(g,d,cx,cz){
  // thread table = dense tower grid
  for(let r=0;r<5;r++) for(let c=0;c<7;c++){
    const x = d.x0+2.6 + c*2.9;
    const z = d.z0+3.4 + r*3.1;
    const h = 3 + ((r*7+c*13)%11)*1.1;
    const t = box(1.7,h,1.7, 0x7FC7DA, 0.62);
    put(t, x, h/2, z); g.add(t);
  }
  // fd table block
  const fd = edged(7, 5, 9, 0x9AD9E8, 0.42);
  put(fd, d.x1-4.2, 2.5, d.z0+6); g.add(fd);
  // enrichment gantries — container / k8s metadata (k8s one is deploy-dependent)
  [['container',d.z1-4.5,C.falco],['k8s',d.z1-9.5,C.purple]].forEach(([lbl,z,col],i)=>{
    const gantry = new THREE.Group();
    const beam = box(d.x1-d.x0-3, 0.8, 1.0, col, 0.8);
    put(beam, cx, 13, z); gantry.add(beam);
    [-1,1].forEach(s=>{
      const leg = box(0.8, 13, 0.8, col, 0.42);
      put(leg, cx + s*(d.x1-d.x0-3)/2, 6.5, z); gantry.add(leg);
    });
    g.add(gantry);
    stateRefs.gantries[lbl] = gantry;
  });
  // enclosing volume
  const vol = edged(d.x1-d.x0+1, d.top, d.z1-d.z0+1, 0x9AD9E8, 0.09, C.g30);
  put(vol, cx, d.top/2, cz); g.add(vol);
  g.add(groundText('ENRICH', cx-2, d.z1+8, 5.0, {color:'#7FD9E6', opacity:0.5}));
  g.add(groundText('thread table · fd table · container · k8s', d.x0, d.z0-6, 2.3,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
}

function BUILD_rules(g,d,cx,cz){
  // priority towers (right side)
  const prios = [
    ['EMERGENCY',C.purple,15],['CRITICAL',C.purple,13],['ERROR',C.redUi,11],
    ['WARNING',C.orange,9],['NOTICE',C.falco,7],['INFO',C.g30,5]
  ];
  prios.forEach((p,i)=>{
    const h = p[2]*1.5;
    const t = edged(2.7, h, 2.7, p[1], 0.72);
    put(t, d.x1-3.2, h/2, d.z0+3.2 + i*3.1); g.add(t);
  });
  // rule blocks grid = ruleset
  RULE_BLOCKS.length = 0;
  for(let r=0;r<6;r++) for(let c=0;c<6;c++){
    const x = d.x0+3.2 + c*2.7;
    const z = d.z0+3.6 + r*3.0;
    const h = 2.2 + ((r*5+c*11)%6)*0.8;
    const b = box(1.9,h,1.9, 0xC9AEDA, 0.5);
    put(b, x, h/2, z); g.add(b);
    RULE_BLOCKS.push(b);
  }
  // engine shell
  const shell = edged(d.x1-d.x0+1, d.top, d.z1-d.z0+1, 0xD9C0E4, 0.1, C.g30);
  put(shell, cx, d.top/2, cz); g.add(shell);
  // condition arch
  const arch = box(1.2, d.top-4, d.z1-d.z0-2, C.purple, 0.13);
  put(arch, d.x0+1.2, (d.top-4)/2, cz); g.add(arch);
  g.add(groundText('MATCH', cx-1, d.z1+8, 5.0, {color:'#CA87DA', opacity:0.45}));
  g.add(groundText('per-event-type ruleset · macros · lists · exceptions', d.x0, d.z0-6, 2.3,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
}

function BUILD_outputs(g,d,cx,cz){
  // three output pipes
  const pipes = [['stdout / file / syslog', 8],['gRPC output API', 0],['falcosidekick', -8]];
  OUT_PIPES.length = 0; outRefs.pipes.length = 0;
  pipes.forEach(([lbl,z],i)=>{
    const p = box(d.x1-d.x0-2, 2.2, 3.2, i===2?C.lumin:C.g20, i===2?0.9:0.7);
    put(p, cx, 2.4, z); g.add(p);
    OUT_PIPES.push(z);
    outRefs.pipes.push(p);
  });
  // sidekick fan-out towers
  for(let i=0;i<6;i++){
    const h = 3 + (i%3)*2.4;
    const t = box(1.5,h,1.5, C.lumin, 0.9);
    put(t, d.x1-1.5, h/2, d.z0+2.5 + i*2.4); g.add(t);
  }
  // talon block
  const talon = edged(5.2, 6, 5.2, C.lumin, 0.55);
  put(talon, d.x0+3.6, 3, d.z1-4); g.add(talon);
  const vol = edged(d.x1-d.x0+1, d.top, d.z1-d.z0+1, C.lumin, 0.1, C.g30);
  put(vol, cx, d.top/2, cz); g.add(vol);
  g.add(groundText('ALERT', cx, d.z1+8, 5.0, {color:'#9FD66A', opacity:0.5}));
  g.add(groundText('slack · loki · elastic · alertmanager · s3 · kafka', d.x0-2, d.z0-6, 2.2,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
}

function BUILD_plugins(g,d,cx,cz){
  const plat = box(d.x1-d.x0-1, 0.7, d.z1-d.z0-1, C.g10, 0.85);
  put(plat, cx, 0.36, cz); g.add(plat);

  /* cloud / identity sources — available whatever the deployment is */
  ['cloudtrail','okta','github','gcpaudit'].forEach((nm,i)=>{
    const h = 4 + (i%3)*2.2;
    const b = edged(3.4, h, 3.4, 0xF3C99A, 0.62);
    put(b, d.x0+3.5 + (i%2)*6.2, 0.7+h/2, d.z0+4 + Math.floor(i/2)*7.5);
    g.add(b);
    g.add(groundText(nm, d.x0+1.7 + (i%2)*6.2, d.z0+7.6 + Math.floor(i/2)*7.5, 1.35,
      {color:'#A3A5A7', mono:true, opacity:0.9, y:0.75}));
  });

  /* k8saudit needs an API server, so this half only exists on a cluster */
  const api = new THREE.Group();
  const srv = edged(4.2, 9, 4.2, C.falco, 0.6);
  put(srv, d.x1-4.2, 0.7+4.5, d.z0+5); api.add(srv);
  const audit = edged(3.4, 5, 3.4, 0xF3C99A, 0.7);
  put(audit, d.x1-4.2, 0.7+2.5, d.z0+13); api.add(audit);
  api.add(groundText('kube-apiserver', d.x1-8.4, d.z0+1.2, 1.5,
    {color:'#00A8BC', mono:true, opacity:0.95, y:0.75}));
  api.add(groundText('k8saudit', d.x1-6.2, d.z0+16.4, 1.5,
    {color:'#A3A5A7', mono:true, opacity:0.9, y:0.75}));
  g.add(api);
  deployRefs.apiServer = api;

  g.add(groundText('PLUGINS', cx-1, d.z1+5.5, 4.2, {color:'#E0B183', opacity:0.5}));
  g.add(groundText('no driver · no ring buffer', cx-8, d.z0-4.5, 2.2,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
}

function BUILD_falcoctl(g,d,cx,cz){
  const plat = box(d.x1-d.x0-1, 0.7, d.z1-d.z0-1, C.g10, 0.9);
  put(plat, cx, 0.36, cz); g.add(plat);

  // the registry the artifacts come from
  const reg = edged(3.6, 11, 3.6, C.g40, 0.7);
  put(reg, d.x0+3.2, 0.7+5.5, cz); g.add(reg);
  g.add(groundText('OCI registry', d.x0+0.8, d.z0+1.4, 1.4,
    {color:'#8A8C8E', mono:true, opacity:0.95, y:0.75}));

  // one crate per maturity level — only stable ships in the package
  [['stable',0,C.lumin,5.5,0.95],['incubating',1,0xC9AEDA,4,0.7],['sandbox',2,C.g20,2.8,0.55]]
    .forEach(([lbl,i,col,h,op])=>{
      const b = edged(3.6, h, 4.2, col, op);
      put(b, d.x0+9.4 + i*3.6, 0.7+h/2, cz); g.add(b);
      g.add(groundText(lbl, d.x0+8.0 + i*3.6, d.z1-2.2, 1.25,
        {color:'#8A8C8E', mono:true, opacity:0.9, y:0.75, rotZ:-Math.PI/2}));
    });

  // artifacts head south, into the rules engine
  for(let i=0;i<3;i++) g.add(chevron(cx+2, d.z1+2 + i*3.2, 1.9, 0xC9AEDA, 0.4, -Math.PI/2));

  g.add(groundText('falcoctl', cx-5, d.z0-3.4, 3.2, {color:'#C9AEDA', opacity:0.6}));
  g.add(groundText('artifact install / follow → rules_files', d.x0, d.z0-6.6, 1.9,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
}

function BUILD_sysdig(g,d,cx,cz){
  const w=d.x1-d.x0, dp=d.z1-d.z0;
  // deck
  const deck = box(w, 1.5, dp, C.deepSee, 0.94);
  put(deck, cx, 0.75, cz); g.add(deck);
  const rimL = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.BoxGeometry(w,1.5,dp)),
    new THREE.LineBasicMaterial({color:C.lumin, transparent:true, opacity:0.75})
  );
  put(rimL, cx, 0.75, cz); g.add(rimL);
  // capability blocks
  const caps = [
    ['Threat Detection', -16, -9, C.lumin, 6],
    ['Runtime Insights', -4, -9, C.lumin, 8.5],
    ['Posture / CIEM',    8, -9, 0x4A8C93, 5],
    ['Activity Audit', -16,  4, 0x4A8C93, 4],
    ['Captures (.scap)', -4, 4, 0x4A8C93, 5.5],
    ['Response / Sage', 10,  4, C.lumin, 7]
  ];
  caps.forEach(([lbl,ox,oz,col,h])=>{
    const b = box(9, h, 8.5, col, col===C.lumin?0.92:0.6);
    put(b, cx+ox, 1.5+h/2, cz+oz); g.add(b);
  });
  g.add(groundText('SYSDIG SECURE', cx-6, d.z1+5, 5.2,
    {color:'#01353E', opacity:0.9, y:1.6}));
  g.add(groundText('same libs · same falco engine', cx-8, d.z1+9.5, 2.3,
    {color:'#4A8C93', mono:true, opacity:0.95, y:1.6}));
  // support columns down to ground
  [[-w/2+5,-dp/2+5],[w/2-5,-dp/2+5],[-w/2+5,dp/2-5],[w/2-5,dp/2-5]].forEach(([ox,oz])=>{
    const col = box(0.6, d.y, 0.6, C.g20, 0.22);
    put(col, cx+ox, -d.y/2, cz+oz); g.add(col);
  });
  sysdigGroup = g;
}


/* ============================================================
   6b. Sysdig Shield overlay
   Per Sysdig docs, Sysdig Shield is two components replacing the classic
   agent: Host Shield (DaemonSet, standalone binary, or container — node
   scoped) and Cluster Shield (Deployment — cluster scoped: admission
   control, audit, container vulnerability management, posture).
   Host Shield is the part that owns the districts we just walked through.
   ============================================================ */
(function shieldOverlay(){
  /* HOST SHIELD — a boundary drawn around driver → outputs */
  const hs = new THREE.Group();
  const first = byId('driver'), last = byId('outputs');
  const band = Math.max(...DISTRICTS.filter(isFlow).map(k=>k.d))/2 + 1;
  const x0=first.x0-3, x1=last.x1+3, z0=-band, z1=band, h=30;
  const shell = new THREE.Mesh(
    new THREE.BoxGeometry(x1-x0, h, z1-z0),
    new THREE.MeshBasicMaterial({color:C.deepSee, transparent:true, opacity:0.035, depthWrite:false}));
  shell.position.set((x0+x1)/2, h/2, (z0+z1)/2); hs.add(shell);
  const shellL = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.BoxGeometry(x1-x0, h, z1-z0)), edgeMat(C.deepSee, 0.34));
  shellL.position.copy(shell.position); hs.add(shellL);
  hs.add(groundText('HOST SHIELD — node scoped', x0+2, z1+2.4, 2.4,
    {color:'#01353E', mono:true, opacity:0.8}));
  world.add(hs);
  deployRefs.hostShield = hs;

  /* CLUSTER SHIELD — a Deployment, so exactly one of it, beside the cluster */
  const cs = new THREE.Group();
  const deck = box(15, 1.2, 13, C.deepSee, 0.94);
  const cp = byId('plugins');
  put(deck, cp.cx+2, 0.6, cp.cz+4); cs.add(deck);
  const rim = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.BoxGeometry(15,1.2,13)), edgeMat(C.lumin, 0.8));
  put(rim, cp.cx+2, 0.6, cp.cz+4); cs.add(rim);
  [['admission',-4.6,-3.4,7],['audit',0.6,-3.4,5],
   ['posture',-4.6,3.4,6],['vuln mgmt',0.6,3.4,4.4]].forEach(([lbl,ox,oz,bh])=>{
    const b = box(4.2, bh, 4.6, C.lumin, 0.9);
    put(b, cp.cx+2+ox, 1.2+bh/2, cp.cz+4+oz); cs.add(b);
  });
  cs.add(groundText('CLUSTER SHIELD — cluster scoped (Deployment)', cp.cx-9, cp.z1+2.5, 2.1,
    {color:'#01353E', mono:true, opacity:0.9}));
  world.add(cs);
  deployRefs.clusterShield = cs;
})();

/* the registry city.js wires onto each district */
const BUILDERS = {
  workloads:BUILD_workloads, driver:BUILD_driver, ring:BUILD_ring, state:BUILD_state,
  rules:BUILD_rules, outputs:BUILD_outputs, plugins:BUILD_plugins,
  falcoctl:BUILD_falcoctl, sysdig:BUILD_sysdig
};

export {
  BUILDERS,
  driverSlabs,
  RING_LANES,
  RULE_BLOCKS,
  OUT_PIPES,
  ringRefs,
  outRefs,
  stateRefs,
  deployRefs,
  sysdigGroup
};
