/* Generated by the module split. See README §開発の分担. */
import * as THREE from 'three';
import { C } from './palette.js';
import { DISTRICTS, byId, isFlow, LANE_PAD, ST } from './layout.js';
import { S, PRESET_MIB } from './state.js';
import { ORCH, TOPOLOGIES, DRIVERS, currentEnv,
         CLUSTER_NODES, setClusterNodes, NODE_MAX, NODE_PITCH, NODE_MARGIN,
         CPU_MAX, nodeCpus, bufferCount,
         SHIELDS, RULE_FILES, loadedRuleFiles,
         NODE_PAD_W, NODE_PAD_D, POD_PITCH } from './districts.data.js';
import { edgeMat, box, edged, put, chevron, groundText, glow } from './mesh.js';
import { world } from './scene.js';


/* ============================================================
   6. builders
   ============================================================ */
/* shared handles the builders (section 6) fill in.
   Declared here because the build loop below runs before their bodies. */
const driverSlabs = [];
const RING_LANES  = [];
const RULE_BLOCKS = [];
const OUT_PIPES   = [];
let sysdigGroup = null;
/* pieces the tuning panel reshapes at runtime */
/* the ring district's pieces. `troughs`/`walls`/`caps`/`laneLabels` are one per
   POSSIBLE CPU (CPU_MAX of them); applyCpus() shows the ones this node has. */
const ringRefs  = { shm:null, troughs:[], walls:[], caps:[], laneLabels:[],
                    pitch:0, group:null, cpuCaption:null, captionAt:null,
                    /* one per POSSIBLE buffer — the ceiling is one buffer per CPU,
                       reached at cpus_for_each_buffer = 1 */
                    bufShells:[], bufHeads:[], bufCaption:null, bufCaptionAt:null };
const outRefs   = { pipes:[] };
/* the two rulesets, partitioned by event source (§BUILD_rules) */
const ruleRefs  = { syscall:[], plugin:[], divider:null };
/* the kernel/user-space membrane (§6c) */
const kernelRefs = { group:null, zone:null, west:null, east:null,
                     crossing:null, severed:null, eastEdges:[] };
/* the three rule files, as three crates (§BUILD_falcoctl) */
const crateRefs = {};
/* three enrichment gantries, and the field lists each one can attach.
   `labels` holds the alternative captions applyEnvironment switches between. */
const stateRefs  = { gantries:{}, labels:{} };
/* the Sysdig Shield overlay, toggled by stack / environment */
const deployRefs = { clusterShield:null, hostShield:null, auditRoutes:{} };
/* topology id -> west-end group (null when that topology draws none) */
const topoVariants = {};
/* orchestrator id -> the ground caption under the west end. `make` is kept
   beside the mesh because the caption spells the node count out loud, so it has
   to be re-baked when the count changes. */
const captionRefs = {};
/* the cluster's pads, one per POSSIBLE node (NODE_MAX of them). applyNodes()
   shows the ones this cluster has — see §applyNodes. */
const nodeRefs = { pads:[], plates:[], depth:0, group:null };

/* ---------- west-end variants, one per declared topology ----------
   A cluster and a single host are not the same picture, so the west end is
   rebuilt rather than relabelled. There are three shapes and forty-odd
   environments, because geometry only depends on the projection: is there a
   kernel path, and is it a cluster. Both shapes below read their node count,
   pod count and process list from TOPOLOGIES — nothing here knows the
   number three, and nothing here knows an environment id. */

/* a cluster: one pad per node, pods on each, one agent per node.
   Built for NODE_MAX nodes and then packed by applyNodes(), which is the only
   way a scenario's declared node count can reach the ground: the layout engine
   sized this district before any scenario existed. */
function buildNodesVariant(dep, d, cx, cz){
  const grp = new THREE.Group();
  const pods = dep.podsPerNode ?? 0;
  nodeRefs.pads.length = 0; nodeRefs.plates.length = 0;
  nodeRefs.depth = d.d;
  nodeRefs.group = grp;
  for(let n=0;n<NODE_MAX;n++){
    /* one group per node so applyNodes() can move it as a unit, with the PLATE
       in a group of its own inside it. Packing shrinks the plate and nothing
       else: the pods, the agent and the label that names the node keep their
       real proportions, and a narrower plate is what a denser rack looks like
       anyway. */
    const node  = new THREE.Group();
    const plate = new THREE.Group();
    node.add(plate);

    const pad = box(NODE_PAD_W, 0.9, NODE_PAD_D, C.g10, 0.95);
    put(pad, cx, 0.45, 0); plate.add(pad);
    const rim = new THREE.LineSegments(
      new THREE.EdgesGeometry(new THREE.BoxGeometry(NODE_PAD_W, 0.9, NODE_PAD_D)),
      edgeMat(C.g20, 0.7));
    put(rim, cx, 0.45, 0); plate.add(rim);

    for(let c=0;c<pods;c++){
      const x = cx + (c - (pods-1)/2) * POD_PITCH;
      const h = 3.2 + ((n*7+c*13)%5)*1.5;
      const b = edged(3.2, h, 4.4, c%4===0 ? 0xF3C99A : C.g20, 0.52);
      put(b, x, 0.9+h/2, 0); node.add(b);
      const a = box(0.9,0.9,0.9, c%3===0 ? C.orange : C.g40, 1);
      put(a, x, 0.9+h+0.9, 0); node.add(a);
    }
    /* an agent on every node — that is what a DaemonSet is */
    const ds = glow(edged(2.6, 2.6, 2.6, C.falco, 0.92));
    put(ds, cx+11.0, 0.9+1.3, 0); node.add(ds);
    node.add(groundText('node-'+(n+1), cx-13.6, 0, 1.7,
      {color:'#8A8C8E', mono:true, opacity:0.95, y:0.12}));

    grp.add(node);
    nodeRefs.pads.push(node);
    nodeRefs.plates.push(plate);
  }
  applyNodes();

  if(dep.boundary){
    /* the boundary grows with the district, so more nodes stay enclosed */
    const cw = NODE_PAD_W + 6, cd = d.d + 4;
    const cb = new THREE.Mesh(
      new THREE.PlaneGeometry(cw, cd),
      new THREE.MeshBasicMaterial({color:C.falco, transparent:true, opacity:0.05, depthWrite:false}));
    cb.rotation.x = -Math.PI/2; cb.position.set(cx, 0.02, cz); grp.add(cb);
    const cbl = new THREE.LineSegments(
      new THREE.EdgesGeometry(new THREE.PlaneGeometry(cw, cd)), edgeMat(C.falco, 0.5));
    cbl.rotation.x = -Math.PI/2; cbl.position.set(cx, 0.03, cz); grp.add(cbl);
  }
  return grp;
}

/* one machine: a slab carrying named, taller processes and a single agent */
function buildMachineVariant(dep, d, cx, cz){
  const grp = new THREE.Group();
  const sw = dep.slabW, sd = dep.slabD;
  const slab = box(sw, 1.4, sd, C.g10, 0.96);
  put(slab, cx, 0.7, cz); grp.add(slab);
  const slabRim = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.BoxGeometry(sw, 1.4, sd)), edgeMat(C.g30, 0.6));
  put(slabRim, cx, 0.7, cz); grp.add(slabRim);

  const per = dep.procsPerRow;
  const rows = Math.ceil(dep.procs.length / per);
  dep.procs.forEach(([nm,h],i)=>{
    const x = cx + ((i%per) - (per-1)/2) * 6.3;
    const z = cz + (Math.floor(i/per) - (rows-1)/2) * 15;
    const b = edged(4.0, h, 5.0, i%3===0 ? C.g30 : C.g20, 0.55);
    put(b, x, 1.4+h/2, z); grp.add(b);
    const a = box(1.2,1.2,1.2, C.g50, 1);
    put(a, x, 1.4+h+1.0, z); grp.add(a);
    grp.add(groundText(nm, x-2.4, z+3.4, 1.5,
      {color:'#8A8C8E', mono:true, opacity:0.9, y:1.5}));
  });

  const svc = glow(edged(4.4, 4.4, 4.4, C.falco, 0.92));
  put(svc, cx+11.4, 1.4+2.2, cz); grp.add(svc);
  return grp;
}

const SHAPES = { nodes:buildNodesVariant, machine:buildMachineVariant };

function BUILD_workloads(g,d,cx,cz){
  for(const topo of TOPOLOGIES){
    const make = SHAPES[topo.shape];
    /* shape:'none' is a real answer — with no driver there is no
       syscall-emitting west end to draw, so the district is left bare */
    const v = make ? make(topo, d, cx, cz) : null;
    if(v){ v.visible = false; g.add(v); }
    topoVariants[topo.id] = v;
  }

  /* The caption belongs to the orchestrator, not to the geometry: EKS and
     self-managed draw the same pads and say different things about them. One
     per declared orchestrator, plus the one for having no driver at all. */
  const cap = (make, key)=>{
    const build = () => {
      const t = groundText(make(), cx-16, d.z1+4, 2.0,
        {color:'#00A8BC', mono:true, opacity:0.95});
      t.visible = false; g.add(t); return t;
    };
    captionRefs[key] = {make, build, group:g, mesh:build()};
  };
  /* the caption says the node count out loud, so it is a factory, not a string:
     applyNodes() re-bakes it when a scenario declares a different cluster */
  for(const o of ORCH) cap(() => o.caption(CLUSTER_NODES), o.id);
  cap(() => 'NO DRIVER (nodriver) · プラグイン入力だけがイベントを運ぶ', 'bare');

  g.add(groundText('SYSCALLS', cx-1, d.z1+8, 5.0, {color:'#BBBDBF', opacity:0.4}));
  /* "kernel boundary →" used to be a floating label here, which is all the city
     ever said about the single most consequential line in the model. It is now a
     drawn membrane with two walls and a named zone — see §6c. */
}

/* ---------- §applyNodes: how many nodes this cluster has ----------
   Shows exactly CLUSTER_NODES pads, centred, and re-bakes the orchestrator
   caption that spells the count out loud. Same shape as applyCpus() below, and
   for the same reason: the count is declared elsewhere (a scenario's
   `env.nodes`) and the district has to be the cluster that was declared.

   Packing, and why the plates shrink. The layout engine sized this district for
   MAX_NODES before any scenario existed, so a six-node cluster does not get a
   bigger rectangle — it gets the same one. So the nodes are packed to a tighter
   pitch and their PLATES scale down by the same factor, which keeps them from
   overlapping while the pods, the agent and the node's own label stay at their
   real size. A sixth node on a narrower plate still reads as a sixth NODE, and
   reading the count is the entire point of this district. Room is the district's
   own depth plus the lane setback, which layout.js guarantees is empty on both
   sides.

   Below MAX_NODES nothing moves at all: pitch clamps at NODE_PITCH and the scale
   at 1, so the default three-node city is pixel-identical to before. */
let shownNodes = -1;
function applyNodes(){
  if(!nodeRefs.pads.length) return;
  const n = Math.max(1, Math.min(NODE_MAX, CLUSTER_NODES));
  if(n === shownNodes) return;
  shownNodes = n;

  const room  = nodeRefs.depth + LANE_PAD;
  const pitch = Math.min(NODE_PITCH, (room - NODE_MARGIN*2) / n);
  const sz    = Math.min(1, pitch / NODE_PITCH);
  for(let i=0;i<nodeRefs.pads.length;i++){
    const on = i < n;
    nodeRefs.pads[i].visible = on;
    if(!on) continue;
    nodeRefs.pads[i].position.z = (i - (n-1)/2) * pitch;
    nodeRefs.plates[i].scale.z = sz;
  }

  /* the captions carry the number, so they are wrong the moment it moves */
  for(const k in captionRefs){
    const c = captionRefs[k];
    const wasVisible = c.mesh.visible;
    c.group.remove(c.mesh);
    c.mesh.material.map?.dispose();
    c.mesh.material.dispose();
    c.mesh.geometry.dispose();
    c.mesh = c.build();
    c.mesh.visible = wasVisible;
  }
}

/* ---------- the one geometric switch ----------
   Everything the composed environment changes about the city, in one place.
   It takes the environment, not an id, and it never asks which environment
   this is — only what is true of it. Adding an axis value cannot reach this
   function unless it declares a consequence, which is the point. */
function applyEnvironment(env = currentEnv()){
  /* How many nodes the cluster has. The scenario hands its count over on
     S.nodes before anything calls in here (campaign.js §startScenario), and this
     is where it becomes the truth: setClusterNodes() moves the one binding every
     other reader derives from, so controls.js writing S.nodes back from
     CLUSTER_NODES two lines later now writes the value that is already true
     instead of flattening the cluster to the topology's default. Only for a
     cluster — on a single host "nodes" is 1 by definition, and on nodriver 0. */
  if(env.topology === 'cluster') setClusterNodes(S.nodes);
  applyNodes();

  /* the west end: cluster pads, one host slab, or nothing */
  for(const k in topoVariants)
    if(topoVariants[k]) topoVariants[k].visible = k === env.topology;

  /* its caption: the orchestrator's, unless there is no driver to caption */
  const capKey = env.kernelPath ? env.orch.id : 'bare';
  for(const k in captionRefs) captionRefs[k].mesh.visible = k === capKey;

  /* the audit route: an apiserver plus however that provider is collected.
     No orchestrator means no audit log to collect, and therefore no route. */
  for(const k in deployRefs.auditRoutes)
    deployRefs.auditRoutes[k].visible = !!env.audit && k === env.orch.id;

  /* the two k8s gantries are separate questions, so they get separate
     captions: runtime-derived fields need the socket, API-derived fields need
     the k8smeta plugin, and the deprecated spellings read <NA> without it */
  const L = stateRefs.labels;
  if(L.container){
    /* two fields is the floor: container.id and container.type come off the
       cgroup, so they survive with no socket at all */
    const rich = env.containerFields.length > 2;
    L.container.full.visible = rich;
    L.container.min.visible  = !rich;
  }
  if(L.k8sRuntime){
    L.k8sRuntime.on.visible  = env.podFields.length > 0;
    L.k8sRuntime.off.visible = env.podFields.length === 0;
  }
  if(L.k8sApi){
    L.k8sApi.on.visible  = env.k8sMeta;
    L.k8sApi.off.visible = !env.k8sMeta;
  }

  /* a driver the node OS cannot load is drawn as a slab you cannot stand on */
  for(const s of driverSlabs){
    const blocked = env.blockedDrivers.includes(s.userData.drvName);
    s.userData.blocked = blocked;
    s.visible = !blocked;
  }

  /* the kernel/user membrane (§6c). `nodriver` does not remove the syscall
     source — it removes the kernel→userspace ring buffer, i.e. the EAST wall
     only. Drawing both walls is what lets that be shown rather than asserted. */
  applyKernelBoundary(env);
  return env;
}

function BUILD_driver(g,d,cx,cz){
  // gate wall with tracepoint pillars
  const wall = edged(3.2, d.top, d.z1-d.z0-2, C.falco, 0.2, C.falco);
  put(wall, cx+3.4, d.top/2, cz); g.add(wall);
  for(let z=d.z0+3; z<=d.z1-3; z+=4.2){
    const h = 5 + (Math.abs(z)%7);
    const p = glow(box(1.5,h,1.5, C.falco, 0.85));
    put(p, cx-3.2, h/2, z); g.add(p);
  }
  /* one selectable slab per driver that actually injects something. nodriver
     has no slab on purpose — it is the absence of one. */
  driverSlabs.length = 0;
  DRIVERS.filter(dv => dv.slab).forEach((dv,i)=>{
    const slab = edged(7.6, 1.5, 8.2, C.g20, 0.75);
    put(slab, cx-1, 1.1 + i*4.4, d.z0-6.5 - i*0.2);
    slab.userData.drvName = dv.id;
    g.add(slab); driverSlabs.push(slab);
  });
  g.add(groundText('DRIVER', cx-5, d.z1+8, 5.0, {color:'#7FD9E6', opacity:0.5}));
}

function BUILD_ring(g,d,cx,cz){
  /* One lane per CPU, built up to CPU_MAX and then centred on however many the
     node actually has (applyCpus below). The pitch is fixed rather than
     span-divided precisely so that a 2-vCPU node draws two lanes at the same
     spacing as an 8-vCPU node draws eight, instead of two lanes stretched to
     the district's full depth — the lanes are CPUs, and a CPU is not wider on
     a smaller machine. */
  RING_LANES.length = 0;
  ringRefs.troughs.length = 0; ringRefs.walls.length = 0;
  ringRefs.caps.length = 0;   ringRefs.laneLabels.length = 0;
  ringRefs.pitch = (d.d*0.74) / (CPU_MAX - 1);
  for(let i=0;i<CPU_MAX;i++){
    const trough = box(d.x1-d.x0-1, 0.55, 2.5, C.g10, 0.95);
    put(trough, cx, 0.3, 0); g.add(trough);
    ringRefs.troughs.push(trough);
    // lane wall — its height tracks buf_size_preset
    const wl = box(d.x1-d.x0-1, 1.5, 0.22, C.g20, 0.34);
    put(wl, cx, 0.9, 0); g.add(wl);
    ringRefs.walls.push(wl);
    // cpu plate
    const cap = box(1.5, 1.4, 2.5, C.g30, 0.9);
    put(cap, d.x0+0.4, 0.85, 0); g.add(cap);
    ringRefs.caps.push(cap);
    /* cpu index plate at the head of the lane. One per possible CPU, so the
       labels stay truthful when the count changes — cpu0..cpu1 on a 2-vCPU
       node, not cpu0..cpu7 with six of them hidden behind nothing. */
    const lbl = groundText('cpu'+i, d.x0-5.6, 0, 1.9,
      {color:'#8A8C8E', mono:true, opacity:0.95});
    g.add(lbl); ringRefs.laneLabels.push(lbl);
  }
  // shared-memory volume — scales with buf_size_preset
  const shm = edged(d.x1-d.x0+1, 7.4, d.z1-d.z0-1, 0x9FB4BC, 0.14, C.g30);
  put(shm, cx, 3.9, cz); g.add(shm);
  ringRefs.shm = shm;
  // drop pit
  const pit = new THREE.Mesh(
    new THREE.PlaneGeometry(d.x1-d.x0-2, 5),
    new THREE.MeshBasicMaterial({color:C.redUi, transparent:true, opacity:0.15, depthWrite:false})
  );
  pit.rotation.x = -Math.PI/2; pit.position.set(cx, 0.06, d.z1+4.5); glow(pit); g.add(pit);
  /* ---- the buffers themselves, as envelopes OVER the CPU lanes ----
     This district drew CPUs and never drew buffers, so the one relation the
     falco.yaml comment exists to teach — buffers = ceil(nCPU ÷
     cpus_for_each_buffer) — was a number in a label and nothing on the ground.
     Now a trough is a CPU and a shell is a BUFFER, and how many troughs one
     shell covers IS cpus_for_each_buffer. Move that lever and the trough count
     does not change while the shell count does, which is exactly the causality.

     Built at CPU_MAX because the ceiling is one buffer per CPU (perBuf = 1);
     applyCpus() sizes and shows the ones that exist. Each shell is a group so
     its BODY can be scaled in y and z while the head plate on the read side —
     the thing you actually count — keeps its real size. */
  ringRefs.bufShells.length = 0; ringRefs.bufHeads.length = 0;
  const bw = d.x1-d.x0+2.4;
  for(let i=0;i<CPU_MAX;i++){
    const shell = new THREE.Group();
    /* Three parts, because this district is read from two angles and a
       translucent box only works from one. The GROUND BAND is what you see from
       above (the reading angle), the CAGE is what you see from the low 3/4 view,
       and the HEAD is the thing you actually count. */
    const pad = new THREE.Mesh(
      new THREE.PlaneGeometry(bw, 1),
      new THREE.MeshBasicMaterial({color:C.falco, transparent:true, opacity:0.13,
                                   depthWrite:false}));
    pad.rotation.x = -Math.PI/2; pad.position.y = 0.07;
    shell.add(pad);
    const padL = new THREE.LineSegments(
      new THREE.EdgesGeometry(new THREE.PlaneGeometry(bw, 1)), edgeMat(C.falco, 0.85));
    padL.rotation.x = -Math.PI/2; padL.position.y = 0.075;
    shell.add(padL);
    const cage = new THREE.LineSegments(
      new THREE.EdgesGeometry(new THREE.BoxGeometry(bw, 1, 1)), edgeMat(C.falco, 0.6));
    shell.add(cage);
    shell.userData.pad = pad; shell.userData.padL = padL; shell.userData.cage = cage;
    /* the read end. Userspace consumes from here, so it sits east of the lanes,
       in the gap the layout leaves between this district and the next. */
    const head = glow(box(1.9, 1.9, 1.9, C.falco, 0.9));
    put(head, d.x1+2.6 - cx, 1.5, 0);
    shell.add(head);
    shell.position.set(cx, 0, 0);
    shell.visible = false;
    g.add(shell);
    ringRefs.bufShells.push(shell);
    ringRefs.bufHeads.push(head);
  }

  g.add(groundText('n_drops', cx+3, d.z1+4.4, 2.4, {color:'#EA5255', mono:true, opacity:0.95}));
  g.add(groundText('BUFFERS', cx-4, d.z1+11, 5.0, {color:'#BBBDBF', opacity:0.4}));
  /* NOT "8 MiB / CPU", and no literal divisor either: 8 MiB is ONE buffer, and
     the count is ceil(nCPU / cpus_for_each_buffer) — both of which move. */
  g.add(groundText('溝 1本 = CPU 1個 · 囲い 1つ = リングバッファ 1本 · timestamp-ordered read',
    d.x0, d.z0-6, 1.85, {color:'#A3A5A7', mono:true, opacity:0.9}));
  /* the count this node actually has, spelled out where the lanes are. Rebuilt
     rather than repositioned, because the text itself changes. */
  ringRefs.cpuCaption = null;
  ringRefs.captionAt = [cx-6, d.z0-9.4];
  ringRefs.bufCaption = null;
  ringRefs.bufCaptionAt = [d.x0, d.z0-12.6];
  ringRefs.group = g;
  applyCpus();
}

/* ---------- how many CPUs this node has, and how many buffers that makes ----------
   Shows exactly nodeCpus() lanes, centred, and rewrites RING_LANES in place so
   sim.js keeps drawing particles into lanes that exist. Called on every tuning
   change and whenever the environment moves, so the district can never be
   showing a different machine from the one the HUD is describing.

   It also derives the BUFFERS from the lanes, which is why it reads S.tune
   directly. That is deliberate rather than a parameter: controls.js
   §applyTuneVisuals calls this first on every tuning change, and the alternative
   — a second entry point taking cpus_for_each_buffer — would let the lane count
   and the buffer count be applied from two places and disagree. There is one
   formula (districts.data.js §bufferCount) and one place that draws it.

   Three inputs, so three memoised values: the lane count, the grouping, and the
   preset (which sets how tall a buffer is). The guard matters — this runs on
   every drag of the buf_size_preset slider. */
let lastCpus = -1, lastPerBuf = -1, lastPreset = -1;
function applyCpus(){
  const n = nodeCpus();
  const perBuf = S.tune?.cpusPerBuf ?? 2;
  const preset = S.tune?.bufPreset ?? 4;
  if(n === lastCpus && perBuf === lastPerBuf && preset === lastPreset) return;
  const cpusMoved = n !== lastCpus;
  lastCpus = n; lastPerBuf = perBuf; lastPreset = preset;
  const pitch = ringRefs.pitch || 0;
  applyBuffers(n, perBuf, preset, pitch);
  if(!cpusMoved) return;            // the lanes themselves have not moved
  RING_LANES.length = 0;
  for(let i=0;i<ringRefs.troughs.length;i++){
    const on = i < n;
    const z = (i - (n-1)/2) * pitch;
    ringRefs.troughs[i].visible = on;
    ringRefs.walls[i].visible   = on;
    ringRefs.caps[i].visible    = on;
    ringRefs.laneLabels[i].visible = on;
    if(!on) continue;
    RING_LANES.push(z);
    ringRefs.troughs[i].position.z = z;
    ringRefs.walls[i].position.z   = z + 1.42;
    ringRefs.caps[i].position.z    = z;
    ringRefs.laneLabels[i].position.z = z;
  }
  /* say the count out loud: this is the number the scenario's diagnosis turns
     on, and "2 vCPU" is not something you can read off eight troughs */
  const g = ringRefs.group;
  if(g && ringRefs.captionAt){
    if(ringRefs.cpuCaption){
      g.remove(ringRefs.cpuCaption);
      ringRefs.cpuCaption.material.map?.dispose();
      ringRefs.cpuCaption.material.dispose();
      ringRefs.cpuCaption.geometry.dispose();
    }
    const t = groundText(`this node: ${n} vCPU`, ringRefs.captionAt[0], ringRefs.captionAt[1],
      2.2, {color:'#00A8BC', mono:true, opacity:0.95});
    g.add(t); ringRefs.cpuCaption = t;
  }
}

/* ---------- the buffers, derived from the lanes ----------
   One shell per buffer, each covering the CPUs that share it. Everything here is
   a consequence of the one formula:

     buffers          ceil(nCPU / cpus_for_each_buffer)   (0 = one for all CPUs)
     lanes per buffer which troughs a shell covers, so the grouping is a SHAPE
     height           buf_size_preset, tracking the lane walls controls.js scales,
                      because 8 MiB is the size of ONE buffer and not of the
                      district

   The caption says the arithmetic out loud, including the double mapping: the
   kernel maps each buffer twice, so an 8 MiB buffer costs 16 MiB of virtual
   memory. Rebuilt rather than repositioned — the text itself changes. */
function applyBuffers(cpus, perBuf, preset, pitch){
  const shells = ringRefs.bufShells;
  if(!shells.length) return;
  const bufs = bufferCount(perBuf, cpus);
  /* how many lanes each buffer covers. perBuf 0 means all of them. */
  const span = perBuf === 0 ? cpus : Math.max(1, perBuf);
  /* same scale the lane walls use (controls.js §applyTuneVisuals), so a shell
     never floats above or sinks below the walls it is supposed to contain */
  const s = 0.45 + (preset - 1) * 0.30;
  const h = 1.7 + 2.4 * s;

  for(let b=0;b<shells.length;b++){
    const on = b < bufs;
    shells[b].visible = on;
    if(!on) continue;
    const first = b * span;
    const last  = Math.min(cpus, first + span) - 1;
    const z0 = (first - (cpus-1)/2) * pitch;
    const z1 = (last  - (cpus-1)/2) * pitch;
    const dep = (z1 - z0) + 3.4;
    const u = shells[b].userData;
    u.pad.scale.set(1, dep, 1);            // a ground plane's local y IS world z
    u.padL.scale.set(1, dep, 1);
    u.cage.scale.set(1, h, dep);
    u.cage.position.y = h/2;
    shells[b].position.z = (z0 + z1) / 2;
    ringRefs.bufHeads[b].position.y = h * 0.5;
  }

  const g = ringRefs.group;
  if(!g || !ringRefs.bufCaptionAt) return;
  if(ringRefs.bufCaption){
    g.remove(ringRefs.bufCaption);
    ringRefs.bufCaption.material.map?.dispose();
    ringRefs.bufCaption.material.dispose();
    ringRefs.bufCaption.geometry.dispose();
  }
  const mib = PRESET_MIB(preset);
  const div = perBuf === 0 ? '0 (= 全 CPU で1本)' : String(perBuf);
  const t = groundText(
    `cpus_for_each_buffer ${div} → ceil(${cpus} ÷ ${perBuf === 0 ? cpus : perBuf}) = ${bufs} buffer${bufs===1?'':'s'}`
    + ` · 1本 ${mib} MiB（二重マップで仮想 ${mib*2} MiB）`,
    ringRefs.bufCaptionAt[0], ringRefs.bufCaptionAt[1], 1.85,
    {color:'#00A8BC', mono:true, opacity:0.95});
  g.add(t); ringRefs.bufCaption = t;
}

function BUILD_state(g,d,cx,cz){
  // thread table = dense tower grid
  for(let r=0;r<5;r++) for(let c=0;c<7;c++){
    const x = d.x0+2.6 + c*2.9;
    const z = d.z0+3.4 + r*3.1;
    const h = 3 + ((r*7+c*13)%11)*1.1;
    const t = box(1.7,h,1.7, 0x7FC7DA, 0.62);
    put(t, x, h/2, z); g.add(t);
  }
  // fd table block
  const fd = edged(7, 5, 9, 0x9AD9E8, 0.42);
  put(fd, d.x1-4.2, 2.5, d.z0+6); g.add(fd);
  /* ---- enrichment gantries: three, because there are three sources ----
     One reads the container runtime socket for container.*, one reads the
     same socket for the pod fields, and one reads the API server through the
     k8smeta plugin. Splitting the second and third is the whole point: they
     look like one "Kubernetes metadata" feature and they fail separately.
     Each carries two captions and applyEnvironment picks one. */
  const GANTRIES = [
    { key:'container', z:d.z1-4.5,  col:C.falco, h:13,
      on:'container.* ← socket (約28)',
      off:'container.id / .type のみ ← cgroup' },
    { key:'k8sRuntime', z:d.z1-10.5, col:0x00A8BC, h:11,
      on:'k8s.ns.name · k8s.pod.* ← socket',
      off:'k8s.pod.* なし (socket 不可)' },
    { key:'k8sApi', z:d.z1-16.5, col:C.purple, h:9,
      on:'k8smeta.deployment.name ← apiserver',
      off:'k8s.deployment.name = <NA>' }
  ];
  GANTRIES.forEach(gd=>{
    const gantry = new THREE.Group();
    const span = d.x1-d.x0-3;
    const beam = box(span, 0.8, 1.0, gd.col, 0.8);
    put(beam, cx, gd.h, gd.z); gantry.add(beam);
    [-1,1].forEach(s=>{
      const leg = box(0.8, gd.h, 0.8, gd.col, 0.42);
      put(leg, cx + s*span/2, gd.h/2, gd.z); gantry.add(leg);
    });
    g.add(gantry);
    stateRefs.gantries[gd.key] = gantry;

    const mk = txt => {
      const t = groundText(txt, cx, gd.z+2.2, 1.3,
        {color:'#8A8C8E', mono:true, opacity:0.92, y:0.14});
      t.visible = false; g.add(t); return t;
    };
    const pair = { on:mk(gd.on), off:mk(gd.off) };
    /* the container gantry's two states are "everything" and "the two the
       kernel can answer", so name them for what they are */
    stateRefs.labels[gd.key] = gd.key === 'container'
      ? { full:pair.on, min:pair.off } : pair;
  });
  // enclosing volume
  const vol = edged(d.x1-d.x0+1, d.top, d.z1-d.z0+1, 0x9AD9E8, 0.09, C.g30);
  put(vol, cx, d.top/2, cz); g.add(vol);
  g.add(groundText('ENRICH', cx-2, d.z1+8, 5.0, {color:'#7FD9E6', opacity:0.5}));
  g.add(groundText('thread table · fd table · container · k8s', d.x0, d.z0-6, 2.3,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
}

/* ---------- 05, divided by event source ----------
   A rule declares exactly one `source` (falco.org, Rules → basic elements;
   default `syscall`), and Falco does not correlate across sources
   (INVARIANTS 3.9). The city was drawing the opposite: the plugin lane was
   labelled "bypass" and its particles converged onto the same z the syscall
   stream used, so the picture said "everything merges here", and the whole point
   of the `a-different-source` scenario — that this is a PARTITION and not a
   volume problem — had nowhere to be read.

   So the ruleset is two rulesets with a wall between them. The split is declared
   once, in layout.js §RULE_SPLIT, because the particle path (ST.joinZ) has to
   land on the plugin side of it and the two must not be able to drift.

     north band   source: k8s_audit / aws_cloudtrail / gcpaudit / okta.
                  A different FIELD SPACE (ct.* / ka.*), so a smaller, separate
                  block of rules, fed by the lane from 07
     divider      solid, full width, with crossed marks on the ground. Nothing in
                  this city crosses it — there is no arrow through it to draw
     south band   source: syscall (the default). The main grid, fed by 04

   Priority towers move south of the divider only because they have to be
   somewhere; priority is orthogonal to source (it filters which rules LOAD, in
   both partitions), so they carry no partition meaning and their caption says
   so.                                                                        */
function BUILD_rules(g,d,cx,cz){
  const split = ST.ruleSplit;                     // -10 at the declared depth
  RULE_BLOCKS.length = 0;
  ruleRefs.syscall.length = 0; ruleRefs.plugin.length = 0;

  /* ---- north: the plugin-source ruleset ---- */
  for(let r=0;r<2;r++) for(let c=0;c<5;c++){
    const x = d.x0+3.8 + c*3.0;
    const z = d.z0+2.6 + r*3.4;
    const h = 2.0 + ((r*7+c*5)%5)*0.7;
    const b = glow(box(1.9,h,1.9, 0xF3C99A, 0.5));
    put(b, x, h/2, z); g.add(b);
    RULE_BLOCKS.push(b); ruleRefs.plugin.push(b);
  }
  g.add(groundText('source: k8s_audit / aws_cloudtrail / gcpaudit / okta',
    d.x0+2.2, split-2.0, 1.45, {color:'#B07A3A', mono:true, opacity:0.95}));
  g.add(groundText('ct.* · ka.* — 別のフィールド空間',
    d.x0+2.2, d.z0+0.6, 1.45, {color:'#B07A3A', mono:true, opacity:0.95}));

  /* ---- the divider: the thing that has no door ----
     Three parts, because the district is read both from above and from the low
     3/4 view, and a translucent wall is invisible from directly overhead:
     a solid PLINTH on the ground, the WALL above it, and crossed marks. */
  const dh = d.top - 4, dwid = d.x1-d.x0-1;
  const plinth = box(dwid, 0.55, 2.6, C.g60, 0.62);
  put(plinth, cx, 0.30, split); g.add(plinth);
  const wall = box(dwid, dh, 0.7, C.g60, 0.22);
  put(wall, cx, 0.55+dh/2, split); g.add(wall);
  const wallL = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.BoxGeometry(dwid, dh, 0.7)),
    edgeMat(C.g60, 0.85));
  put(wallL, cx, 0.55+dh/2, split); g.add(wallL);
  ruleRefs.divider = wall;
  /* crossed marks along the top of the plinth. An X is the only mark that reads
     as "not this way" without a colour, and colour is spoken for here — red is a
     drop and orange is a plugin input. */
  {
    const pts = [], t = 1.05;
    for(let k=0;k<7;k++){
      const x = d.x0+3.5 + k*((d.x1-d.x0-7)/6);
      pts.push(x-t,0,split-t, x+t,0,split+t,  x-t,0,split+t, x+t,0,split-t);
    }
    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.Float32BufferAttribute(pts, 3));
    const marks = new THREE.LineSegments(geo,
      new THREE.LineBasicMaterial({color:C.g10, transparent:true, opacity:0.95}));
    marks.position.y = 0.60; g.add(marks);
  }
  g.add(groundText('相関しない — 1つのルールは1つのソースにしか属さない',
    d.x0+2.2, split+2.4, 1.6, {color:'#3E4042', mono:true, opacity:0.95}));

  /* ---- south: the syscall ruleset (the default source) ---- */
  for(let r=0;r<6;r++) for(let c=0;c<6;c++){
    const x = d.x0+3.2 + c*2.7;
    const z = split+5.4 + r*2.9;
    const h = 2.2 + ((r*5+c*11)%6)*0.8;
    const b = glow(box(1.9,h,1.9, 0xC9AEDA, 0.5));
    put(b, x, h/2, z); g.add(b);
    RULE_BLOCKS.push(b); ruleRefs.syscall.push(b);
  }
  g.add(groundText('source: syscall（既定）',
    d.x0+2.2, split+4.0, 1.6, {color:'#8E5FA0', mono:true, opacity:0.95}));
  g.add(groundText('evt.* · proc.* · fd.* · container.* · k8s.pod.*',
    d.x0+2.2, d.z1-2.4, 1.45, {color:'#8E5FA0', mono:true, opacity:0.95}));

  /* priority towers — a property of a rule, in both partitions */
  const prios = [
    ['EMERGENCY',C.purple,15],['CRITICAL',C.purple,13],['ERROR',C.redUi,11],
    ['WARNING',C.orange,9],['NOTICE',C.falco,7],['INFO',C.g30,5]
  ];
  prios.forEach((p,i)=>{
    const h = p[2]*1.5;
    const t = glow(edged(2.7, h, 2.7, p[1], 0.72));
    put(t, d.x1-3.2, h/2, split+5.0 + i*2.9); g.add(t);
  });

  // engine shell — one engine, whatever the source
  const shell = edged(d.x1-d.x0+1, d.top, d.z1-d.z0+1, 0xD9C0E4, 0.1, C.g30);
  put(shell, cx, d.top/2, cz); g.add(shell);
  // condition arch, spanning both partitions: it is the same engine
  const arch = box(1.2, d.top-4, d.z1-d.z0-2, C.purple, 0.13);
  put(arch, d.x0+1.2, (d.top-4)/2, cz); g.add(arch);
  g.add(groundText('MATCH', cx-1, d.z1+8, 5.0, {color:'#CA87DA', opacity:0.45}));
  g.add(groundText('同じエンジン · ソースごとに分割された ruleset · macros · lists · exceptions',
    d.x0, d.z0-6, 2.0, {color:'#A3A5A7', mono:true, opacity:0.9}));
}

function BUILD_outputs(g,d,cx,cz){
  // three output pipes
  const pipes = [['stdout / file / syslog', 8],['gRPC output API', 0],['falcosidekick', -8]];
  OUT_PIPES.length = 0; outRefs.pipes.length = 0;
  pipes.forEach(([lbl,z],i)=>{
    const p = box(d.x1-d.x0-2, 2.2, 3.2, i===2?C.lumin:C.g20, i===2?0.9:0.7);
    if(i===2) glow(p);
    put(p, cx, 2.4, z); g.add(p);
    OUT_PIPES.push(z);
    outRefs.pipes.push(p);
  });
  // sidekick fan-out towers
  for(let i=0;i<6;i++){
    const h = 3 + (i%3)*2.4;
    const t = glow(box(1.5,h,1.5, C.lumin, 0.9));
    put(t, d.x1-1.5, h/2, d.z0+2.5 + i*2.4); g.add(t);
  }
  // talon block
  const talon = glow(edged(5.2, 6, 5.2, C.lumin, 0.55));
  put(talon, d.x0+3.6, 3, d.z1-4); g.add(talon);
  const vol = edged(d.x1-d.x0+1, d.top, d.z1-d.z0+1, C.lumin, 0.1, C.g30);
  put(vol, cx, d.top/2, cz); g.add(vol);
  g.add(groundText('ALERT', cx, d.z1+8, 5.0, {color:'#9FD66A', opacity:0.5}));
  g.add(groundText('slack · loki · elastic · alertmanager · s3 · kafka', d.x0-2, d.z0-6, 2.2,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
}

/* ---------- one audit route per orchestrator ----------
   The k8saudit lane is where the orchestrator axis is actually visible, and
   the shapes genuinely differ:

     self-managed  the apiserver pushes over a webhook into the Falco that is
                   already watching syscalls. No second installation.
     managed       the apiserver's flags are not yours, so no webhook can be
                   pointed anywhere. A provider plugin PULLS from the log sink,
                   and that means a separate installation that collects.

   For EKS the official Helm values pin that installation exactly:
   controller.kind: deployment / replicas: 1 / driver.enabled: false /
   collectors.enabled: false — one pod, no driver, no collectors, because two
   pods would pull the same CloudWatch stream twice and duplicate every alert.
   GKE says the opposite (Pub/Sub exactly-once lets you run several) and AKS
   says nothing, so only EKS draws the disabled slots and the "replicas: 1"
   plate. A model that generalised this would be teaching a false constraint. */
function buildAuditRoute(orch, d){
  const a = orch.audit;
  if(!a) return null;
  const grp = new THREE.Group();
  const x = ax => d.x0 + ax, z = az => d.z0 + az;

  /* the apiserver, and the sink or webhook the audit events leave through */
  const srv = edged(4.2, 9, 4.2, C.falco, 0.6);
  put(srv, x(16), 0.7+4.5, z(6)); grp.add(srv);
  grp.add(groundText('kube-apiserver', x(11.4), z(1.4), 1.4,
    {color:'#00A8BC', mono:true, opacity:0.95, y:0.75}));

  const sink = edged(3.6, a.pull ? 6 : 4, 3.6, 0xF3C99A, 0.7);
  put(sink, x(16), 0.7+(a.pull?3:2), z(15)); grp.add(sink);
  grp.add(groundText(a.transport, x(15), z(20), 1.35,
    {color:'#A3A5A7', mono:true, opacity:0.92, y:0.75}));
  /* pull points east into the collector, push points west into the DaemonSet */
  for(let i=0;i<3;i++)
    grp.add(chevron(x(a.pull ? 19.5+i*2.4 : 12.5-i*2.4), z(15), 1.5,
      0xF3C99A, 0.45, a.pull ? 0 : Math.PI));

  if(a.controller === 'deployment'){
    /* a Deployment, drawn as a deck carrying exactly as many pods as the
       sources permit — one for EKS, several for GKE */
    const n = a.replicas ?? 1;
    const dw = 13, dd = 13, dx = x(27), dz = z(11);
    const deck = box(dw, 1.0, dd, C.g10, 0.95);
    put(deck, dx, 0.36+0.5, dz); grp.add(deck);
    const rim = new THREE.LineSegments(
      new THREE.EdgesGeometry(new THREE.BoxGeometry(dw, 1.0, dd)), edgeMat(C.purple, 0.7));
    put(rim, dx, 0.36+0.5, dz); grp.add(rim);

    for(let i=0;i<n;i++){
      const pz = dz + (i - (n-1)/2) * 3.6;
      const pod = edged(4.4, 5.2, 3.0, C.falco, 0.9);
      put(pod, dx-1.6, 1.36+2.6, pz); grp.add(pod);
    }
    grp.add(groundText(a.lbl, x(20), z(21.8), 1.35,
      {color:'#B15FC4', mono:true, opacity:0.95, y:0.75}));

    /* the two things this installation explicitly does NOT have, drawn as
       empty slots so the absence is a building and not a missing label */
    const off = [];
    if(a.driver === false)     off.push('driver.enabled: false');
    if(a.collectors === false) off.push('collectors.enabled: false');
    off.forEach((lbl,i)=>{
      const slot = box(3.8, 3.4, 2.6, C.redUi, 0.06);
      put(slot, dx+3.4, 1.36+1.7, dz - 3.2 + i*4.6); grp.add(slot);
      const cage = new THREE.LineSegments(
        new THREE.EdgesGeometry(new THREE.BoxGeometry(3.8, 3.4, 2.6)),
        edgeMat(C.redUi, 0.55));
      put(cage, dx+3.4, 1.36+1.7, dz - 3.2 + i*4.6); grp.add(cage);
      /* the caption goes north of the deck rather than beside the slot: at
         1280×720 a label on the east edge runs out of the district */
      grp.add(groundText(lbl, dx+1, z(3.4 + i*2.2), 1.0,
        {color:'#B23A3D', mono:true, opacity:0.95, y:1.5}));
    });
    if(a.single)
      grp.add(groundText('単一インスタンス必須 — 2つ動かすとアラートが重複する',
        x(19), z(24.4), 1.4, {color:'#B23A3D', mono:true, opacity:0.95, y:0.75}));
  } else {
    /* no separate installation at all: the webhook lands on the Falco that is
       already there, so the route is a label and an arrow pointing west */
    grp.add(groundText(a.lbl, x(19), z(9.5), 1.5,
      {color:'#00A8BC', mono:true, opacity:0.95, y:0.75}));
    grp.add(groundText('監査用の別インスタンスは要らない', x(19), z(13), 1.4,
      {color:'#A3A5A7', mono:true, opacity:0.9, y:0.75}));
  }
  return grp;
}

function BUILD_plugins(g,d,cx,cz){
  const plat = box(d.x1-d.x0-1, 0.7, d.z1-d.z0-1, C.g10, 0.85);
  put(plat, cx, 0.36, cz); g.add(plat);

  /* cloud / identity sources — available whatever the environment is */
  ['cloudtrail','okta','github','gcpaudit'].forEach((nm,i)=>{
    const h = 4 + (i%3)*2.2;
    const b = edged(3.4, h, 3.4, 0xF3C99A, 0.62);
    put(b, d.x0+3.5 + (i%2)*6.2, 0.7+h/2, d.z0+4 + Math.floor(i/2)*7.5);
    g.add(b);
    g.add(groundText(nm, d.x0+1.7 + (i%2)*6.2, d.z0+7.6 + Math.floor(i/2)*7.5, 1.35,
      {color:'#A3A5A7', mono:true, opacity:0.9, y:0.75}));
  });

  /* the k8saudit half, once per declared orchestrator. Adding a provider is a
     declaration in ORCH; this loop and applyEnvironment need nothing. */
  for(const orch of ORCH){
    const route = buildAuditRoute(orch, d);
    if(!route) continue;
    route.visible = false;
    g.add(route);
    deployRefs.auditRoutes[orch.id] = route;
  }

  g.add(groundText('PLUGINS', cx-1, d.z1+5.5, 4.2, {color:'#E0B183', opacity:0.5}));
  g.add(groundText('no driver · no ring buffer · ルールはソース間で相関しない',
    cx-8, d.z0-4.5, 2.2, {color:'#A3A5A7', mono:true, opacity:0.9}));
}

/* ---------- 09, as three crates with two of them shut ----------
   INVARIANTS §4.1: maturity and FILE are 1:1 in falcosecurity/rules, and the
   release package ships exactly one of the three. This district used to draw
   three blocks of decreasing height and opacity, which reads as "three tiers of
   quality" — true, but not the thing that matters. What matters is that
   **you already have one of them and you do not have the other two**, and a
   short block cannot say that.

   So: three crates on a platform. The shipped one has no lid, and you can see
   and count the 25 rules inside it. The other two are shut, with their filename
   printed on the lid and their count on the ground beside them. 25 open against
   68 sealed is "Falco の既定ルールは思ったより少ない" with no sentence attached.

   Which crates are open comes from districts.data.js §loadedRuleFiles(), so when
   the maturity lever lands (policies.js §LEVERS) opening a crate is one call to
   applyRuleFiles() and nothing here changes.

   CRATE_W / CRATE_D are sized so five columns of five rules fit inside with a
   readable gap, which is what set the district's 24×22 footprint. */
const CRATE_W = 5.6, CRATE_D = 8.4, CRATE_H = 3.2, CRATE_T = 0.45, CRATE_PITCH = 7.4;

/* Both states are BUILT for every crate and one of them is shown, so opening a
   crate is a visibility flip and never a rebuild. `count` rules go inside; the
   grid is 5 wide, which makes 25 read as five rows of five. */
function buildCrate(file, x, z, g){
  const grp = new THREE.Group();
  const iw = CRATE_W - CRATE_T*2, id = CRATE_D - CRATE_T*2;
  const open = new THREE.Group(), shut = new THREE.Group();

  const floor = box(CRATE_W, 0.4, CRATE_D, C.g10, 0.95);
  put(floor, x, 0.7+0.2, z); grp.add(floor);
  /* four walls, so a crate is a container and not a block */
  const sideY = 0.9 + CRATE_H/2;
  const sides = [];
  [[CRATE_W, CRATE_T, 0, (CRATE_D-CRATE_T)/2], [CRATE_W, CRATE_T, 0, -(CRATE_D-CRATE_T)/2],
   [CRATE_T, CRATE_D, (CRATE_W-CRATE_T)/2, 0], [CRATE_T, CRATE_D, -(CRATE_W-CRATE_T)/2, 0]]
    .forEach(([w,dd,ox,oz])=>{
      const s = glow(box(w, CRATE_H, dd, C.lumin, 0.92));
      put(s, x+ox, sideY, z+oz); grp.add(s); sides.push(s);
    });

  /* ---- open: the rules, countable ---- */
  const cols = 5, rows = Math.ceil(file.count / 5);
  const px = iw/cols, pz = id/Math.max(rows, 5);
  for(let i=0;i<file.count;i++){
    const c = i % cols, r = Math.floor(i / cols);
    const h = 1.4 + ((r*5+c*7)%4)*0.35;
    const b = glow(box(px*0.52, h, pz*0.5, 0xC9AEDA, 0.85));
    put(b, x + (c-(cols-1)/2)*px, 1.1+h/2, z + (r-(rows-1)/2)*pz);
    open.add(b);
  }
  /* the filename rides the crate's LIP, at the same height whether there is a lid
     or not, so the two states differ only by the lid. Inside the open crate it
     disappeared behind its own contents. */
  const lipY = 0.9 + CRATE_H + 0.10;
  open.add(groundText(file.file, x, z, 0.95,
    {color:'#3E4042', mono:true, opacity:0.95, y:lipY, rotZ:-Math.PI/2}));

  /* ---- shut: a lid, with the filename printed on it ---- */
  const lidY = 0.9 + CRATE_H + CRATE_T/2;
  const lid = box(CRATE_W, CRATE_T, CRATE_D, C.g30, 0.95);
  put(lid, x, lidY, z); shut.add(lid);
  const seal = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.BoxGeometry(CRATE_W, CRATE_T, CRATE_D)),
    edgeMat(C.g50, 0.85));
  put(seal, x, lidY, z); shut.add(seal);
  shut.add(groundText(file.file, x, z, 0.95,
    {color:'#626466', mono:true, opacity:0.95, y:lidY+CRATE_T/2+0.06, rotZ:-Math.PI/2}));

  grp.add(open); grp.add(shut);
  g.add(grp);
  crateRefs[file.id] = {grp, open, shut, sides};
  return grp;
}

function BUILD_falcoctl(g,d,cx,cz){
  const plat = box(d.x1-d.x0-1, 0.7, d.z1-d.z0-1, C.g10, 0.9);
  put(plat, cx, 0.36, cz); g.add(plat);

  /* the registry the artifacts come from — a bar across the north edge, above
     all three crates, because all three live in the same registry */
  const reg = edged(d.x1-d.x0-8, 3.4, 3.0, C.g40, 0.7);
  put(reg, cx, 0.7+1.7, d.z0+3.2); g.add(reg);
  g.add(groundText('OCI registry', d.x0+1.4, d.z0+0.9, 1.4,
    {color:'#8A8C8E', mono:true, opacity:0.95, y:0.75}));

  const crateZ = d.z0 + 12.6;
  RULE_FILES.forEach((f,i)=>{
    const x = d.x0 + 4.8 + i*CRATE_PITCH;
    buildCrate(f, x, crateZ, g);
    /* the count, beside its own crate, running ALONG the crate. Written across the
       district instead, the three of them were 15–19 units wide on a 7.4 pitch and
       overprinted into mush. The three numbers side by side ARE the argument, so
       they have to be legible as three. */
    g.add(groundText(`${f.lbl} · ${f.count}本`, x - CRATE_W/2 - 1.4, crateZ, 1.45,
      {color: f.shipped ? '#3E4042' : '#8A8C8E', mono:true, opacity:0.95, y:0.75,
       rotZ:-Math.PI/2}));
  });
  applyRuleFiles();

  /* artifacts leave for the rules engine — from the OPEN crate, because that is
     the only one feeding 05 by default */
  for(let i=0;i<3;i++)
    g.add(chevron(d.x0+4.8, d.z1+2 + i*3.2, 1.9, 0xC9AEDA, 0.4, -Math.PI/2));

  g.add(groundText('falcoctl', cx-5, d.z0-3.4, 3.2, {color:'#C9AEDA', opacity:0.6}));
  g.add(groundText('artifact install / follow → rules_files', d.x0, d.z0-6.6, 1.9,
    {color:'#A3A5A7', mono:true, opacity:0.9}));
  g.add(groundText('成熟度はフラグではなくファイル — 同梱されるのは falco_rules.yaml だけ',
    d.x0, d.z0-9.6, 1.75, {color:'#3E4042', mono:true, opacity:0.95}));
}

/* Open the crates the engine has actually loaded. Nothing passes an argument yet
   — the maturity lever is the policy layer's (BOARD D33) — so the default IS the
   claim: stable only, because that is the only file the release package ships.
   Kept as a function rather than baked in so that when the lever arrives,
   setRuleFiles() + applyRuleFiles() is the whole wiring. */
function applyRuleFiles(){
  const on = loadedRuleFiles();
  for(const f of RULE_FILES){
    const c = crateRefs[f.id];
    if(!c) continue;
    const loaded = on.includes(f.id);
    c.open.visible = loaded;
    c.shut.visible = !loaded;
    /* a shut crate is grey-20: what is inside it is not yours yet */
    for(const s of c.sides){
      s.material.color.setHex(loaded ? C.lumin : C.g20);
      s.material.opacity = loaded ? 0.92 : 0.9;
    }
  }
}

function BUILD_sysdig(g,d,cx,cz){
  const w=d.x1-d.x0, dp=d.z1-d.z0;
  // deck
  const deck = box(w, 1.5, dp, C.deepSee, 0.94);
  put(deck, cx, 0.75, cz); g.add(deck);
  const rimL = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.BoxGeometry(w,1.5,dp)),
    new THREE.LineBasicMaterial({color:C.lumin, transparent:true, opacity:0.75})
  );
  put(rimL, cx, 0.75, cz); g.add(rimL);
  // capability blocks
  const caps = [
    ['Threat Detection', -16, -9, C.lumin, 6],
    ['Runtime Insights', -4, -9, C.lumin, 8.5],
    ['Posture / CIEM',    8, -9, 0x4A8C93, 5],
    ['Activity Audit', -16,  4, 0x4A8C93, 4],
    ['Captures (.scap)', -4, 4, 0x4A8C93, 5.5],
    ['Response / Sage', 10,  4, C.lumin, 7]
  ];
  caps.forEach(([lbl,ox,oz,col,h])=>{
    const b = box(9, h, 8.5, col, col===C.lumin?0.92:0.6);
    if(col === C.lumin) glow(b);
    put(b, cx+ox, 1.5+h/2, cz+oz); g.add(b);
  });
  g.add(groundText('SYSDIG SECURE', cx-6, d.z1+5, 5.2,
    {color:'#01353E', opacity:0.9, y:1.6}));
  g.add(groundText('same libs · same falco engine', cx-8, d.z1+9.5, 2.3,
    {color:'#4A8C93', mono:true, opacity:0.95, y:1.6}));
  // support columns down to ground
  [[-w/2+5,-dp/2+5],[w/2-5,-dp/2+5],[-w/2+5,dp/2-5],[w/2-5,dp/2-5]].forEach(([ox,oz])=>{
    const col = box(0.6, d.y, 0.6, C.g20, 0.22);
    put(col, cx+ox, -d.y/2, cz+oz); g.add(col);
  });
  sysdigGroup = g;
}


/* ============================================================
   6b. Sysdig Shield — the boundary AND what is inside it
   ------------------------------------------------------------
   Host Shield used to be *only* a boundary drawn round 02〜06, and Cluster Shield
   *only* a deck with four unlabelled blocks. So the single question a viewer
   arrives with — what do I get if I put Sysdig in? — had no answer on the ground,
   and this was the model's largest hole (GAME-DESIGN §0).

   The feature lists come from districts.data.js §SHIELDS (docs.sysdig.com,
   Onboarding → Sysdig Shield). Seven features, and the drawing has to keep the
   hardest invariant in the model intact while showing them:

     INVARIANTS §5.2 — **Sysdig を足しても検知は1段も増えない.** `npm test` pins
     it (`sysdig` appears in no CHAIN step's `needs`), so if the picture implies
     otherwise the picture is the thing that is wrong.

   Hence two shapes, and the shape carries the claim:

     kind:'operate'  A HOLLOW frame with arrows into the districts that already
                     do the work. Runtime Threat Detection is 02〜06 (same libs,
                     same engine — §5.4) and Kubernetes Audit Threat Detection is
                     07. Nothing is added; the operating moves.
     kind:'new'      A SOLID building. Vulnerability scanning, posture, remote
                     response, admission. This is the whole of what arrives.

   Five solid and two hollow. Nothing solid lands anywhere near the pipeline, so
   "detection did not move" is legible before any caption is read — and adding a
   feature to the data cannot break it, because the shape follows `kind`.
   ============================================================ */

/* One module. `operate` gets a frame and a tether; `new` gets a building. */
function shieldModule(f, x, z, opts){
  const grp = new THREE.Group();
  const w = opts.w ?? 20, dp = opts.d ?? 11;
  const operate = f.kind === 'operate';
  /* Host Shield sits on the near-white ground, Cluster Shield on its own Deep See
     deck, so the text has to invert or it vanishes into the surface it is on.
     Both pairs are brand tokens: Deep See / #4A8C93 on light, Lumin / grey-10 on
     dark. */
  const dark = !!opts.onDark;
  const INK  = dark ? '#BDF78B' : '#01353E';
  const INK2 = dark ? '#EAEBED' : '#4A8C93';
  /* Everything below is built at ground-relative y and the whole group is then
     lifted. Without this the Cluster Shield's modules were built at y≈0 and its
     deck top is at 1.2, so every label, wash and chevron was drawn UNDERNEATH
     the deck it belongs to and simply never appeared. */
  grp.position.y = opts.baseY ?? 0;

  if(operate){
    /* hollow: edges only, plus a floor wash so it still reads as a footprint.
       No box body at all — a translucent body is what "faint building" looks
       like, and a faint building is still a building. */
    const wash = new THREE.Mesh(
      new THREE.PlaneGeometry(w, dp),
      new THREE.MeshBasicMaterial({color:C.deepSee, transparent:true,
                                   opacity:0.055, depthWrite:false}));
    wash.rotation.x = -Math.PI/2; wash.position.set(x, 0.04, z); grp.add(wash);
    const frame = new THREE.LineSegments(
      new THREE.EdgesGeometry(new THREE.BoxGeometry(w, 5.5, dp)), edgeMat(C.deepSee, 0.7));
    put(frame, x, 2.75, z); grp.add(frame);
    /* the tether: arrows leaving the frame toward the work it takes over.
         'flow'  the work runs EAST–WEST through this frame — arrows both ways
                 along the pipeline, which is what "02〜06 のすべて" looks like
                 from a module standing in one gap between two of them
         ±1      the work is one direction away in z                          */
    const dir = opts.toward ?? -1;
    if(dir === 'flow'){
      for(const s of [-1, 1]) for(let i=0;i<3;i++)
        grp.add(chevron(x + s*(w/2 + 1.8 + i*3.0), z, 2.3, C.deepSee,
                        0.62 - i*0.16, s < 0 ? Math.PI : 0));
    }else{
      for(let i=0;i<3;i++)
        grp.add(chevron(x, z + dir*(dp/2 + 1.7 + i*2.1), 2.0, C.deepSee,
                        0.6 - i*0.15, dir < 0 ? -Math.PI/2 : Math.PI/2));
    }
    /* the tether's caption goes INSIDE the frame — there is nothing but ground in
       there, and the alternative is putting text on top of the districts the
       arrows are pointing at */
    if(opts.tether)
      grp.add(groundText(opts.tether,
        dir === 'flow' ? x : x - w/2 + 1.0,
        dir === 'flow' ? z + dp/2 - 2.0 : z - dp*0.5 + 1.8,
        Math.min(1.4, Math.max(w, 6)/9),
        {color:INK, mono:true, opacity:0.95, y:0.09,
         rotZ: dir === 'flow' ? -Math.PI/2 : 0}));
  }else{
    const b = glow(box(w*0.62, opts.h ?? 6, dp*0.62, C.lumin, 0.9));
    put(b, x, 0.9 + (opts.h ?? 6)/2, z); grp.add(b);
    const pad = box(w*0.78, 0.9, dp*0.78, C.deepSee, 0.94);
    put(pad, x, 0.45, z); grp.add(pad);
    const rim = new THREE.LineSegments(
      new THREE.EdgesGeometry(new THREE.BoxGeometry(w*0.78, 0.9, dp*0.78)),
      edgeMat(C.lumin, 0.8));
    put(rim, x, 0.45, z); grp.add(rim);
  }

  /* Two label modes, because the two Shields have very different footprints.
     `full` gets the source's own English name on one line and the Japanese plus
     the config key on the next. `short` is for the Cluster Shield, whose four
     modules sit on a 13-deep deck at 8.5 pitch: an English name there is three
     times the width of its own module and the four of them would overprint each
     other. The full breakdown for those four is in the district's own text. */
  if(opts.label === 'gap'){
    /* Used where the module stands in a FLOW_GAP: 8 units of x against 48 of z,
       so the only direction a 24-character name fits is along the gap. One name
       each side of the module, both inside the gap. */
    grp.add(groundText(f.en, x - (w/2 + 1.5), z, 1.3,
      {color:INK, mono:true, opacity:0.95, y:0.09, rotZ:-Math.PI/2}));
    grp.add(groundText(f.jp, x + (w/2 + 1.5), z, 1.3,
      {color:INK2, mono:true, opacity:0.95, y:0.09, rotZ:-Math.PI/2}));
  }else if(opts.label === 'short'){
    /* Along the module, not across it. Across, the four Japanese names are 9–12
       characters on an 8.5 pitch and they overprinted into one line of mush; the
       deck is 13 deep, so along it there is room for all four. */
    grp.add(groundText(f.jp, x - (w/2 + 1.4), z, 1.3,
      {color:INK, mono:true, opacity:0.95, y:0.09, rotZ:-Math.PI/2}));
  }else{
    grp.add(groundText(f.en, x - w/2 + 0.6, z + dp/2 + 2.2, 1.65,
      {color:INK, mono:true, opacity:0.95, y:0.09}));
    grp.add(groundText(f.key ? `${f.jp} · ${f.key}` : f.jp,
      x - w/2 + 0.6, z + dp/2 + 4.7, 1.4,
      {color:INK2, mono:true, opacity:0.95, y:0.09}));
  }
  return grp;
}

(function shieldOverlay(){
  const band = Math.max(...DISTRICTS.filter(isFlow).map(k=>k.d))/2 + 1;

  /* ---------------- HOST SHIELD ---------------- */
  const hs = new THREE.Group();
  const first = byId('driver'), last = byId('outputs');
  const x0=first.x0-3, x1=last.x1+3, z0=-band, z1=band, h=30;
  const shell = new THREE.Mesh(
    new THREE.BoxGeometry(x1-x0, h, z1-z0),
    new THREE.MeshBasicMaterial({color:C.deepSee, transparent:true, opacity:0.035, depthWrite:false}));
  shell.position.set((x0+x1)/2, h/2, (z0+z1)/2); hs.add(shell);
  const shellL = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.BoxGeometry(x1-x0, h, z1-z0)), edgeMat(C.deepSee, 0.34));
  shellL.position.copy(shell.position); hs.add(shellL);

  const host = SHIELDS.find(s => s.id === 'host');
  hs.add(groundText(`${host.lbl} — ${host.scope} · ${host.jpScope}`, x0+2, z1+2.4, 2.4,
    {color:'#01353E', mono:true, opacity:0.85}));

  /* WHERE the four features go, and why it is the FLOW GAPS.
     There is no south strip to use. `band` is half the deepest FLOW district's
     depth, and the deepest one is 02 at 46 — not 01, whose declared depth follows
     MAX_NODES, which is the CLUSTER's 3. So band is 23 and the districts are ±23:
     the shell has no interior margin at all, and a first attempt at a row south of
     the pipeline put the whole Shield outside both the shell AND cityBox (the home
     shot fits the DISTRICTS, so anything past their extent is off-frame).

     What is genuinely empty inside the shell is the FLOW_GAP between each pair of
     districts — 8 units of x by the full depth, four of them, derived from the
     layout so they cannot drift. So each feature stands in one gap, and the names
     run ALONG the gap (label:'gap'). Runtime Threat Detection points both ways down
     the flow, which is what "all of 02〜06" looks like from a module standing
     between two of them.

     One gap is NOT used: the one between 02 and 03. That is where the kernel
     membrane's east wall stands (§6c), and a Deep See frame with a caption on top
     of a grey membrane with a caption is two readings fighting for one 8-unit
     strip — measured, and it was the one place in this change where the city got
     harder to read. So the fourth feature takes the shallow strip south of 06
     instead (06 is only ±17 deep against the shell's ±23), which is empty ground
     inside the boundary at every node count. */
  const flow = DISTRICTS.filter(isFlow);
  const gapAfter = id => {
    const i = flow.findIndex(d => d.id === id);
    return (flow[i].x1 + flow[i+1].x0) / 2;
  };
  const out = byId('outputs');
  const MOD_Z = 15, MOD_D = 13;
  /* doc order, in the room that is actually free. Runtime Threat Detection sits
     mid-run so its two-way tether points at 02〜04 one way and 05〜06 the other. */
  const spots = [
    { x:gapAfter('ring'),  z:MOD_Z, w:4.6, d:MOD_D },
    { x:gapAfter('state'), z:MOD_Z, w:4.6, d:MOD_D },
    { x:gapAfter('rules'), z:MOD_Z, w:4.6, d:MOD_D },
    { x:out.cx,            z:20.5,  w:12,  d:4.6  }
  ];
  host.features.forEach((f,i)=>{
    const s = spots[i];
    if(!s) return;
    hs.add(shieldModule(f, s.x, s.z, {
      w:s.w, d:s.d, h:[0, 7, 6, 8][i] || 6, label:'gap',
      toward:'flow', tether:'02〜06 をそのまま運用する — 検知は増えない'
    }));
  });
  /* The legend for the two shapes. Once, because the grammar is the same for both
     Shields, and a legend repeated is a legend nobody trusts. It rides the shell's
     own west margin, along z, which is the last free strip inside the boundary. */
  hs.add(groundText('□ 中空＋矢印 = 既存地区の運用を引き取る — 検知は1段も増えない',
    x0+1.0, 0, 1.5, {color:'#01353E', mono:true, opacity:0.95, y:0.09, rotZ:-Math.PI/2}));
  hs.add(groundText('■ 実体 = この都市に地区が無かった仕事（脆弱性・姿勢・応答）',
    x0+2.6, 0, 1.5, {color:'#4A8C93', mono:true, opacity:0.95, y:0.09, rotZ:-Math.PI/2}));
  hs.add(groundText(host.deploy, x0+4.2, 0, 1.4,
    {color:'#4A8C93', mono:true, opacity:0.9, y:0.09, rotZ:-Math.PI/2}));
  world.add(hs);
  deployRefs.hostShield = hs;

  /* ---------------- CLUSTER SHIELD ----------------
     A cluster-scoped Deployment. No source states a replica count, so it draws
     one deck and says "cluster scoped" rather than "1". It sits just north of the
     plugin district because that is the lane it works in — and now that is doing
     double duty: `audit` is the one Cluster Shield feature that takes over
     something the city already has, and what it takes over is 07, which is
     directly south of here. So the tether has somewhere true to point.

     The deck widens from 15 to the plugin district's own width so four labelled
     modules fit in a row along X. It must NOT get deeper: it already sits at the
     northern edge of what the home shot frames. */
  const cs = new THREE.Group();
  const cp = byId('plugins');
  const csx = cp.cx, csz = cp.z0 - 9;
  const dw = cp.w, dd = 13;
  const deck = box(dw, 1.2, dd, C.deepSee, 0.94);
  put(deck, csx, 0.6, csz); cs.add(deck);
  const rim = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.BoxGeometry(dw,1.2,dd)), edgeMat(C.lumin, 0.8));
  put(rim, csx, 0.6, csz); cs.add(rim);

  const clus = SHIELDS.find(s => s.id === 'cluster');
  clus.features.forEach((f,i)=>{
    const x = csx + (i - 1.5) * (dw/4);
    cs.add(shieldModule(f, x, csz - 1.6, {
      /* narrower than its slot, so the name has a lane of its own beside it */
      w:dw/4 - 3.0, d:7, h:[6,0,5,4.4][i] || 5,
      /* the deck's top face, so the module stands ON it rather than in it */
      label:'short', onDark:true, baseY:1.22,
      /* 07 is south of the Cluster Shield, so the tether points +z */
      toward:1, tether:'07 を引き取る'
    }));
  });
  /* both captions CENTRED on the deck: left-anchored they ran out past the west
     edge of what the home shot frames (measured at x = -113) */
  cs.add(groundText(`${clus.lbl} — ${clus.jpScope}`,
    csx, csz+dd/2+2.0, 2.0, {color:'#01353E', mono:true, opacity:0.9}));
  cs.add(groundText('■3つ = 脆弱性・姿勢・アドミッション ／ □1つ = 07 の運用を引き取る',
    csx, csz+dd/2+4.6, 1.5, {color:'#4A8C93', mono:true, opacity:0.95}));
  world.add(cs);
  deployRefs.clusterShield = cs;
})();


/* ============================================================
   6c. the kernel / user-space membrane
   ------------------------------------------------------------
   The city laid nine districts out in a row and said nothing about the one line
   that explains most of its own design. The only trace of it was a floating
   `kernel boundary →` label west of 02.

   There are TWO crossings and they are not the same crossing, which is why one
   line will not do:

     01 → 02   user → kernel. The application ASKS. Everyone has to ask, which is
               why nothing can evade this (§workloads)
     02 → 03   kernel → user. The kernel HANDS OVER, through one shared-memory
               ring buffer, and that is the only place in the whole model where
               events are lost (INVARIANTS 1.1)

   Draw those two walls and a named zone between them, and four separate design
   decisions stop needing an explanation: why the ring buffer is the only thing
   that drops, why `base_syscalls` is described as the cheap filter *in the
   kernel*, why `buf_size_preset` and `cpus_for_each_buffer` are the dimensions of
   a handover, and — the one this was worth doing for — what `nodriver` actually
   is. Per the docs it does not delete the syscall SOURCE; it means there is no
   kernel→userspace ring buffer. With the wall drawn, that is what you see: the
   east wall goes, the zone empties, and the plugin lane is untouched because it
   never crossed here.

   Geometry: both walls sit in the FLOW_GAP the layout already leaves between
   districts, so nothing is displaced at any node count, and they span the driver
   district's depth plus a margin rather than the full flow band — a 100-unit wall
   would be a screen, not a boundary.
   ============================================================ */
(function kernelMembrane(){
  const wl = byId('workloads'), drv = byId('driver'), rg = byId('ring');
  const westX = (wl.x1 + drv.x0) / 2;          // middle of the 01|02 gap
  const eastX = (drv.x1 + rg.x0) / 2;          // middle of the 02|03 gap
  const zA = drv.z0 - 7, zB = drv.z1 + 7;
  const H = 26;
  const g = new THREE.Group();

  /* the zone: kernel space is a different address space, so it is drawn as a
     different patch of ground rather than as another coloured district */
  const zone = new THREE.Mesh(
    new THREE.PlaneGeometry(eastX - westX, zB - zA),
    new THREE.MeshBasicMaterial({color:C.g60, transparent:true, opacity:0.055,
                                 depthWrite:false}));
  zone.rotation.x = -Math.PI/2;
  zone.position.set((westX+eastX)/2, 0.02, (zA+zB)/2);
  g.add(zone);
  const zoneL = new THREE.LineSegments(
    new THREE.EdgesGeometry(new THREE.PlaneGeometry(eastX-westX, zB-zA)),
    edgeMat(C.g60, 0.30));
  zoneL.rotation.x = -Math.PI/2;
  zoneL.position.set((westX+eastX)/2, 0.025, (zA+zB)/2);
  g.add(zoneL);

  /* a wall: a faint membrane with vertical ribs, so it reads as something being
     crossed rather than as a pane of glass in the way */
  function membrane(x){
    const m = new THREE.Group();
    const face = new THREE.Mesh(
      new THREE.PlaneGeometry(zB - zA, H),
      new THREE.MeshBasicMaterial({color:C.g60, transparent:true, opacity:0.05,
                                   side:THREE.DoubleSide, depthWrite:false}));
    face.rotation.y = Math.PI/2;
    face.position.set(x, H/2, (zA+zB)/2);
    m.add(face);
    const pts = [];
    for(let z=zA; z<=zB+0.01; z+=(zB-zA)/10){ pts.push(x,0,z, x,H,z); }
    pts.push(x,0,zA, x,0,zB, x,H,zA, x,H,zB);
    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.Float32BufferAttribute(pts, 3));
    const ribs = new THREE.LineSegments(geo, edgeMat(C.g60, 0.42));
    m.add(ribs);
    /* A ghost of the same wall, DASHED. Dropping the solid wall's opacity was not
       enough to read as "this crossing does not exist" — two faint walls look like
       one lighting artefact. A dashed outline where a solid wall was is
       unambiguous, and it does it without borrowing red, which means "dropped"
       everywhere else in this city. */
    const ghost = new THREE.LineSegments(geo.clone(),
      new THREE.LineDashedMaterial({color:C.g40, transparent:true, opacity:0.85,
                                    dashSize:2.4, gapSize:2.0}));
    ghost.computeLineDistances();
    ghost.visible = false;
    m.add(ghost);
    m.userData.ribs = ribs;
    m.userData.ghost = ghost;
    m.userData.face = face;
    g.add(m);
    return m;
  }
  kernelRefs.west = membrane(westX);
  kernelRefs.east = membrane(eastX);

  /* Captions run ALONG each wall (rotZ), in the gap the wall stands in, so they
     never compete with a district's own ground text at any node count. */
  const along = (txt, x, hgt, col, op=0.95) =>
    groundText(txt, x, 0, hgt, {color:col, mono:true, opacity:op, y:0.08,
                                rotZ:-Math.PI/2});
  g.add(along('USER SPACE', westX - 3.4, 2.5, '#8A8C8E', 0.8));
  g.add(along('01 → 02 · syscall を頼む — 迂回できない', westX + 1.6, 1.7, '#3E4042'));
  g.add(along('02 → 03 · カーネル→ユーザ空間の渡し場 — 唯一の越境・唯一落ちる場所',
              eastX - 1.6, 1.7, '#3E4042'));
  g.add(along('USER SPACE', eastX + 3.4, 2.5, '#8A8C8E', 0.8));
  /* the zone's own name, on the empty ground the zone has south of the district */
  g.add(groundText('KERNEL SPACE', westX + 1.2, zB - 3.2, 2.8,
    {color:'#3E4042', mono:true, opacity:0.75, y:0.08}));

  /* the two states of the east wall. `severed` is not drawn in red: red is a
     DROP in this city's colour language and a missing handover is not a drop. */
  kernelRefs.crossing = along('渡し場は1つ — timestamp 順に読み出す', eastX + 1.2, 1.4, '#00A8BC');
  kernelRefs.severed  = along('nodriver — この渡し場が無い（syscall ソースが消えるのではない）',
                              eastX + 1.2, 1.4, '#8A8C8E');
  g.add(kernelRefs.crossing); g.add(kernelRefs.severed);
  kernelRefs.severed.visible = false;

  kernelRefs.zone = zone;
  kernelRefs.group = g;
  world.add(g);
  applyKernelBoundary(currentEnv());
})();

/* nodriver empties the kernel zone and takes the east wall with it. The west wall
   stays: an application still asks the kernel for things — nobody stopped making
   syscalls, there is just nothing carrying them up. That distinction is the whole
   of INVARIANTS 3.10 and it is now a thing you can see. */
function applyKernelBoundary(env = currentEnv()){
  const kp = env.kernelPath;
  if(kernelRefs.zone) kernelRefs.zone.material.opacity = kp ? 0.055 : 0.018;
  /* the east wall is the one nodriver takes: solid becomes a dashed ghost */
  const e = kernelRefs.east;
  if(e){
    e.userData.face.visible  = kp;
    e.userData.ribs.visible  = kp;
    e.userData.ghost.visible = !kp;
  }
  /* the west wall STAYS. Processes still ask the kernel for things under
     nodriver — nobody stopped calling execve. That is the half of §3.10 the
     model kept getting told and never showed. */
  const w = kernelRefs.west;
  if(w){
    w.userData.face.material.opacity = kp ? 0.05 : 0.05;
    w.userData.ribs.material.opacity = kp ? 0.42 : 0.42;
  }
  if(kernelRefs.crossing) kernelRefs.crossing.visible = kp;
  if(kernelRefs.severed)  kernelRefs.severed.visible  = !kp;
}

/* the registry city.js wires onto each district */
const BUILDERS = {
  workloads:BUILD_workloads, driver:BUILD_driver, ring:BUILD_ring, state:BUILD_state,
  rules:BUILD_rules, outputs:BUILD_outputs, plugins:BUILD_plugins,
  falcoctl:BUILD_falcoctl, sysdig:BUILD_sysdig
};

export {
  BUILDERS,
  applyEnvironment,
  applyCpus,
  applyBuffers,
  applyNodes,
  applyRuleFiles,
  applyKernelBoundary,
  ruleRefs,
  kernelRefs,
  crateRefs,
  nodeRefs,
  topoVariants,
  captionRefs,
  driverSlabs,
  RING_LANES,
  RULE_BLOCKS,
  OUT_PIPES,
  ringRefs,
  outRefs,
  stateRefs,
  deployRefs,
  sysdigGroup
};
