/* Generated by the module split. See README §開発の分担. */
import { C } from './palette.js';


/* ============================================================
   1a. the environment — four orthogonal axes
   ------------------------------------------------------------
   This used to be one axis with four values (host / self-managed k8s /
   managed k8s / kernel-less), resting on the claim that "managed Kubernetes
   cannot load a kernel module". That claim does not survive the primary
   sources. The only environment Falco documents as unable to load its
   kernel module is GKE's Container-Optimized OS, and the constraint belongs
   to the node image, not to who runs the control plane — EKS and AKS do not
   appear on that page at all. Likewise "a systemd host only has
   container.id and never fires a k8saudit rule" was wrong twice over:
   container metadata comes off the container runtime socket, which is
   orthogonal to how Falco was installed, and k8saudit runs fine on a host.

   So the environment is four axes that switch independently, and each axis
   value carries the consequence it causes and nothing else:

     orchestrator    changes how the Kubernetes audit log is COLLECTED.
                     Self-managed can point a static audit webhook at Falco.
                     Managed cannot, so a provider plugin PULLS the log
                     (EKS = CloudWatch Logs, AKS = Event Hub, GKE = Pub/Sub)
     node OS         COS cannot insert a kernel module, so Modern eBPF is
                     mandatory. This is the ONLY documented case of kmod
                     being impossible, which is why it hangs off the node
                     image and not off the orchestrator
     runtime socket  whether container.* and — in Kubernetes — k8s.pod.* /
                     k8s.ns.name get attached at all. Unreachable leaves
                     container.id and container.type, because those two come
                     from the cgroup inside the kernel and need no socket
     k8smeta plugin  whether the API-server-derived fields exist. Falco 0.37
                     moved them out of the engine into the k8smeta plugin +
                     k8s-metacollector, and the old k8s.deployment.name
                     family now evaluates to <NA> in rules

   Sources, in order: falco.org/docs/setup/enviroments (COS / kmod),
   falco.yaml's own comments (the container plugin reads the runtime socket),
   plugins/k8saudit-eks/README.md (single instance), the Falco 0.37 release
   notes and k8smeta plugin docs.

   Adding a value is a declaration in one of these arrays. controls.js
   renders a button for it and log.js reads its consequences; neither file
   contains an environment id, and that is the invariant to keep.
   ============================================================ */

/* Pads sit on a fixed pitch, centred on the district. The constants are the
   ones the hand-written three-node version worked out to, so a 3-node cluster
   is geometrically identical to before. */
const NODE_PITCH = 11.875;   // pad depth 10.4 + gap
const NODE_MARGIN = 2.375;   // clearance at both ends of the district
const NODE_PAD_W = 24, NODE_PAD_D = 10.4;
const POD_PITCH = 4.8;

/* ---------- axis 1: orchestrator — how the audit log is COLLECTED ----------
   `audit` is the whole causal payload. `null` means there is no Kubernetes
   audit log to collect, so no k8saudit rule can fire — not because of how
   Falco was installed, but because the input does not exist.

     pull        the plugin fetches from a provider log sink instead of
                 receiving a webhook push
     controller  what actually gets deployed for the audit path
     replicas    how many of it. 1 where a source says so, and only there
     single      duplicate alerts if you run more than one. EKS only
     driver /    whether that instance carries a driver and collectors.
     collectors  false where the official Helm values say so, null where no
                 source states it — the model does not guess                */
const ORCH = [
  {
    id:'none', lbl:'なし', jp:'オーケストレータなし', wire:'host',
    cluster:false, apiServer:false, managed:false, audit:null,
    why:'Kubernetes が無いので、k8saudit の入力そのものが存在しない。'+
        'syscall 側の検知はこれとは無関係に成立する',
    caption:() => 'SINGLE HOST · falco.service (systemd)'
  },
  {
    id:'k8s', lbl:'self-managed', jp:'self-managed k8s', wire:'k8s',
    cluster:true, apiServer:true, managed:false,
    audit:{
      plugin:'k8saudit', transport:'audit webhook', pull:false,
      controller:'daemonset', replicas:null, single:false,
      driver:true, collectors:true,
      lbl:'k8saudit · webhook → falco (DaemonSet 同居)',
      why:'apiserver の監査 webhook を Falco に向けられる。syscall を見ている'+
          'その Falco がそのまま受けるので、監査用の別インスタンスは要らない'
    },
    caption:n => `KUBERNETES CLUSTER · ${n} NODES · DAEMONSET`
  },
  {
    id:'eks', lbl:'EKS', jp:'managed k8s · EKS', wire:'eks',
    cluster:true, apiServer:true, managed:true,
    audit:{
      plugin:'k8saudit-eks', transport:'CloudWatch Logs', pull:true,
      controller:'deployment', replicas:1, single:true,
      driver:false, collectors:false,
      lbl:'k8saudit-eks · Deployment · replicas: 1',
      why:'プラグインが CloudWatch Logs から pull するので、2つ以上動かすと同じログを'+
          '二重に取り、アラートが重複する。公式 Helm 値は controller.kind: deployment / '+
          'replicas: 1 / driver.enabled: false / collectors.enabled: false — '+
          '監査経路には DaemonSet ではなく単一の Deployment が建ち、そこはドライバも'+
          'コレクタも無効'
    },
    caption:n => `EKS · ${n} NODES · DAEMONSET + AUDIT DEPLOYMENT (replicas 1)`
  },
  {
    id:'gke', lbl:'GKE', jp:'managed k8s · GKE', wire:'gke',
    cluster:true, apiServer:true, managed:true,
    audit:{
      plugin:'k8saudit-gke', transport:'Pub/Sub', pull:true,
      controller:'deployment', replicas:3, single:false,
      driver:null, collectors:null,
      lbl:'k8saudit-gke · Deployment · replicas: 複数可',
      why:'Pub/Sub の exactly-once 配信を使うので、単一リージョン内なら複数インスタンスが'+
          '明示的に許されている。EKS の単一インスタンス制約をここに一般化してはいけない'
    },
    caption:n => `GKE · ${n} NODES · DAEMONSET + AUDIT DEPLOYMENT`
  },
  {
    id:'aks', lbl:'AKS', jp:'managed k8s · AKS', wire:'aks',
    cluster:true, apiServer:true, managed:true,
    audit:{
      plugin:'k8saudit-aks', transport:'Event Hub', pull:true,
      controller:'deployment', replicas:1, single:false,
      driver:null, collectors:null,
      lbl:'k8saudit-aks · Deployment · Event Hub',
      why:'Event Hub から pull する。単一インスタンスの注意書きは資料に無いので、'+
          'この模型では単一必須だとは主張しない'
    },
    caption:n => `AKS · ${n} NODES · DAEMONSET + AUDIT DEPLOYMENT`
  }
];

/* ---------- axis 2: node OS — the only place kmod can be impossible ---------- */
const NODE_OSES = [
  { id:'generic', lbl:'汎用 Linux', jp:'汎用 Linux', blocks:[], why:null },
  { id:'cos', lbl:'COS', jp:'Container-Optimized OS',
    blocks:['kmod'],
    why:'COS はセキュリティ制約でカーネルモジュールを挿入できないので、Modern eBPF が必須。'+
        'Falco が kmod 不可を文書化しているのはこの1件だけで、managed かどうかの話ではない' }
];

/* ---------- axis 3: container runtime socket ----------
   The container plugin reads the runtime socket. Reach it and you get the
   whole container.* space plus, in Kubernetes, the pod fields — because the
   runtime knows which pod its containers belong to. Lose it and you keep
   exactly the two fields the kernel can answer from the cgroup. */
const SOCKETS = [
  { id:'reachable', lbl:'到達可', jp:'ランタイムソケット 到達可',
    containerFields:['container.id','container.type','container.name',
                     'container.image.repository','container.image.tag',
                     'container.privileged','container.mount.*','… 約28'],
    podFields:['k8s.ns.name','k8s.pod.name','k8s.pod.id','k8s.pod.uid',
               'k8s.pod.sandbox_id','k8s.pod.label[*]','k8s.pod.ip',
               'k8s.pod.cni.json'],
    why:'container プラグインが CRI / docker ソケットからコンテナのメタデータを取る。'+
        'DaemonSet か systemd かとは直交する — ソケットに届くかどうかだけの問題' },
  { id:'unreachable', lbl:'不可', jp:'ランタイムソケット 到達不可',
    containerFields:['container.id','container.type'],
    podFields:[],
    why:'cgroup から取れる container.id と container.type だけが残る。'+
        'この2つはカーネル内で決まるのでソケットを必要としない' }
];

/* ---------- axis 4: k8smeta plugin — the API-server-derived fields ----------
   Falco 0.37 removed the built-in k8s client. The deployment / replicaset /
   service / replicationcontroller names now come from the k8smeta plugin
   talking to k8s-metacollector (still marked experimental), and the old
   k8s.* spellings evaluate to <NA> in rules. k8s.pod.* is NOT in that list:
   it survives because its source is the container runtime, not the API. */
const K8S_METAS = [
  { id:'on', lbl:'有', jp:'k8smeta プラグイン 有',
    fields:['k8smeta.pod.name','k8smeta.ns.name','k8smeta.deployment.name',
            'k8smeta.rs.name','k8smeta.svc.name'],
    naFields:[],
    why:'k8smeta プラグイン ＋ k8s-metacollector で apiserver 由来のフィールドが付く。'+
        'k8s.pod.name とは併用可（置き換えではなく追加）' },
  { id:'off', lbl:'無', jp:'k8smeta プラグイン 無',
    fields:[],
    naFields:['k8s.deployment.name','k8s.rs.name','k8s.svc.name','k8s.rc.name'],
    why:'非推奨になった k8s.deployment.name 系はルールで使うと <NA> になる。'+
        'ワークロード名で相関したいなら k8smeta を入れるしかない' }
];

/* ---------- the driver lever ----------
   Not one of the four environment axes — it is the operator's choice — but
   it is declared here because the node OS axis is allowed to forbid values
   and because `nodriver` is what switches the kernel path off. Per the
   docs, nodriver does not delete the syscall source; it means no
   kernel→userspace ring buffer, so only plugins actually deliver events. */
const DRIVERS = [
  { id:'modern_ebpf', lbl:'modern_ebpf', kernelPath:true, slab:true,
    note:'CO-RE eBPF。kernel ≥ 5.8、ビルド不要。0.38 以降の既定' },
  /* The retirement date this used to carry (2026-12-04) belongs to SYSDIG's
     legacy eBPF driver, not to Falco's probe — two clocks with two owners
     (BOARD D2 / D3). Rather than swap one unsourced date for another, the claim
     is dropped until INVARIANTS carries it; `deprecated` is the part every
     source agrees on. */
  { id:'ebpf', lbl:'ebpf', kernelPath:true, slab:true, deprecated:true,
    note:'legacy eBPF プローブ。falco-probe.o をカーネルに合わせて用意する必要がある（非推奨）' },
  { id:'kmod', lbl:'kmod', kernelPath:true, slab:true,
    note:'カーネルモジュール。完全な権限が必要。COS では挿入できない' },
  { id:'nodriver', lbl:'nodriver', kernelPath:false, slab:false,
    note:'ドライバを注入しない。カーネル→ユーザ空間のリングバッファが無いので、'+
         '実際にイベントを届けるのはプラグインだけになる' }
];

/* ---------- the west end, as geometry ----------
   Geometry only cares about three shapes, so only three get built. Which one
   is on screen follows from the composed environment, not from an id.

     shape    'nodes'   node pads carrying pods — a cluster
              'machine' one slab carrying named processes — a single host
              'none'    no syscall-emitting west end to draw (nodriver)
     nodes    how many pads. The district's own depth is derived from the
              largest count declared here, so the layout engine re-flows the
              rest of the city on its own — no coordinate needs touching   */
const TOPOLOGIES = [
  { id:'machine', shape:'machine', nodes:1, boundary:false,
    /* fewer, taller, named — a host is not a pile of interchangeable pods */
    procs:[['systemd',13],['sshd',7],['nginx',16],['cron',5],
           ['postgres',19],['node',11],['dockerd',9],['rsyslog',6]],
    procsPerRow:4, slabW:26, slabD:34 },
  { id:'cluster', shape:'nodes', nodes:3, podsPerNode:5, boundary:true },
  { id:'bare', shape:'none', nodes:0, boundary:false }
];

/* Ceiling on node count. From 4 nodes up, the workloads district becomes the
   deepest thing on the flow axis and starts pushing the north annexes outward.
   Measured against the 340×240 ground plane (z must stay inside ±120):

     nodes   4      8      11     12     14
     depth   49.9   97.4   133.0  144.9  168.6
     city z  -71.9  -95.7  -113.5 -119.4 -131.3  ← off the ground at 14

   So 12 is the hard geometric edge, with 0.6 units to spare. 8 is the limit
   here: it keeps ~24 units of margin and the pipeline still reads at the
   1280×720 floor. No two districts overlap at any count from 1 to 20. */
const NODE_MAX = 8;

/* z of each pad, centred: nodeOffsets(3) === [-11.875, 0, 11.875] */
const nodeOffsets = n => Array.from({length:n}, (_, i) => (i - (n-1)/2) * NODE_PITCH);
/* how deep the workloads district has to be: workloadsDepth(3) === 38 */
const workloadsDepth = n => n * NODE_PITCH + NODE_MARGIN;

/* Node count is module-local on purpose: it belongs in S, and state.js is
   another session's file this phase. `?nodes=N` overrides the clustered
   topology so the layout can be checked at 1 / 2 / 3 / 5 / 8 without an edit.
   Guarded for Node, where the check scripts import this module with no DOM. */
const nodeOverride = (() => {
  if(typeof location === 'undefined') return null;
  const n = Number(new URLSearchParams(location.search).get('nodes'));
  return Number.isInteger(n) && n >= 1 ? Math.min(n, NODE_MAX) : null;
})();
const nodeCount = t => t.shape === 'nodes' ? (nodeOverride ?? t.nodes) : t.nodes;
const MAX_NODES = Math.max(...TOPOLOGIES.map(nodeCount));
const byTopologyId = id => TOPOLOGIES.find(t => t.id === id);

/* How many pads a cluster actually has. Captions need it before compose runs,
   and it is a `let` on purpose: a scenario is allowed to declare its own node
   count (scenarios/schema.js §env.nodes), and until now that number reached the
   noise model through S.nodes and never reached the ground — the city drew the
   topology's default three whatever the scenario said. `nodes-are-not-buffers`
   teaches "six nodes, and still one ring buffer each"; with three pads on screen
   it teaches nothing.

   So this is the single place the count lives, districts.build.js §applyNodes
   redraws the cluster from it, and controls.js's own write-back of S.nodes now
   assigns the value that is already true instead of overwriting it.

   `?nodes=N` still wins outright, so the layout stays checkable from the URL.

   What does NOT move is MAX_NODES, and therefore the workloads district's
   declared depth: the layout engine runs once at module load, long before any
   scenario is chosen, so the rectangle cannot follow. applyNodes() packs the
   pads into the rectangle it was given instead. */
let CLUSTER_NODES = nodeCount(byTopologyId('cluster'));
function setClusterNodes(n){
  if(nodeOverride != null) return;                   // the URL override is deliberate
  if(!Number.isFinite(n)) return;
  CLUSTER_NODES = Math.max(1, Math.min(NODE_MAX, Math.round(n)));
  return CLUSTER_NODES;
}


/* ============================================================
   1a-1b. CPUs on ONE node, and the buffer count that follows
   ------------------------------------------------------------
   INVARIANTS 3.6: the ring buffer count is

       ceil(nCPU / cpus_for_each_buffer)          modern_ebpf, default 2

   and nCPU is a property of one node. Adding nodes adds DaemonSet pods; the
   node that is overflowing gets no new buffer out of it.

   This used to be the literal 8 in two places — the ring district's lane loop
   and the TUNING label, which therefore always read "2 → 4 buffers" no matter
   what node you were standing on. That is a units error the model was
   teaching, and it directly contradicts the nodes-are-not-buffers scenario,
   whose whole diagnosis is that the new 2-vCPU nodes get ceil(2/2) = 1 buffer
   where the old 8-vCPU nodes had ceil(8/2) = 4.

   So the count is declared once, here, and everything derives from it:

     CPU_MAX          how many lanes the ring district builds. The ceiling, not
                      the count — lanes above the current count are hidden
     NODE_CPUS        what one node has when nothing says otherwise. 8, because
                      that is what the district was drawn for and what the
                      README's measurements were taken against
     nodeCpus()       the current count. THE swap point: when the scenario
                      schema grows a per-environment CPU count (L1 is adding
                      it), setNodeCpus() is what the environment layer calls
                      and nothing else in the model has to change
     bufferCount()    ceil(cpus / cpusPerBuf). Used by the label AND by the
                      geometry, so the two cannot disagree

   `?cpus=N` overrides it the same way `?nodes=N` overrides the node count, so
   the derivation is checkable at 1 / 2 / 4 / 8 before the attribute lands.
   ============================================================ */
const CPU_MAX = 8;
const NODE_CPUS = 8;

const cpuOverride = (() => {
  if(typeof location === 'undefined') return null;
  const n = Number(new URLSearchParams(location.search).get('cpus'));
  return Number.isInteger(n) && n >= 1 ? Math.min(n, CPU_MAX) : null;
})();

let _cpus = cpuOverride ?? NODE_CPUS;
const nodeCpus = () => _cpus;
/* The environment layer's single entry point. Returns the count actually in
   force, so a caller can tell when it asked for more than the district can
   draw. An explicit `?cpus=` on the URL wins, because it is a debug override. */
function setNodeCpus(n){
  if(cpuOverride == null && Number.isInteger(n) && n >= 1) _cpus = Math.min(n, CPU_MAX);
  return _cpus;
}
/* the one formula. cpus defaults to the current node so callers cannot forget.
   `0` is not "one CPU per buffer" — falco.yaml spells it out as "a single ring
   buffer shared by ALL online CPUs", which is the opposite end of the range. The
   TUNING panel only offers 1 / 2 / 4 so this branch is unreachable from the UI
   today, but the district body quotes the 0 case and the two must not disagree. */
const bufferCount = (cpusPerBuf, cpus = nodeCpus()) =>
  cpusPerBuf === 0 ? 1
                   : Math.max(1, Math.ceil(cpus / Math.max(1, cpusPerBuf)));


/* ============================================================
   1a-1c. what a Shield actually CONTAINS
   ------------------------------------------------------------
   Until now the two Sysdig Shields were a boundary and a deck: Host Shield was
   literally "the box drawn round 02〜06", so the one question a viewer arrives
   with — *what do I get if I put Sysdig in?* — had no answer anywhere in the
   city. The feature lists are primary-sourced (docs.sysdig.com, Onboarding for
   Sysdig Secure → Sysdig Shield: "Host Shield consolidates the following
   features in one application" / same sentence for Cluster Shield) and they are
   short, closed lists, so they can be drawn rather than summarised.

   The load-bearing field is `kind`, and it exists to protect INVARIANTS §5.2:

     'operate'  this city ALREADY does this, in the districts named by `at`.
                The Shield does not add it — it takes over running it. Drawn
                hollow and tethered to those districts, never as a new building.
                Runtime Threat Detection is the whole reason this distinction
                has to be in the DATA and not in a builder's discretion: it is
                the same libs and the same Falco engine (§5.4), so if it ever
                reads as a detection being ADDED, the model has started lying
                about the one thing `npm test` guards hardest.
     'new'      a job the city does not have a district for at all. Vulnerability
                scanning, posture, remote response. Drawn as a solid building,
                because something genuinely arrived.

   Four solid buildings and two tethers is therefore the honest picture, and it
   is readable without a caption: nothing solid lands anywhere near the pipeline.

   `admission_control` has no feature-list name of its own — it is one of the
   four Cluster Shield config sections the install docs enable — so it carries
   its config key as its name and nothing else is claimed about it.
   ============================================================ */
const SHIELDS = [
  {
    id:'host', lbl:'HOST SHIELD', jp:'Host Shield', scope:'node scoped',
    jpScope:'ノード単位',
    deploy:'K8s: DaemonSet · 単体ホスト: パッケージ／コンテナ',
    features:[
      { id:'runtime', en:'Runtime Threat Detection', jp:'ランタイム脅威検知',
        kind:'operate', at:['driver','ring','state','rules','outputs'],
        why:'02〜06 と同じ libs・同じ Falco エンジン。検知は1段も増えない — '+
            '同じ検知を別の場所から運用するだけ' },
      { id:'hostVuln', en:'Host Vulnerability Scanning', jp:'ホスト脆弱性スキャン',
        kind:'new', why:'ホスト上のパッケージを定期スキャンする。振る舞いの検知とは別の仕事' },
      { id:'kspmHost', en:'KSPM for Hosts', jp:'ホストの姿勢管理',
        kind:'new', why:'ホストの設定をコンプライアンスポリシーに照らす。予防側' },
      { id:'rapid', en:'Rapid Response', jp:'遠隔シェルでの初動',
        kind:'new', why:'指定した担当者がリモートシェルで調査できる。検知ではなく対処' }
    ]
  },
  {
    id:'cluster', lbl:'CLUSTER SHIELD', jp:'Cluster Shield', scope:'cluster scoped',
    jpScope:'クラスタ単位（Deployment）',
    deploy:'クラスタに1つ。守るクラスタが無い構成には存在しない',
    features:[
      { id:'ctrVuln', en:'Container Vulnerability Scanning', jp:'コンテナ脆弱性スキャン',
        key:'container_vulnerability_management',
        kind:'new', why:'実行中のイメージをスキャンする。この都市に対応する地区は無い' },
      { id:'k8sAudit', en:'Kubernetes Audit Threat Detection', jp:'K8s 監査ログの脅威検知',
        key:'audit', kind:'operate', at:['plugins'],
        why:'07 の k8saudit と同じ入力・同じルール言語。検知は増えず、取得と運用を引き取る' },
      { id:'kspmCluster', en:'KSPM for Clusters', jp:'クラスタの姿勢管理',
        key:'posture', kind:'new', why:'クラスタのマニフェストを集めて評価する。予防側' },
      { id:'admission', en:'admission_control', jp:'アドミッション制御',
        key:'admission_control', kind:'new',
        why:'入る前に止める。Cluster Shield の設定4区画のうちの1つで、'+
            '機能一覧に固有の名前は無いので設定キーのまま置く' }
    ]
  }
];
const shieldById = id => SHIELDS.find(s => s.id === id) || null;


/* ============================================================
   1a-2. the axes as levers, and the composition
   ------------------------------------------------------------
   ENV_AXES is what controls.js renders. ENV_SEL is what is selected. Both
   live here rather than in state.js only because state.js belongs to another
   session this phase; controls.js is the single writer either way.

   composeEnv is a pure function of the selection. Everything downstream —
   which west end is on screen, which audit route is built, which fields the
   console log can print, which driver buttons are legal — reads a field it
   returns. That is what keeps the environment ids out of controls.js and
   log.js: they ask what is true, not which environment it is.
   ============================================================ */
const ENV_AXES = [
  { id:'orch',    lbl:'orchestrator',  values:ORCH,
    hint:'k8saudit の取得経路が変わる' },
  { id:'nodeOs',  lbl:'node os',       values:NODE_OSES,
    hint:'COS は kmod をロードできない' },
  { id:'socket',  lbl:'runtime socket', values:SOCKETS,
    hint:'container.* と k8s.pod.* が付くか' },
  { id:'k8sMeta', lbl:'k8smeta',       values:K8S_METAS,
    hint:'k8s.deployment.name 系が付くか' }
];

const ENV_SEL = {
  orch:'k8s', nodeOs:'generic', socket:'reachable', k8sMeta:'on',
  driver:'modern_ebpf'
};

const pick = (list, id, fallback) => list.find(x => x.id === id) ?? fallback;

function composeEnv(sel = ENV_SEL){
  const orch   = pick(ORCH,       sel.orch,    ORCH[1]);
  const nodeOs = pick(NODE_OSES,  sel.nodeOs,  NODE_OSES[0]);
  const socket = pick(SOCKETS,    sel.socket,  SOCKETS[0]);
  const meta   = pick(K8S_METAS,  sel.k8sMeta, K8S_METAS[0]);
  const driver = pick(DRIVERS,    sel.driver,  DRIVERS[0]);

  const kernelPath = driver.kernelPath;
  const cluster    = orch.cluster;
  const apiServer  = orch.apiServer;
  /* k8s-metacollector watches the API server, so the plugin has nothing to
     talk to without one. Selecting it is still allowed and remembered — the
     axis stays independent; it just has no consequence to cause. */
  const k8sMeta = meta.id === 'on' && apiServer;
  /* pod fields ride the runtime socket, but only pods have them: the socket
     on a plain host can name containers and cannot invent a namespace */
  const podFields = cluster ? socket.podFields : [];

  return {
    id:[orch.id, nodeOs.id, socket.id, meta.id, driver.id].join('/'),
    orch, nodeOs, socket, meta, driver,
    /* the legacy wire value S.deploy carries. state.js, sim.js and
       campaign.js still compare against these strings and belong to other
       sessions this phase, so keep feeding them something they understand. */
    wire: kernelPath ? orch.wire : 'plugins',
    cluster, apiServer, managed:orch.managed, kernelPath,
    k8sMeta, k8sMetaAsked: meta.id === 'on',
    blockedDrivers: nodeOs.blocks,
    containerFields: socket.containerFields,
    podFields,
    metaFields: k8sMeta ? meta.fields : [],
    naFields:   k8sMeta ? [] : meta.naFields,
    /* the audit log exists whether or not a driver does — that is the point
       of (b): k8saudit runs on a host, and it runs with nodriver */
    audit: orch.audit,
    topology: !kernelPath ? 'bare' : cluster ? 'cluster' : 'machine',
    /* Host Shield is the driver-bearing half, so nodriver leaves none of it.
       Cluster Shield is cluster-scoped and driverless (admission / audit /
       posture / vuln mgmt), so it survives wherever there is a cluster. */
    shield:{ host:kernelPath, cluster }
  };
}

let _env = composeEnv();
const currentEnv = () => _env;
/* set one axis. Returns the recomposed environment so the caller can react
   without asking twice. Unknown axes and values are ignored on purpose. */
function setEnvAxis(axis, value){
  if(!(axis in ENV_SEL)) return _env;
  ENV_SEL[axis] = value;
  _env = composeEnv();
  return _env;
}

/* ============================================================
   1a-3. named environments
   ------------------------------------------------------------
   The axes are the truth. These are named POSITIONS on them, and they exist
   because a scenario has to hand the player a place — "you inherited a
   self-managed cluster" — rather than four dropdowns. Every attribute below
   is DERIVED by composeEnv, so a named environment cannot disagree with the
   axes it stands on.

     id       the wire value S.deploy carries, and what setDeploy() takes
     env      the scenario-facing name (scenarios/schema.js §ENVIRONMENTS)
     nodeOs   which node OS axis value this environment stands on
     kmodOk   whether a kernel module can be loaded here. FALSE ONLY where the
              node OS forbids it. **Not** because a cluster is managed: EKS
              and AKS have no documented kmod restriction, and asserting one
              is exactly the error this table used to carry
     drivers  the driver ids that are legal here, derived from kmodOk and from
              whether there is a kernel path at all. Ready for the scenario
              layer to use directly, so nothing downstream has to re-derive it

   GKE is the one named environment that stands on COS, because that is what
   Falco documents GKE as using. Even there the constraint belongs to the node
   image and not to GKE: the node OS axis is switchable underneath it.
   ============================================================ */
const DEPLOY_PRESETS = {
  host:    { orch:'none', nodeOs:'generic', socket:'reachable', k8sMeta:'off',
             driver:'modern_ebpf' },
  k8s:     { orch:'k8s',  nodeOs:'generic', socket:'reachable', k8sMeta:'on',
             driver:'modern_ebpf' },
  eks:     { orch:'eks',  nodeOs:'generic', socket:'reachable', k8sMeta:'on',
             driver:'modern_ebpf' },
  gke:     { orch:'gke',  nodeOs:'cos',     socket:'reachable', k8sMeta:'on',
             driver:'modern_ebpf' },
  aks:     { orch:'aks',  nodeOs:'generic', socket:'reachable', k8sMeta:'on',
             driver:'modern_ebpf' },
  plugins: { orch:'k8s',  nodeOs:'generic', socket:'unreachable', k8sMeta:'on',
             driver:'nodriver' }
};
/* the old wire value for managed Kubernetes, before the providers were split
   apart. Kept so `setDeploy('managed')` from a console or a bookmark still
   lands somewhere sensible. */
DEPLOY_PRESETS.managed = DEPLOY_PRESETS.eks;

const NAMED_ENVS = [
  { id:'host',    env:'standalone',       jp:'スタンドアロンサーバ' },
  { id:'k8s',     env:'self-managed-k8s', jp:'self-managed k8s' },
  /* `managed-k8s` is EKS: it is the provider whose audit path is fully sourced,
     and keeping the name means scenarios written against it do not move */
  { id:'eks',     env:'managed-k8s',      jp:'managed k8s · EKS' },
  { id:'gke',     env:'managed-k8s-cos',  jp:'managed k8s · GKE (COS ノード)' },
  { id:'aks',     env:'managed-k8s-aks',  jp:'managed k8s · AKS' },
  { id:'plugins', env:'serverless',       jp:'サーバレス／特権なし (nodriver)' }
];

const DEPLOYMENTS = NAMED_ENVS.map(n => {
  const env = composeEnv(DEPLOY_PRESETS[n.id]);
  const topo = byTopologyId(env.topology);
  const kmodOk = !env.blockedDrivers.includes('kmod');
  return {
    ...env,
    id:n.id, env:n.env, jp:n.jp,
    /* geometry projection, so nodeCount() works on these entries too */
    shape:topo.shape, nodes:nodeCount(topo),
    /* the node OS axis, named, for anyone who needs the reason and not just
       the consequence */
    nodeOs:env.nodeOs.id, kmodOk,
    drivers:env.kernelPath
      ? DRIVERS.filter(d => d.slab && (d.id !== 'kmod' || kmodOk)).map(d => d.id)
      : []
  };
});

/* Look up a named environment. The live composition wins when it is the one
   being asked about, so hasCap() in state.js follows the axes the player is
   actually moving rather than the preset the scenario started from. */
function byDeployId(id){
  const live = currentEnv();
  if(id === live.wire) return live;
  return DEPLOYMENTS.find(d => d.id === id) || null;
}


/* ============================================================
   1a-4. the three rule files
   ------------------------------------------------------------
   INVARIANTS §4.1: maturity and FILE are 1:1 in falcosecurity/rules, and only
   `falco_rules.yaml` ships in the release package. "Is this rule in by default"
   is therefore not a flag on the rule — it is *which file you fetched*, and the
   counts (25 / 31 / 37) are what makes "Falco の既定ルールは思ったより少ない"
   a thing you can see instead of a thing you have to be told.

   `shipped` is the whole causal payload: the district draws a crate per file and
   opens exactly the ones that are shipped, so the picture cannot drift from the
   claim. Counts are the number of rules in each file on falcosecurity/rules
   main, per §4.1.
   ============================================================ */
const RULE_FILES = [
  { id:'stable', lbl:'stable', file:'falco_rules.yaml',
    count:25, shipped:true,
    why:'リリースパッケージに同梱される唯一のファイル。既定で読み込まれるのはこれだけ' },
  { id:'incubating', lbl:'incubating', file:'falco-incubating_rules.yaml',
    count:31, shipped:false,
    why:'別の OCI アーティファクト（falco-incubating-rules）。falcoctl で取りに行く' },
  { id:'sandbox', lbl:'sandbox', file:'falco-sandbox_rules.yaml',
    count:37, shipped:false,
    why:'別の OCI アーティファクト（falco-sandbox-rules）。より実験的' }
];
/* the ids the engine has actually loaded. A `let` for the same reason
   CLUSTER_NODES is one: the maturity lever (policies.js §LEVERS) is arriving in
   another lane, and when it does, setRuleFiles() is the single call that has to
   reach the ground. Until then the default IS the claim — stable only. */
let LOADED_RULE_FILES = RULE_FILES.filter(f => f.shipped).map(f => f.id);
function setRuleFiles(ids){
  if(!Array.isArray(ids)) return LOADED_RULE_FILES;
  const known = RULE_FILES.map(f => f.id);
  LOADED_RULE_FILES = ids.filter(id => known.includes(id));
  return LOADED_RULE_FILES;
}
const loadedRuleFiles = () => LOADED_RULE_FILES;
const loadedRuleCount = () =>
  RULE_FILES.filter(f => LOADED_RULE_FILES.includes(f.id))
            .reduce((n,f) => n + f.count, 0);


/* ============================================================
   1. district model  (flow runs along +X)
   ============================================================ */
const DISTRICTS = [
  {
    id:'workloads', n:'01', tag:'WORKLOADS',
    hoverT:'WORKLOADS / PROCESSES', hoverS:'コンテナ・Pod・ホストのプロセス — すべての起点',
    hoverM:['execve · openat · connect · ptrace','~80 interesting syscalls'],
    jp:'ワークロード', en:'workloads / processes',
    /* depth follows the largest declared topology; 3 nodes === 38 as before */
    w:22, d:workloadsDepth(MAX_NODES), top:22, color:C.g20, cam:[-118,46,58],
    metrics:[['観測対象','syscall + 一部の非 syscall'],['改造','アプリ変更ゼロ']],
    body:`
<h3>ここで何が起きているか</h3>
<p>コンテナ・Pod・ホスト上のプロセスが動くと、必ず <strong>システムコール</strong> が発行される。ファイルを開く <code>openat</code>、プロセスを起こす <code>execve</code>、外に繋ぐ <code>connect</code>、他プロセスを覗く <code>ptrace</code> — アプリが何をしようとしても、最後はカーネルに頼むしかない。</p>
<p>Falco がここを起点に選ぶ理由は単純で、<span class="mark">カーネルの境界は誰も迂回できない</span>から。言語もフレームワークもベースイメージも問わない。サイドカーも SDK も不要。</p>
<h3>ここでの設計上のポイント</h3>
<ul>
<li>アプリに手を入れない = 開発チームへの依存がゼロ。だから「あとから全ワークロードに」入れられる</li>
<li>見えるのは <em>振る舞い</em>。「脆弱性があるか」ではなく「実際に何をしたか」</li>
<li>ホストのプロセスもコンテナ外のプロセスも同じ経路で見える。Kubernetes だけの話ではない</li>
</ul>
<div class="takeaway"><span class="cv">▸</span>すべての検知は「カーネルに頼んだ事実」から始まる。だから逃げ道がない。</div>`
  },
  {
    id:'driver', n:'02', tag:'DRIVER (KERNEL)',
    hoverT:'DRIVER — KERNEL SPACE', hoverS:'tracepoint にアタッチし、関心のある syscall だけを通す門',
    hoverM:['modern_ebpf · ebpf · kmod · nodriver','kmod が不可なのは COS だけ'],
    jp:'ドライバ（カーネル空間）', en:'driver — modern_ebpf / ebpf / kmod / nodriver',
    w:13, d:46, top:18, color:C.falco, cam:[-88,40,62],
    metrics:[['既定','modern_ebpf (CO-RE)'],['kmod 不可','COS（ノード OS 由来）']],
    body:`
<h3>3つの目のうち、どれを使うか</h3>
<ul>
<li><code>modern_ebpf</code> — CO-RE eBPF。カーネル 5.8 以上、<strong>ビルド不要・カーネルモジュール不要</strong>。0.38 以降の既定</li>
<li><code>ebpf</code> — 従来型 eBPF プローブ。<code>falco-probe.o</code> をカーネルに合わせて用意する必要がある（<strong>非推奨</strong>）</li>
<li><code>kmod</code> — カーネルモジュール。完全な権限が必要</li>
<li><code>nodriver</code> — ドライバを注入しない。<span class="mark">syscall ソースが消えるのではなく、カーネル→ユーザ空間のリングバッファが無い</span>ので、実際にイベントを届けるのはプラグインだけになる</li>
</ul>
<h3>どこで <code>kmod</code> が選べないのか</h3>
<p>「マネージド Kubernetes ではカーネルモジュールが使えない」は<strong>誤り</strong>。制約は<span class="mark">ノード OS の属性</span>で、コントロールプレーンを誰が運用しているかとは無関係。Falco が文書化しているのは <strong>GKE の Container-Optimized OS (COS)</strong> ただ1件で、EKS・AKS はそのページに登場しない。</p>
<p>だから NODE OS を <code>COS</code> にすると <code>kmod</code> のボタンが落ちる。ORCHESTRATOR を動かしても落ちない。</p>
<h3>この地区だけがカーネル空間にある</h3>
<p>街に1本だけ引かれている二重線がそれ。<strong>この地区の西の壁と東の壁が、ユーザ空間とカーネル空間の境界</strong>で、越え方が2回とも違う。</p>
<ul>
<li><strong>西の壁（01 → 02）</strong> — アプリがカーネルに<em>頼む</em>側。<code>execve</code> を呼ぶのはアプリで、これは全員が必ず通る道。だから<span class="mark">迂回できない</span></li>
<li><strong>東の壁（02 → 03）</strong> — カーネルがユーザ空間に<em>渡す</em>側。渡し場は共有メモリのリングバッファひとつだけで、<span class="mark">この模型で唯一イベントが落ちる場所</span>がそこ（03）。渡し損ねたら消える</li>
</ul>
<p>この2枚の壁が、パイプライン全体のほぼすべての設計判断の理由になっている。<code>base_syscalls</code> が<strong>カーネル側の</strong>安いフィルタなのは、東の壁を越える前に捨てられるから。<code>buf_size_preset</code> と <code>cpus_for_each_buffer</code> が効くのは、東の壁の渡し場の寸法だから。</p>
<p><code>nodriver</code> のときこの地区は空になり、東の壁が切れる。<span class="mark">syscall というソースが消えたのではなく、カーネル→ユーザ空間の渡し場が無い</span>。プラグイン入力は最初からこの壁を通らないので、まったく影響を受けない。</p>
<h3>ここが一番安いフィルタ</h3>
<p>ドライバは <code>sys_enter</code> / <code>sys_exit</code> / <code>sched_process_exit</code> などの tracepoint にアタッチし、<span class="mark">関心のある syscall だけ</span>を選んでリングバッファへ流す。関係ない大量の syscall はここで捨てる。</p>
<p>この「捨てる場所がカーネル内である」ことが性能の核心。ユーザ空間まで運んでから捨てるのは、運ぶコストを丸ごと払うのと同じ。</p>
<div class="takeaway"><span class="cv">▸</span>安いフィルタを一番手前に置く。これが低オーバーヘッドの正体。</div>`
  },
  {
    id:'ring', n:'03', tag:'RING BUFFER',
    hoverT:'RING BUFFERS', hoverS:'カーネルが書き、ユーザ空間が読む共有メモリ',
    hoverM:['既定 8 MiB × ceil(nCPU ÷ 2) 本','唯一「落ちる」場所 — n_drops'],
    jp:'リングバッファ', en:'shared ring buffers',
    w:27, d:38, top:9, color:C.g30, cam:[-46,38,66],
    metrics:[['既定','1バッファ 8 MiB · 2 CPU で共有'],['危険信号','n_drops > 0']],
    body:`
<h3>唯一、イベントが失われる場所</h3>
<p>ドライバが選んだイベントは<strong>共有メモリのリングバッファ</strong>に書かれ、ユーザ空間がそれを時刻順に読む。カーネルは待たない。ユーザ空間の読み出しが追いつかなければ、<span class="mark">新しいイベントは静かに捨てられる</span>。</p>
<h3>「CPU ごとに1本」ではない（既定では）</h3>
<p>ここは間違えやすい。<strong><code>kmod</code> では CPU ごとだが、既定の <code>modern_ebpf</code> では CPU ペアごと</strong>。</p>
<ul>
<li><code>cpus_for_each_buffer</code> は <code>modern_ebpf</code> 専用で<strong>既定 2</strong> = 1つのバッファを 2 CPU で共有する（<code>1</code> で CPU ごと ＝ <code>ebpf</code> の既定、<code>0</code> で全オンライン CPU で1つ）</li>
<li>バッファ数は <span class="mark"><code>ceil(オンライン CPU 数 ÷ この値)</code></span>。falco.yaml のコメントが「CPU 7個・既定 2 → <strong>バッファ4個</strong>」を図で実演している</li>
<li><code>buf_size_preset</code> の 8 MiB は<strong>1バッファのサイズ</strong>。しかもバッファは仮想メモリに<strong>二重にマップ</strong>されるので、8 MiB のバッファは仮想メモリ上 <strong>16 MiB</strong> を占める</li>
<li>現行の設定キーは <code>engine.modern_ebpf.cpus_for_each_buffer</code> と <code>engine.&lt;engine&gt;.buf_size_preset</code>。右の TUNING パネルもこの名前で出している</li>
</ul>
<h3>この地区は「レーン ＝ CPU」「囲い ＝ バッファ」で描いてある</h3>
<p>溝が1本＝<strong>CPU 1個</strong>。その上に被さっている囲いが<strong>リングバッファ1本</strong>で、<span class="mark">何本の溝を1つの囲いがまとめているかが <code>cpus_for_each_buffer</code></span>。だから TUNING でその値を動かすと、溝の数は変わらないまま囲いの数だけが変わる。既定 2 で 8 vCPU なら囲いは4つ。<code>1</code> にすれば8つ、<code>4</code> にすれば2つ。</p>
<p>そして <code>?cpus=2</code> のような2 vCPU のノードでは溝が2本しか出ない。既定 2 のままだと囲いは <code>ceil(2÷2) = 1</code> ——<strong>バッファが1本</strong>になる。8 vCPU のノードで4本あったものが1本になるのは、ノードを増やしたからではなく<em>ノードが小さくなったから</em>。</p>
<p>つまりこの地区は<strong>ノード数ではなく CPU 数</strong>の話をしている。ノードを増やして増えるのは DaemonSet の Pod の数で、溢れているノードの中の囲いは1つも増えない。</p>
<p>パイプライン全体で、イベントが本当に消えるのはここだけ。だから運用では真っ先にこの数字を見る。</p>
<h3>ドロップを「見なかったことにしない」</h3>
<p>Falco はドロップ自体を扱える。<code>syscall_event_drops</code> の設定で <code>ignore</code> / <code>log</code> / <code>alert</code> / <code>exit</code> を選べる。検知基盤が黙って盲目になるより、鳴らして気づくほうが正しい。</p>
<ul>
<li>バッファサイズは <code>buf_size_preset</code> で調整（既定 preset 4 = 1バッファ 8 MiB）</li>
<li>ドロップが続くなら、まず <strong>入口を絞る</strong>（不要な syscall を落とす）。バッファを増やすのは次の手</li>
<li>ノード負荷スライダを上げると、右の <em>event drops</em> が増えるのが見える</li>
</ul>
<div class="takeaway"><span class="cv">▸</span>ドロップ率を見ていない検知基盤は、静かに嘘をつく。</div>`
  },
  {
    id:'state', n:'04', tag:'STATE ENGINE (libsinsp)',
    hoverT:'libscap / libsinsp — STATE ENGINE', hoverS:'生の syscall に文脈を貼り、意味のあるイベントに変える',
    hoverM:['thread table · fd table','container / k8s metadata'],
    jp:'状態エンジン', en:'libscap / libsinsp',
    w:25, d:42, top:22, color:0x9AD9E8, cam:[8,42,72],
    metrics:[['thread table','pid/exe/args/uid/親子'],['fd table','fd → path / socket']],
    body:`
<h3>「fd=7 に write した」を意味に変える</h3>
<p>生の syscall だけでは何も言えない。<code>write(7, ...)</code> は 7 が何なのか知らない。ここで <strong>libsinsp</strong> が状態を持って文脈を貼る。</p>
<ul>
<li><strong>スレッドテーブル</strong> — pid / tid / comm / exe / args / cwd / uid / loginuid、そして親子チェーン（<code>proc.pname</code>, <code>proc.aname[2]</code>）</li>
<li><strong>FD テーブル</strong> — fd 番号 → ファイルパスやソケット（<code>fd.name</code>, <code>fd.sip</code>）</li>
<li><strong>コンテナメタデータ</strong> — <code>container</code> プラグインが<span class="mark">コンテナランタイムのソケット</span>から取る。<code>container.name</code> / <code>container.image.repository</code> ほか約28フィールド</li>
<li><strong>Kubernetes メタデータ</strong> — <strong>2系統ある</strong>（次節）</li>
</ul>
<p>この層があるから、はじめて <span class="mark">「payments 名前空間の nginx コンテナの中で、root が /etc/shadow を読んだ」</span> と言える。ルールが人間の言葉で書けるのは、ここが下支えしているから。</p>
<h3>k8s メタデータのガントリーは2本ある</h3>
<p>ここは間違えやすい。Kubernetes のフィールドは<strong>出どころが2つに分かれている</strong>。</p>
<ul>
<li><strong>ランタイム由来（ソケット）</strong> — <code>k8s.ns.name</code> / <code>k8s.pod.name</code> / <code>k8s.pod.uid</code> / <code>k8s.pod.label[*]</code> / <code>k8s.pod.ip</code> など。コンテナランタイムが「このコンテナはどの Pod のものか」を知っているので付く。<span class="mark">ソケットに届かなければ、この系統ごと消える</span></li>
<li><strong>API サーバ由来（k8smeta プラグイン）</strong> — <code>k8smeta.deployment.name</code> など。Falco 0.37 で本体の k8s クライアントが廃止され、<code>k8smeta</code> プラグイン ＋ <code>k8s-metacollector</code>（experimental）に分離された。非推奨になった <code>k8s.deployment.name</code> / <code>k8s.rs.name</code> / <code>k8s.svc.name</code> / <code>k8s.rc.name</code> は<span class="mark">ルールで使うと <code>&lt;NA&gt;</code></span></li>
</ul>
<p>ソケットが死んでも残るのは <code>container.id</code> と <code>container.type</code> だけ。この2つは cgroup からカーネル内で決まるので、ソケットを必要としない。</p>
<p>逆に <code>k8s.pod.name</code> が Falco 0.37 の廃止を生き延びたのは、<span class="mark">出どころが API サーバではなくコンテナランタイムだから</span>。同じ「k8s.」で始まるのに寿命が違う理由がこれ。</p>
<h3>コストの正体</h3>
<p>この状態管理がメモリを使う。プロセスが激しく生成消滅する環境ではスレッドテーブルが膨らむ。「Falco が重い」と言われるとき、犯人はドライバではなくここか、次のルール層のことが多い。</p>
<div class="takeaway"><span class="cv">▸</span>検知の質は、貼れる文脈の量で決まる。文脈のない syscall は騒音。</div>`
  },
  {
    id:'rules', n:'05', tag:'RULES ENGINE',
    hoverT:'FALCO RULES ENGINE', hoverS:'condition + output + priority。イベント型ごとに評価対象を絞る',
    hoverM:['rules · macros · lists','per-event-type ruleset bitmask'],
    jp:'ルールエンジン', en:'falco rules engine',
    w:23, d:42, top:26, color:0xD9C0E4, cam:[46,44,72],
    metrics:[['ルール定義','condition / output / priority / tags'],['優先度','EMERGENCY … DEBUG']],
    body:`
<h3>ルールは3つの部品でできている</h3>
<p><code>falco_rules.yaml</code> と自前のルールが読み込まれる。1つのルールは <strong>condition</strong>（フィルタ式）、<strong>output</strong>（鳴ったときに何を言うか）、<strong>priority</strong>、<strong>tags</strong>。共通部分は <code>macro</code> と <code>list</code> に切り出して再利用する。</p>
<h3>なぜ数百ルールでも回るのか</h3>
<p>素朴に作れば「イベント1件 × 全ルール」で総当たりになる。Falco は <span class="mark">イベント種別ごとに評価すべきルールの集合を事前計算</span>しておく。<code>execve</code> が来たら <code>execve</code> に関係するルールだけを触る。これが効くから、ルールを増やしても線形に重くならない。</p>
<h3>例外は宣言的に書く</h3>
<p>誤検知を潰すとき、条件式に <code>and not (...)</code> を足し続けると読めなくなる。<code>exceptions</code> フィールドで「この組み合わせは除く」を構造として書く。ルールの意図と例外を分けて残せる。</p>
<ul>
<li>優先度: EMERGENCY / ALERT / CRITICAL / ERROR / WARNING / NOTICE / INFO / DEBUG</li>
<li><code>output</code> のフィールドは前段の状態エンジンが埋める。書けるフィールドは前の層の能力そのもの</li>
<li>マッチしなかったイベントはここで消える。全 syscall のうち鳴るのはごく一部</li>
</ul>
<div class="takeaway"><span class="cv">▸</span>ルールは「悪いことのリスト」ではなく「普通ではない振る舞いの定義」。</div>`
  },
  {
    id:'outputs', n:'06', tag:'OUTPUTS',
    hoverT:'OUTPUT CHANNELS', hoverS:'stdout / file / syslog / program / http / gRPC',
    hoverM:['Falcosidekick → 多数の宛先','Falco Talon → 自動応答'],
    jp:'出力チャネル', en:'outputs / falcosidekick / talon',
    w:19, d:34, top:16, color:C.lumin, cam:[86,38,58],
    metrics:[['ネイティブ','stdout / file / syslog / program / http / gRPC'],['実運用','Falcosidekick がハブ']],
    body:`
<h3>鳴った先をどう配るか</h3>
<p>Falco 本体の出力は <code>stdout</code> / <code>file</code> / <code>syslog</code> / <code>program</code> / <code>http</code>、そして <strong>gRPC Output API</strong>。ここまでは「アラートを吐く」だけ。</p>
<p>実運用のハブになるのは <strong>Falcosidekick</strong>。受けたアラートを Slack / Teams / Loki / Elasticsearch / Alertmanager / S3 / Kafka など多数の宛先へ扇形に配る。「検知を既存の運用に載せる」仕事はほぼここで終わる。</p>
<h3>見るだけで終わらせないなら</h3>
<p><strong>Falco Talon</strong> を挟むと、アラートを条件付きのアクションに繋げられる（Pod をラベルする、隔離する、止める）。<span class="mark">検知と応答は別のコンポーネント</span>であることに意味がある — 誤って止める怖さを、検知の設計と分けて調整できる。</p>
<h3>OSS の境界線</h3>
<p>ここが Falco OSS の終点。<em>この瞬間のアラート</em>は手に入る。持っていないのは、過去との突き合わせ・他のシグナルとの相関・組織横断の運用。それが右上の Sysdig レイヤの担当。</p>
<div class="takeaway"><span class="cv">▸</span>アラートを出すのは半分。届いて、判断され、行動に変わって初めて検知。</div>`
  },
  {
    id:'plugins', n:'07', tag:'PLUGIN INPUTS',
    /* NOT "bypass lane" any more. A bypass merges — that is what the word means
       and that is what the drawing was saying. Falco does not correlate across
       sources (INVARIANTS 3.9): the two lanes run in parallel into the SAME
       engine and land in DIFFERENT rulesets, and nothing crosses between them. */
    hoverT:'PLUGIN INPUTS — A SEPARATE SOURCE, IN PARALLEL',
    hoverS:'同じルールエンジンに入るが、syscall とは混ざらない',
    hoverM:['k8saudit · cloudtrail · gcpaudit','ct.* — 別のフィールド空間'],
    jp:'プラグイン入力', en:'plugin inputs — a separate source, running in parallel',
    /* wider and deeper than the rest of the north lane because the audit
       route lives here: an apiserver, a transport, and — on managed
       Kubernetes — a whole separate Deployment doing the collecting */
    /* No hand-picked camera any more. The old one sat south of the workloads
       district and looked north straight through it, and it could not follow
       the node count — this district's z is derived from how deep the
       workloads district got. layout.js derives an approach from the west for
       off-flow lanes, which follows the layout for free. */
    w:34, d:26, top:12, lane:'north', after:'workloads', dx:-2, color:0xF3C99A,
    metrics:[['入力側','k8saudit / cloudtrail / gcpaudit / okta / github'],['共通点','同じルール言語で書ける']],
    body:`
<h3>カーネルの外の出来事も同じ言語で</h3>
<p>Falco の入力は syscall だけではない。<strong>プラグイン</strong>がイベントソースを増やす — <code>k8saudit</code>（Kubernetes 監査ログ）、<code>cloudtrail</code>、<code>gcpaudit</code>、<code>okta</code>、<code>github</code>、汎用の <code>json</code>。</p>
<p>重要なのは、これらが <span class="mark">同じルールエンジンに入る</span>こと。「特権 Pod が作られた」「S3 バケットが公開された」「管理者ロールが付与された」を、syscall 検知と同じ書き方・同じ出力経路で扱える。</p>
<p><strong>ただし「合流」ではない。</strong>05 ルールエンジンの中に仕切りが1枚立っていて、この道の先はその北側の区画にしか入らない。<span class="mark">並走して同じエンジンに入るが、混ざらない</span>（詳しくは下の「ソース間の相関はしない」）。</p>
<h3>この道はドライバを通らない</h3>
<p>プラグイン入力はカーネルのドライバもリングバッファも経由しない。だから <strong>ドライバなしで Falco を動かす</strong>構成も成り立つ（<code>nodriver</code>）。クラウド側のイベントだけを見る使い方。</p>
<ul>
<li>入力プラグインは1プロセスに1つが基本。用途ごとに Falco を分けて動かす構成が実務的</li>
<li>抽出（extractor）プラグインを足すと、既存イベントから新しいフィールドを引ける</li>
</ul>
<h3>監査ログの「取り方」で街の形が変わる</h3>
<p><code>k8saudit</code> は Kubernetes の監査ログを読む。<span class="mark">問題はどうやって手に入れるか</span>で、ここがオーケストレータ軸の正体。</p>
<ul>
<li><strong>self-managed</strong> — apiserver の監査 webhook を Falco に向けられる。syscall を見ている<em>その</em> Falco がそのまま受けるので、監査用の別インスタンスは要らない</li>
<li><strong>managed</strong> — apiserver の起動オプションを触れないので webhook が張れない。プロバイダ別プラグインが<span class="mark">ログの置き場から pull する</span> — EKS は CloudWatch Logs、AKS は Event Hub、GKE は Pub/Sub</li>
</ul>
<h3>EKS だけは単一インスタンス</h3>
<p><code>k8saudit-eks</code> は CloudWatch Logs から pull するので、<strong>2つ動かすと同じログを二重に取り、アラートが重複する</strong>。公式 Helm 値がそのまま答えになっている — <code>controller.kind: deployment</code> / <code>replicas: 1</code> / <code>driver.enabled: false</code> / <code>collectors.enabled: false</code>。</p>
<p>つまり EKS の監査経路では <span class="mark">DaemonSet ではなく replicas 1 の Deployment が建ち、そこはドライバもコレクタも無効</span>。ノード上の DaemonSet とは<strong>別の建物</strong>で、役割も違う。DEPLOY で EKS を選ぶと、この地区にその1棟が建つ。</p>
<p><strong>GKE に一般化してはいけない。</strong>Pub/Sub の exactly-once 配信を使うので、単一リージョン内なら複数インスタンスが明示的に許されている。AKS には単一インスタンスの注意書きが無いので、この模型でも主張しない。</p>
<h3>ソース間の相関はしない</h3>
<p>ルールは<strong>イベントソースごとに分割</strong>される。1つのルールは <code>source</code> を1つしか持てない（既定 <code>syscall</code>）。<code>aws_cloudtrail</code> は <code>ct.*</code> という<strong>別のフィールド空間</strong>を持つ別ソースで、<span class="mark">Falco はソース間の相関をしない</span>。</p>
<p>だから「クラウド API の操作が syscall ルールに当たる」ことは<strong>原理的に起きない</strong>。ルールを何本足しても、負荷をいくら下げても、ドロップを 0% にしても起きない。<span class="mark">量の問題ではなく、分割の問題</span>。05 の仕切りに × が描いてあるのはそれで、あの線を越える矢印はこの街に1本も無い。</p>
<p>そして逆向きにも効く。別ソースなので<strong>カーネル経路の有無と独立に成立する</strong> — <code>nodriver</code> でもクラウド側の検知は取れる。これはドライバの有無とは無関係な、もっと強い理由。</p>
<div class="takeaway"><span class="cv">▸</span>検知の言語をひとつに揃えると、運用が増えても複雑さが増えない。ただし言語が同じことと、突き合わせられることは別。</div>`
  },
  {
    id:'sysdig', n:'08', tag:'SYSDIG SECURE', floating:true,
    hoverT:'SYSDIG SECURE — PLATFORM LAYER', hoverS:'同じ libs・同じ Falco エンジン。違いは周辺にある',
    hoverM:['policies ↓ · events + captures ↑','runtime insights で相関'],
    jp:'Sysdig Secure', en:'platform layer — commercial',
    w:46, d:32, top:8, y:31, lane:'north', after:'outputs', dx:-6, color:C.deepSee, cam:[104,62,10],
    metrics:[['エンジン','Falco と同一（Sysdig が作った）'],['付加価値','記憶・相関・手']],
    body:`
<h3>エンジンは同じ。違うのは周辺</h3>
<p>Sysdig エージェントは <strong>同じ libs（libscap / libsinsp）と同じ Falco エンジン</strong>を内蔵している。Falco はもともと Sysdig が作って CNCF に寄贈した。だから検知の芯は変わらない。差は、その周りに何があるか。</p>
<h3>いまの構成は2コンポーネント（Sysdig Shield）</h3>
<p>Classic Agent 方式を置き換える形で、導入は <strong>Host Shield</strong> と <strong>Cluster Shield</strong> の2つに集約されている。ドライバは Universal eBPF（Linux 5.8+ 推奨）/ kmod（旧カーネル）/ Legacy eBPF（非推奨）。</p>
<h3>中身は7つ。そして<span class="mark">検知は1つも増えない</span></h3>
<p>「Sysdig を入れると何が付いてくるのか」は数えられる。街ではこう描き分けてある。</p>
<ul>
<li><strong>□ 中空の枠 ＋ 既存地区への矢印</strong> — <span class="mark">この都市がもう持っている仕事を、運用ごと引き取る</span>もの。建物は建たない</li>
<li><strong>■ 実体のある建物</strong> — この都市に地区が1つも無かった仕事。<em>そこだけが増える</em></li>
</ul>
<p><strong>Host Shield（ノード単位・K8s では DaemonSet、単体ホストではパッケージ／コンテナ）</strong></p>
<ul>
<li>□ <strong>Runtime Threat Detection</strong> → 02〜06。<span class="mark">同じ libs・同じ Falco エンジン</span>なので、検知は1段も増えない。増えるのは、ノードごとに YAML を配る運用から降りられることだけ</li>
<li>■ <strong>Host Vulnerability Scanning</strong> — ホストのパッケージを定期スキャン</li>
<li>■ <strong>KSPM for Hosts</strong> — ホスト設定をコンプライアンスポリシーに照らす</li>
<li>■ <strong>Rapid Response</strong> — 指定した担当者がリモートシェルで調査できる</li>
</ul>
<p><strong>Cluster Shield（クラスタ単位で <em>1つ</em>・Deployment）</strong></p>
<ul>
<li>■ <strong>Container Vulnerability Scanning</strong>（<code>container_vulnerability_management</code>）</li>
<li>□ <strong>Kubernetes Audit Threat Detection</strong>（<code>audit</code>）→ 07。k8saudit と<strong>同じ入力・同じルール言語</strong>。ここも検知は増えず、取得経路と運用が移る</li>
<li>■ <strong>KSPM for Clusters</strong>（<code>posture</code>）</li>
<li>■ <code>admission_control</code> — 入る前に止める。設定4区画のうちの1つ</li>
</ul>
<p>数えると <strong>■ が5つ、□ が2つ</strong>。<span class="mark">脆弱性・姿勢・応答が増え、検知は増えない</span> — これが「買うか建てるか」の実際の中身。</p>
<p>そして <strong>単体ホスト構成では Cluster Shield は存在しない</strong>（守るクラスタが無い）。DEPLOY を <code>スタンドアロン</code> にすると、上の4つが街から消える。DEPLOY を切り替えるとこの2つの箱が出たり消えたりするのは、それが実際の配置単位だから。</p>
<h3>降りてくるもの — ポリシー</h3>
<ul>
<li>マネージドルールと Sysdig TRT（Threat Research Team）由来の脅威コンテンツが継続的に降りてくる</li>
<li>ゾーン単位でポリシーを当てられる（本番と開発で違う厳しさ、を組織構造のまま表現できる）</li>
<li>チューニングの結果が全ノードに配られる。ノードごとに YAML を配る運用から降りられる</li>
</ul>
<h3>上がるもの — イベント・監査・録画</h3>
<ul>
<li>検知イベントに加えて <strong>Activity Audit</strong>（コマンド・ファイル・ネットワーク・kubectl exec の履歴）</li>
<li><strong>キャプチャ（.scap）</strong> — 前後の syscall を丸ごと残す。事後に「何が起きたか」を再生できる</li>
</ul>
<h3>相関 — ここが一番大きい差</h3>
<p><strong>Runtime Insights</strong> は「実行中に実際に使われているパッケージ」を知っている。だから脆弱性の山を <span class="mark">in-use のものだけ</span>に絞れる。同じ CVE でも、動いていないライブラリのそれは後回しにできる。Posture / CIEM / Identity と突き合わせて「実際に到達可能で、権限があり、動いている」ものを前に出す。</p>
<h3>手 — 応答</h3>
<p>コンテナの kill / pause、Sysdig Sage による説明。検知から封じ込めまでを同じ文脈の中で行える。</p>
<div class="takeaway"><span class="cv">▸</span>OSS Falco は目。Sysdig は目 + 記憶 + 相関 + 手。芯は同じものを共有している。</div>`
  },
  {
    id:'falcoctl', n:'09', tag:'RULE DISTRIBUTION',
    hoverT:'falcoctl — RULE & PLUGIN DISTRIBUTION',
    hoverS:'ルールとプラグインは OCI アーティファクトとして配られる',
    hoverM:['stable / incubating / sandbox','同梱されるのは stable だけ'],
    jp:'ルール配布', en:'falcoctl — oci artifacts',
    /* 20×16 held three crates you could not see inside. The three rule FILES
       are the content of this district (§1a-4), so it needs room for three
       crates big enough to be open or shut and to carry their own count.
       24×22 fits them in a column with the registry beside them, and it stays
       clear of the Sysdig deck (x1 = 55 against sysdig's x0 = 60). */
    w:24, d:22, top:14, lane:'north', after:'rules', dx:-4, color:0xC9AEDA,
    metrics:[['配布形式','OCI アーティファクト'],['同梱','falco_rules.yaml（stable 25本）のみ']],
    body:`
<h3>ルールはイメージに焼かない</h3>
<p>Falco のルールとプラグインは <strong>OCI アーティファクト</strong>としてレジストリから配られ、<code>falcoctl</code> が取得と更新を担う。<span class="mark">ルールを更新するために Falco を再デプロイしなくていい</span>、というのがここの意味。</p>
<h3>成熟度は<strong>フラグではなくファイル</strong></h3>
<p>ここは間違えやすい。「既定で入っているか」はルールに付いた属性ではなく、<span class="mark">どのファイルを取得したか</span>。<code>falcosecurity/rules</code> は成熟度とファイルが <strong>1:1</strong> に分かれていて、incubating のルールは <code>falco_rules.yaml</code> に1本も無い。</p>
<ul>
<li><strong>stable</strong> — <code>falco_rules.yaml</code> · <strong>25本</strong>。<span class="mark">リリースパッケージに同梱されるのはこのファイルだけ</span></li>
<li><strong>incubating</strong> — <code>falco-incubating_rules.yaml</code> · <strong>31本</strong>。別の OCI アーティファクト（<code>falco-incubating-rules</code>）。一定の堅牢性はあるが用途がより限定的</li>
<li><strong>sandbox</strong> — <code>falco-sandbox_rules.yaml</code> · <strong>37本</strong>。別の OCI アーティファクト。より実験的</li>
</ul>
<p>だからこの地区には<strong>箱が3つ並んでいて、開いているのは1つだけ</strong>。開いている箱の中に見えている25個が、あなたが何もしなくても持っているルールの全部。<span class="mark">残りの68本は、封のしてある2つの箱の中にある</span>。</p>
<p>「Falco の既定ルールは思ったより少ない」と感じたら、それは stable しか入っていないから。incubating を足すかどうかは、誤検知をどこまで引き受けるかの判断になる（開けた分だけ 05 に流れるルールが増え、その分アラートも増える）。</p>
<p>（ほかに Deprecated がある。）</p>
<h3>Helm の3つのキーは別物</h3>
<ul>
<li><code>falcoctl.config.artifact.install.refs</code> — 起動時に<strong>取得</strong>するもの</li>
<li><code>falcoctl.config.artifact.follow.refs</code> — <strong>自動更新</strong>の対象にするもの</li>
<li><code>falco.rules_files</code> — エンジンが実際に<strong>読み込む</strong>もの</li>
</ul>
<p>取得しただけでは読み込まれない。読み込んでいても follow に入れていなければ古いままになる。3つが揃っていないと「入れたはずのルールが効いていない」が起きる。</p>
<h3>Sysdig の場合</h3>
<p>同じ役割を backend が担う。マネージドルールと Sysdig TRT の脅威コンテンツがポリシーとして降りてくるので、この地区の仕事は Sysdig Secure 側に移る。STACK を切り替えると、ルールの流れの出どころがこの地区から上空のプラットフォームに変わる。</p>
<div class="takeaway"><span class="cv">▸</span>ルールは成果物。バージョンがあり、配布経路があり、更新戦略が要る。</div>`
  }
];

export {
  DISTRICTS,
  DEPLOYMENTS,
  byDeployId,
  ORCH,
  NODE_OSES,
  SOCKETS,
  K8S_METAS,
  DRIVERS,
  TOPOLOGIES,
  ENV_AXES,
  ENV_SEL,
  SHIELDS,
  shieldById,
  RULE_FILES,
  setRuleFiles,
  loadedRuleFiles,
  loadedRuleCount,
  DEPLOY_PRESETS,
  composeEnv,
  currentEnv,
  setEnvAxis,
  byTopologyId,
  nodeCount,
  CLUSTER_NODES,
  setClusterNodes,
  CPU_MAX,
  NODE_CPUS,
  nodeCpus,
  setNodeCpus,
  bufferCount,
  MAX_NODES,
  NODE_MAX,
  NODE_PITCH,
  NODE_MARGIN,
  NODE_PAD_W,
  NODE_PAD_D,
  POD_PITCH,
  nodeOffsets,
  workloadsDepth
};
