/* Generated by the module split. See README §開発の分担. */
import { C } from './palette.js';
import { currentEnv } from './districts.data.js';
import { S, GAME } from './state.js';
import { PRIO, spawn, N } from './sim.js';


/* ============================================================
   10. console log lines (real Falco rule names)
   ------------------------------------------------------------
     [0] rule name
     [1] priority index into PRIO
     [2] the output fields the rule itself prints
     [3] plugin event source, if it is not a syscall rule. These are the only
         rules that can fire with no kernel path
     [4] RULE MATURITY: 'incubating' | 'sandbox'. Absent means stable.
     [5] a capability the ENVIRONMENT has to have for the behaviour to be
         possible at all — a key on currentEnv(). Absent means none.

   [5] is why `Contact K8S API Server From Container` now names `apiServer`. On
   the `standalone` preset the scoreboard says, in words, that there is no
   Kubernetes API server here so "this behaviour cannot occur" — and the console
   two panels away was printing that exact rule. `[3]` only gated the PLUGIN
   sources, so a syscall rule written on a Kubernetes premise had nothing
   stopping it.

   ---------------------------------------------------------------- §maturity
   [4] used to be "a district that must be standing", and the only rule carrying
   it was `Drop and execute new binary in container`, pinned to 09 ルール配布.
   That was backwards in both directions, and the console was contradicting the
   scoreboard in the same frame:

     - `Drop and execute new binary in container` is tagged `maturity_stable`,
       so it IS in the release package and falcoctl has nothing to do with it.
       INVARIANTS 4.3 records the same error against campaign.js's CHAIN step.
     - meanwhile five genuinely non-stable rules had no gate at all and printed
       freely. Measured in `inherited-all-syscalls` with 09 unbuilt: `Non sudo
       setuid` (incubating) and `Detect crypto miners using the Stratum
       protocol` (sandbox) reached this console while the panel beside it was
       scoring the player as not having them.

   The fact, once: the rules ship in three files and file maps 1:1 to maturity —
   `falco_rules.yaml` (stable, 25) / `falco-incubating_rules.yaml` (31) /
   `falco-sandbox_rules.yaml` (37) — and only the stable set is loaded by
   default. incubating and sandbox are separate OCI artifacts, which is exactly
   what 09 ルール配布 (falcoctl) is. So the gate is not a per-rule district any
   more; it is derived from the maturity tag, in one line, below.

   campaign.js states the same fact on its CHAIN steps and has to state it twice
   for now, because log.js cannot import campaign.js — campaign.js →
   controls.js → log.js already, so the import would close a cycle and ui.js's
   module body would run against a half-initialised campaign.js.
   ============================================================ */
const RULES_LOG = [
  ['Terminal shell in container', 2, 'user=root shell=bash parent=containerd-shim'],
  /* stable, so it needs no artifact — see §maturity and INVARIANTS 4.3 */
  ['Drop and execute new binary in container', 0, 'exe=/tmp/.x parent=sh'],
  ['Read sensitive file untrusted', 1, 'file=/etc/shadow proc=cat'],
  ['Write below etc', 1, 'file=/etc/cron.d/pwn proc=sh', null, 'sandbox'],
  ['Contact K8S API Server From Container', 2, 'connection=10.0.0.1:443 proc=curl',
   null, null, 'apiServer'],
  /* the incubating example the attack chain's step 4 becomes (INVARIANTS 4.5):
     credential theft from the instance metadata service. Real, and genuinely
     not in the release package — which is what step 4 was claiming all along */
  ['Contact EC2 Instance Metadata Service From Container', 1,
   'connection=169.254.169.254:80 proc=curl', null, 'incubating'],
  ['Launch Privileged Container', 2, 'image=nginx:latest privileged=true'],
  ['Detect crypto miners using the Stratum protocol', 0, 'proc=xmrig port=3333',
   null, 'sandbox'],
  ['Redirect STDOUT/STDIN to Network Connection in Container', 1, 'proc=bash fd=3'],
  ['Sudo Potential Privilege Escalation', 1, 'proc=sudoedit user=app'],
  ['Packet socket created in container', 3, 'proc=tcpdump'],
  ['Clear Log Activities', 1, 'file=/var/log/auth.log proc=shred', null, 'incubating'],
  ['Search Private Keys or Passwords', 2, 'proc=grep args=-r BEGIN RSA'],
  ['Change thread namespace', 3, 'proc=nsenter', null, 'incubating'],
  ['Non sudo setuid', 2, 'proc=node uid=0', null, 'incubating'],
  /* 4th element = plugin event source (not syscalls) → no syscall-side k8s.pod
     suffix, and these are the ONLY rules that can fire in kernel-less mode */
  ['K8s Secret Get Successfully', 2, 'ka.user=svc/deployer ka.target.name=db-creds ka.target.namespace=payments', 'k8saudit'],
  ['Create Privileged Pod', 0, 'ka.user=svc/ci ka.target.name=debug-pod ka.target.namespace=payments', 'k8saudit'],
  ['Attach/Exec Pod', 2, 'ka.user=alice@corp ka.target.name=api-7f9c ka.target.namespace=payments', 'k8saudit'],
  ['ClusterRole With Write Privileges Created', 1, 'ka.user=svc/ci ka.target.name=edit-all', 'k8saudit'],
  ['Console Login Without MFA', 1, 'aws.user=ops-admin aws.region=ap-northeast-1 mfa=false', 'cloudtrail'],
  ['Delete Bucket Encryption', 0, 'aws.user=svc/deploy aws.bucket=prod-artifacts', 'cloudtrail'],
  ['Put Bucket ACL Public Read/Write', 0, 'aws.user=svc/deploy aws.bucket=prod-logs acl=public-read-write', 'cloudtrail'],
  ['CloudTrail Trail Deleted', 0, 'aws.user=root aws.region=us-east-1 trail=org-trail', 'cloudtrail'],
  ['Okta User Account Locked', 3, 'okta.actor=bob@corp okta.attempts=8', 'okta'],
  ['Github Secret Pushed', 1, 'github.repo=corp/api github.user=carol type=aws_key', 'github']
];
const NS = ['payments','checkout','default','kube-system','ingress','data-eng'];
const PODS = ['api-7f9c','worker-2b1','nginx-5dd','etl-9ac','auth-3e8','cache-c17'];

const clog = document.getElementById('clog');
let logCooldown = 0, logQueue = [], dropCool = 0;
const metaQueue = [];          // falco's own messages (drops, exit, restart)

function nowTs(){
  const n = new Date();
  return `${String(n.getHours()).padStart(2,'0')}:${String(n.getMinutes()).padStart(2,'0')}`
       + `:${String(n.getSeconds()).padStart(2,'0')}.${String(n.getMilliseconds()).padStart(3,'0')}`;
}
function appendLine(html){
  const el = document.createElement('div');
  el.innerHTML = html;
  clog.appendChild(el);
  while(clog.children.length > 26) clog.removeChild(clog.firstChild);
}

/* ---------- the console belongs to the situation you are standing in ----------
   A scenario is a claim about what this estate can and cannot see, and the
   console is the evidence for it. Carrying the previous scenario's lines across
   the switch makes the new scenario's premise false on arrival: entering
   `a-different-source` — whose whole point is that the cloud side never rings —
   showed six leftover cloud alerts from the run before. The model was right and
   the screen was lying, which is the worse of the two.

   So the console is emptied when the situation changes. Everything in flight
   goes with it: a line already in the queue was matched against the OLD estate,
   so printing it after the switch would reintroduce exactly the same lie one
   tick later. ui.js calls this on `scenario` and on `mode`, because it is the
   module that hears the campaign feed — log.js cannot import campaign.js
   (campaign.js → controls.js → log.js would close the cycle). */
function resetLog(){
  while(clog.firstChild) clog.removeChild(clog.firstChild);
  logQueue.length = 0;
  metaQueue.length = 0;
  logCooldown = 0;
  dropCool = 0;
}

/* syscall_event_drops.actions — the point being that `ignore` is a choice
   to be blind, and `exit` is a choice to fail loudly rather than silently. */
function onDrop(){
  const act = S.tune.dropAction;
  if(act === 'ignore') return;
  S.deadDrops++;
  if(act === 'exit' && !S.dead && S.deadDrops >= 15){ die(); return; }
  if(dropCool > 0) return;
  dropCool = 2.2;
  const n = S.counters.drop;
  if(act === 'log')
    metaQueue.push({cls:'kv', text:`falco: ${n} syscall event drops so far (actions: log)`});
  else
    metaQueue.push({cls:'p-err', text:`Critical Falco internal: syscall event drops — ${n} events lost (actions: alert)`});
}
function die(){
  S.dead = true;
  metaQueue.push({cls:'p-err',
    text:'falco: too many consecutive syscall event drops — actions: exit → agent stopped. 検知は止まりました。'});
}
function revive(){
  if(!S.dead) return;
  S.dead = false; S.deadDrops = 0;
  for(let i=0;i<N;i++) spawn(i, Math.random()*1.6);
  metaQueue.push({cls:'sys', text:'falco restarted — detection resumed'});
}

/* ---------- what a syscall-derived line can actually say ----------
   The output fields a rule can print are exactly the enrichment the state
   engine managed to attach, so this is the most honest place in the model to
   show the four axes doing their work. Three independent sources:

     cgroup          container.id / container.type. Always. No socket needed
     runtime socket  the rest of container.*, and — in Kubernetes — the pod
                     fields, because the runtime knows which pod is which
     k8smeta plugin  the workload names, from the API server. Without it the
                     deprecated k8s.deployment.name family reads <NA>, which
                     is worse than missing: the rule looks like it works    */
const DEPLOYS = ['api','worker','nginx','etl','auth','cache'];
const hexId = () => (0x100000+((Math.random()*0xefffff)|0)).toString(16);

function enrich(env){
  const ns   = NS[(Math.random()*NS.length)|0];
  const pod  = PODS[(Math.random()*PODS.length)|0];
  const bits = [];

  if(env.containerFields.length > 2)
    bits.push(`container.name=${pod.split('-')[0]}`,
              `container.image.repository=corp/${pod.split('-')[0]}`);
  else
    bits.push(`container.id=${hexId()}`, 'container.type=containerd');

  if(env.podFields.length) bits.push(`k8s.ns.name=${ns}`, `k8s.pod.name=${pod}`);

  /* only claim a workload name where there is a cluster to have one */
  if(env.cluster){
    if(env.k8sMeta) bits.push(`k8smeta.deployment.name=${DEPLOYS[(Math.random()*DEPLOYS.length)|0]}`);
    else            bits.push('k8s.deployment.name=&lt;NA&gt;');
  }
  return bits.join(' ');
}

/* ---------- what is standing, and therefore what can reach this console ----
   The console is 06 出力チャネル. A rule that has nowhere to be delivered does
   not appear in it, and a rule the node was never given does not exist. In
   explore mode everything is built, so this is the identity function.

   Reading GAME from state.js rather than campaign.js is deliberate: GAME is
   declared there, and importing campaign.js from here would close an import
   cycle (campaign.js → controls.js → log.js). */
const SYSCALL_PATH = ['driver','ring','state','rules','outputs'];
const PLUGIN_PATH  = ['plugins','rules','outputs'];
const built = k => !GAME.on || GAME.built.has(k);
/* Only the stable set ships in the release package; incubating and sandbox are
   separate OCI artifacts, which is what 09 ルール配布 IS. See §maturity. */
const NEEDS_ARTIFACT = {incubating:true, sandbox:true};
/* [3] chooses the lane that carries it, [4] says whether the node was ever given
   the rule, and [5] whether the environment can produce the behaviour */
const standing = r =>
  (r[3] ? PLUGIN_PATH : SYSCALL_PATH).every(built)
  && (!NEEDS_ARTIFACT[r[4]] || built('falcoctl'));

function emitLog(prio){
  if(logQueue.length > 6) return;
  logQueue.push(prio);
}
function flushLog(dt){
  logCooldown -= dt;
  dropCool -= dt;
  /* falco's own messages jump the queue — they are not rule matches */
  if(metaQueue.length){
    const m = metaQueue.shift();
    appendLine(`<span class="ts">${nowTs()}</span> <span class="${m.cls}">${m.text}</span>`);
  }
  if(logCooldown > 0 || !logQueue.length || S.dead) return;
  logCooldown = 0.42 + Math.random()*0.5;
  const prio = logQueue.shift();
  /* Which rules can fire at all, read off the composed environment rather than
     off an environment id. Two separate questions, and the correction is that
     they really are separate:

       no kernel path  →  no ring buffer, so only plugin sources deliver
       no audit route  →  there is no Kubernetes audit log to read. Note this
                          is about COLLECTION, not about how Falco was
                          installed: k8saudit fires perfectly well on a host,
                          and it fires under `nodriver` too                */
  const env = currentEnv();
  const pluginOnly = !env.kernelPath;
  const noAudit    = !env.audit;
  const ok = r => (!pluginOnly || !!r[3]) && !(noAudit && r[3] === 'k8saudit')
                && (!r[5] || !!env[r[5]])          /* [5]: the place must allow it */
                && standing(r);
  let pool = RULES_LOG.filter(r => r[1]===prio && ok(r));
  if(!pool.length) pool = RULES_LOG.filter(ok);
  /* No fallback past `ok` on purpose. It used to fall back to the whole table
     to guarantee a line, which is how a rule the player has not built yet
     reached the console and quietly contradicted the scenario. Nothing that
     cannot fire is allowed to print — if that means silence, silence is the
     honest answer, and the alert VOLUME is unchanged for everything that can
     fire (the queue and the cooldown are untouched). */
  if(!pool.length) return;
  const r = pool[(Math.random()*pool.length)|0];
  const ts = nowTs();
  const p = PRIO[r[1]];
  const ctx = r[3] ? r[2] : `${r[2]} ${enrich(env)}`;
  appendLine(`<span class="ts">${ts}</span> <span class="${p.cls}">${p.name}</span> ${r[0]} `+
             `<span class="kv">(${ctx})</span>`);
  if(S.mode==='sysdig' && Math.random()<0.3){
    appendLine(`<span class="ts">${ts}</span> <span class="sys">sysdig</span> `+
      `<span class="kv">policy=Sysdig Runtime Threat Detection · capture=stored · in-use CVE correlated</span>`);
  }
}

export {
  emitLog,
  flushLog,
  resetLog,
  onDrop,
  die,
  revive,
  appendLine,
  nowTs,
  metaQueue
};
