/* Generated by the module split. See README §開発の分担. */
import * as THREE from 'three';
import { DISTRICTS } from './layout.js';
import { S, GAME, setProfile, profile, setStage, resetProfile } from './state.js';
import { renderer, scene, camera, controls, homeView, homeCam, onResize,
         tickFlight, goHome, HOME_TGT } from './scene.js';
import { districtObjs, hitTargets } from './city.js';
import { RULE_BLOCKS, deployRefs } from './districts.build.js';
import { step, spawn, spawnPolicy, N, PN, P } from './sim.js';
import { flushLog } from './log.js';
import { updateTags, updateHud, drawMinimap, select, closeDrawer } from './ui.js';
import { setMode, setDeploy, onTuneChange } from './controls.js';
import { tickReveal, applyGameVisibility, setUiMode, evaluate, build, runAttack,
         setRole, setSide, blameOf, OWNER, roleReport,
         SCENARIOS, startScenario, activeScenario, activeEnv, activeChain,
         goalStatus, passResults, onCampaignChange } from './campaign.js';
import { initAudio, play, tickAudio, campaignAudio,
         setMuted, toggleMuted, setVolume, audioState } from './audio.js';
import * as save from './save.js';
import { SCENARIO_ERRORS } from './scenarios/index.js';
import { model } from './state.js';


/* ============================================================
   17. loop
   ============================================================ */
const clock = new THREE.Clock();
let mmT = 0;

function frame(){
  const dt = Math.min(0.05, clock.getDelta());

  tickFlight(dt);
  controls.update();

  step(dt);
  tickAudio(P);
  tickReveal(dt);
  flushLog(dt);
  updateTags();
  updateHud(dt);

  // pulse the matched rule blocks
  const tt = clock.elapsedTime;
  for(let i=0;i<RULE_BLOCKS.length;i++){
    const b = RULE_BLOCKS[i];
    const ph = Math.sin(tt*2.2 + i*1.7);
    b.material.opacity = 0.42 + Math.max(0,ph)*0.42*Math.min(1.4,S.load);
  }

  mmT += dt;
  if(mmT > 0.09){ drawMinimap(); mmT = 0; }

  renderer.render(scene, camera);
  requestAnimationFrame(frame);
}


/* manual-step hook — lets the sim be driven/inspected without rAF */
window.__city = {
  step, S, DISTRICTS, select, setMode,
  frames:0,
  pump(n=60, dt=1/60){ for(let i=0;i<n;i++){ step(dt); tickReveal(dt); flushLog(dt); updateHud(dt); } },
  GAME, evaluate, build, setUiMode, runAttack,
  setRole, setSide, blameOf, OWNER, roleReport,
  SCENARIOS, startScenario, activeScenario, activeEnv, activeChain, goalStatus,
  SCENARIO_ERRORS,
  setProfile, profile, setStage, resetProfile,
  model, onTune:onTuneChange, setDeploy, dbg:deployRefs,
  initAudio, play, setMuted, toggleMuted, setVolume, audioState,
  save,
  renderOnce(){ controls.update(); updateTags(); drawMinimap(); renderer.render(scene,camera); },
  homeCam,
  camDist(){ return camera.position.distanceTo(controls.target); },
  applyHome(){ onResize(); const h = homeView();
               camera.position.set(...h.pos); controls.target.copy(h.tgt);
               controls.update(); updateTags(); renderer.render(scene,camera); }
};

/* the sound layer listens to the same feed the campaign panel does, so it never
   needs its own hook into the rules. Muted by default — nothing is created
   until a real click reaches initAudio(). */
onCampaignChange(ev => campaignAudio(ev, GAME));

/* progress: save.js decides the shape, this decides when. Nothing about the
   run's internals is stored — only which scenario was cleared and how well.
   Both hooks are per-PASS, not per-wave, which is the distinction that matters
   now that an attack arrives in several waves:

     attack  fires once when a pass starts, so one pass is one attempt
     over    fires once when the last wave has banked, and carries the verdict

   and the score has to come from passResults(), which is cumulative across the
   waves of the pass. GAME.results is only ever the wave on screen — reading it
   here recorded 2-wave greenfield as 3/3 instead of 6/6. */
onCampaignChange(ev => {
  if(ev.type === 'scenario') save.beginScenario(ev.id);
  else if(ev.type === 'attack') save.noteAttempt(GAME.scenario);
  else if(ev.type === 'over' && ev.cleared){
    const sc = activeScenario();
    if(!sc) return;
    const det = passResults().filter(r => !r.response);
    save.recordClear(sc.id, {
      detect: det.filter(r => r.caught).length,
      of:     det.length,
      asks:   GAME.asks,
      dropPct: model().dropP * 100
    });
  }
});

/* init */
setMode('oss');
document.querySelector('#drvSeg button').click();
setDeploy('k8s');
onTuneChange();
applyGameVisibility();
drawMinimap();
frame();
setTimeout(()=> document.getElementById('loader').classList.add('gone'), 620);
setTimeout(()=> document.getElementById('hint').classList.add('gone'), 9000);
