/* Generated by the module split. See README §開発の分担. */
import * as THREE from 'three';
import { C } from './palette.js';


/* ============================================================
   3. mesh helpers
   ============================================================ */
/* Per-instance edge material on purpose: districts get dimmed independently,
   and a shared material would leak one district's opacity into all of them. */
const edgeMat = (color, opacity) =>
  new THREE.LineBasicMaterial({color:color ?? C.g30, transparent:true, opacity:opacity ?? 0.34});

function box(w,h,d,color,opacity=1,flat=false){
  const g = new THREE.BoxGeometry(w,h,d);
  const m = new THREE.MeshLambertMaterial({
    color, transparent:opacity<1, opacity,
    depthWrite:opacity>0.6, flatShading:flat
  });
  return new THREE.Mesh(g,m);
}
function edged(w,h,d,color,opacity,edgeColor){
  const grp = new THREE.Group();
  const mesh = box(w,h,d,color,opacity);
  grp.add(mesh);
  const el = new THREE.LineSegments(
    new THREE.EdgesGeometry(mesh.geometry),
    edgeColor!=null ? edgeMat(edgeColor, 0.5) : edgeMat()
  );
  grp.add(el);
  grp.userData.mesh = mesh;
  return grp;
}
function put(o,x,y,z){ o.position.set(x,y,z); return o; }

/* --- authoritative Sysdig chevron as a flat 3D shape --- */
function chevronShape(){
  const s = new THREE.Shape();
  const S = 1/336, cx = 100*S, cy = 168*S;
  const P = (x,y)=>[x*S-cx, (336-y)*S-cy];
  let p = P(113.302,190.691); s.moveTo(p[0],p[1]);
  p = P(0,303.994);      s.lineTo(p[0],p[1]);
  p = P(32.002,335.996); s.lineTo(p[0],p[1]);
  p = P(200,167.998);    s.lineTo(p[0],p[1]);
  p = P(32.002,0);       s.lineTo(p[0],p[1]);
  p = P(0,32.002);       s.lineTo(p[0],p[1]);
  p = P(113.302,145.304);s.lineTo(p[0],p[1]);
  const c1=P(125.861,157.863), c2=P(125.861,178.188), e=P(113.302,190.691);
  s.bezierCurveTo(c1[0],c1[1],c2[0],c2[1],e[0],e[1]);
  return s;
}
const CHEV_GEO = new THREE.ShapeGeometry(chevronShape());

function chevron(x,z,size,color,opacity,rotY=0){
  const m = new THREE.Mesh(CHEV_GEO, new THREE.MeshBasicMaterial({
    color, transparent:true, opacity, side:THREE.DoubleSide, depthWrite:false
  }));
  m.scale.setScalar(size);
  m.rotation.x = -Math.PI/2;
  m.rotation.z = -rotY;
  m.position.set(x, 0.07, z);
  return m;
}

/* --- canvas text → flat ground plane --- */
function textTexture(txt, {size=190, weight=700, color='#8A8C8E', mono=false, track=0}={}){
  const cv = document.createElement('canvas');
  const ctx = cv.getContext('2d');
  const font = `${weight} ${size}px ${mono?"'Share Tech Mono',monospace":"Poppins,sans-serif"}`;
  ctx.font = font;
  if(track) ctx.letterSpacing = `${track}px`;
  const w = Math.ceil(ctx.measureText(txt).width)+size*0.3;
  const h = Math.ceil(size*1.42);
  cv.width = Math.max(4,w); cv.height = h;
  const c2 = cv.getContext('2d');
  c2.font = font;
  if(track) c2.letterSpacing = `${track}px`;
  c2.fillStyle = color; c2.textBaseline='middle'; c2.textAlign='left';
  c2.fillText(txt, size*0.15, h/2);
  const t = new THREE.CanvasTexture(cv);
  t.anisotropy = 8; t.needsUpdate = true;
  return {tex:t, aspect:cv.width/cv.height};
}
function groundText(txt, x, z, height, opts={}){
  const {tex,aspect} = textTexture(txt, opts);
  const m = new THREE.Mesh(
    new THREE.PlaneGeometry(height*aspect, height),
    new THREE.MeshBasicMaterial({map:tex, transparent:true,
      opacity:opts.opacity??0.5, depthWrite:false})
  );
  m.rotation.x = -Math.PI/2;
  m.rotation.z = opts.rotZ ?? 0;
  m.position.set(x, opts.y ?? 0.05, z);
  return m;
}

export {
  edgeMat,
  box,
  edged,
  put,
  CHEV_GEO,
  chevron,
  textTexture,
  groundText
};
