/* Generated by the module split. See README §開発の分担. */
/* Sysdig 2026 brand tokens, as three-friendly hex ints. */


/* ============================================================
   0. palette
   ============================================================ */
const C = {
  lumin:0xBDF78B, white:0xFFFFFF, black:0x000000, deepSee:0x01353E,
  g10:0xEAEBED, g20:0xBBBDBF, g25:0xA3A5A7, g30:0x8A8C8E, g40:0x626466,
  g50:0x535557, g60:0x3E4042, g70:0x2B2D30, g90:0x121217,
  falco:0x00CBE2, yellow:0xFDD835, orange:0xFFA940, red:0xFF7774,
  redUi:0xEA5255, purple:0xCA87DA
};

export {
  C
};
