/* Generated by the module split. See README §開発の分担. */
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { C } from './palette.js';
import { DISTRICTS, cityBox, campaignView } from './layout.js';
import { chevron } from './mesh.js';


/* ============================================================
   2. renderer / scene / camera
   ============================================================ */
const app = document.getElementById('app');
const renderer = new THREE.WebGLRenderer({antialias:true, alpha:false});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));
renderer.setSize(innerWidth, innerHeight);
renderer.setClearColor(0xF7F8F8, 1);
renderer.shadowMap.enabled = false;
app.appendChild(renderer.domElement);

const scene = new THREE.Scene();
scene.background = new THREE.Color(0xF7F8F8);
scene.fog = new THREE.Fog(0xF7F8F8, 320, 940);

const camera = new THREE.PerspectiveCamera(38, Math.max(1,innerWidth)/Math.max(1,innerHeight), 0.5, 1100);
/* the city is ~185 units wide — pull the home shot back on narrow viewports
   so the whole syscall→alert flow stays in frame */
const HOME_TGT = new THREE.Vector3(7, 4, -3);
/* the whole city, including the floating Sysdig deck */
const CITY_BOX = cityBox();
const HOME_DIR = new THREE.Vector3(-0.40, 0.53, 0.75).normalize();

/* Exact fit: push the camera back along HOME_DIR until every corner of CITY_BOX
   is inside the frustum. Adapts to any aspect ratio instead of guessing. */
function homeView(){
  const a  = Math.max(1,innerWidth)/Math.max(1,innerHeight);
  const vt = Math.tan(camera.fov*Math.PI/360);
  const ht = vt*a;
  /* the campaign panel covers the left ~third of the viewport, so fit the city
     into the remaining width and then slide the view across by that much */
  const F   = campaignView ? 0.32 : 0;
  const htF = ht*(1-F);
  const zA = HOME_DIR.clone();                                  // camera sits at +zA
  const xA = new THREE.Vector3().crossVectors(new THREE.Vector3(0,1,0), zA).normalize();
  const yA = new THREE.Vector3().crossVectors(zA, xA);
  const p = new THREE.Vector3();
  let d = 0;
  for(let i=0;i<8;i++){
    p.set(i&1 ? CITY_BOX.max.x : CITY_BOX.min.x,
          i&2 ? CITY_BOX.max.y : CITY_BOX.min.y,
          i&4 ? CITY_BOX.max.z : CITY_BOX.min.z).sub(HOME_TGT);
    const pz = p.dot(zA);
    d = Math.max(d, pz + Math.abs(p.dot(xA))/htF, pz + Math.abs(p.dot(yA))/vt);
  }
  d *= 1.04;
  /* the campaign panel covers the left third of the screen, so slide the whole
     view sideways (camera and target together) to keep the city clear of it */
  const shift = xA.clone().multiplyScalar(-d*ht*F);
  const tgt = HOME_TGT.clone().add(shift);
  return { pos: tgt.clone().add(HOME_DIR.clone().multiplyScalar(d)).toArray(), tgt };
}
const homeCam = () => homeView().pos;
const goHome  = () => { const h = homeView(); flyTo(h.pos, h.tgt); };
camera.position.set(...homeCam());

const controls = new OrbitControls(camera, renderer.domElement);
controls.target.copy(HOME_TGT);
controls.enableDamping = true;
controls.dampingFactor = 0.075;
controls.maxPolarAngle = Math.PI/2 - 0.045;
controls.minDistance = 34;
controls.maxDistance = 720;   // must exceed the widest homeCam() fit
controls.update();

scene.add(new THREE.HemisphereLight(0xffffff, 0xD8DCDE, 1.05));
const sun = new THREE.DirectionalLight(0xffffff, 0.72);
sun.position.set(-70, 130, 90); scene.add(sun);
const rim = new THREE.DirectionalLight(0xCFE9F0, 0.34);
rim.position.set(90, 60, -110); scene.add(rim);


/* ============================================================
   4. ground + district floors
   ============================================================ */
const world = new THREE.Group(); scene.add(world);

const ground = new THREE.Mesh(
  new THREE.PlaneGeometry(340, 240),
  new THREE.MeshLambertMaterial({color:0xFCFCFC})
);
ground.rotation.x = -Math.PI/2; ground.position.y = -0.06;
world.add(ground);

const grid = new THREE.GridHelper(340, 68, 0xE4E6E8, 0xEFF1F2);
grid.position.y = -0.03; world.add(grid);

/* flow road */
(function road(){
  const r = new THREE.Mesh(
    new THREE.PlaneGeometry(178, 15),
    new THREE.MeshBasicMaterial({color:0x2B2D30, transparent:true, opacity:0.055, depthWrite:false})
  );
  r.rotation.x = -Math.PI/2; r.position.set(1,0.01,0); world.add(r);
  for(let x=-78; x<=88; x+=9)
    world.add(chevron(x, 0, 2.7, 0x2B2D30, 0.13));
})();

/* survive a 0×0 start (background tab / hidden pane) and any later resize */
function onResize(){
  const w = Math.max(1, innerWidth), h = Math.max(1, innerHeight);
  camera.aspect = w/h;
  camera.updateProjectionMatrix();
  renderer.setSize(w, h, false);
  renderer.domElement.style.width = '100%';
  renderer.domElement.style.height = '100%';
}
addEventListener('resize', onResize);
new ResizeObserver(onResize).observe(document.documentElement);
onResize();

/* ---- camera flight ---- */
let flight = null;
function flyTo(camPos, target, ms=1050){
  flight = {
    t:0, ms,
    fromP:camera.position.clone(), toP:new THREE.Vector3(...camPos),
    fromT:controls.target.clone(),  toT:target.clone()
  };
}
const easeIO = t => t<0.5 ? 4*t*t*t : 1-Math.pow(-2*t+2,3)/2;
function tickFlight(dt){
  if(!flight) return;
  flight.t += dt*1000;
  const t = Math.min(1, flight.t/flight.ms), e = easeIO(t);
  camera.position.lerpVectors(flight.fromP, flight.toP, e);
  controls.target.lerpVectors(flight.fromT, flight.toT, e);
  if(t >= 1) flight = null;
}

export {
  renderer,
  scene,
  camera,
  controls,
  world,
  CITY_BOX,
  HOME_TGT,
  HOME_DIR,
  homeView,
  homeCam,
  goHome,
  onResize,
  flyTo,
  tickFlight
};
