/* Generated by the module split. See README §開発の分担. */
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { ShaderPass } from 'three/addons/postprocessing/ShaderPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { C } from './palette.js';
import { DISTRICTS, cityBox, campaignView } from './layout.js';
import { chevron, BLOOM_LAYER } from './mesh.js';


/* ============================================================
   2. renderer / scene / camera
   ============================================================ */
const app = document.getElementById('app');
/* antialias:false is not a downgrade — everything goes through the composer
   below, which renders into a 4× multisampled target instead. Leaving it on
   would allocate a second MSAA buffer for a canvas we never draw into. */
const renderer = new THREE.WebGLRenderer({antialias:false, alpha:false,
                                          powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));
renderer.setSize(innerWidth, innerHeight);
renderer.setClearColor(0xF7F8F8, 1);
/* Deliberately NOT tone mapping. ACES/AgX pull #F7F8F8 down to a grey and
   desaturate Lumin and Falco Blue on the way — the brand tokens ARE the output
   values here, so the frame stays untouched and contrast is shaped by lighting
   and the vignette instead. */
renderer.toneMapping = THREE.NoToneMapping;
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
app.appendChild(renderer.domElement);

const scene = new THREE.Scene();
scene.background = new THREE.Color(0xF7F8F8);
scene.fog = new THREE.Fog(0xF7F8F8, 320, 940);

const camera = new THREE.PerspectiveCamera(38, Math.max(1,innerWidth)/Math.max(1,innerHeight), 0.5, 1100);
/* the city is ~185 units wide — pull the home shot back on narrow viewports
   so the whole syscall→alert flow stays in frame */
const HOME_TGT = new THREE.Vector3(7, 4, -3);
/* the whole city, including the floating Sysdig deck */
const CITY_BOX = cityBox();
const HOME_DIR = new THREE.Vector3(-0.40, 0.53, 0.75).normalize();

/* Exact fit: push the camera back along HOME_DIR until every corner of CITY_BOX
   is inside the frustum. Adapts to any aspect ratio instead of guessing. */
function homeView(){
  const a  = Math.max(1,innerWidth)/Math.max(1,innerHeight);
  const vt = Math.tan(camera.fov*Math.PI/360);
  const ht = vt*a;
  /* the campaign panel covers the left ~third of the viewport, so fit the city
     into the remaining width and then slide the view across by that much */
  const F   = campaignView ? 0.32 : 0;
  const htF = ht*(1-F);
  const zA = HOME_DIR.clone();                                  // camera sits at +zA
  const xA = new THREE.Vector3().crossVectors(new THREE.Vector3(0,1,0), zA).normalize();
  const yA = new THREE.Vector3().crossVectors(zA, xA);
  const p = new THREE.Vector3();
  let d = 0;
  for(let i=0;i<8;i++){
    p.set(i&1 ? CITY_BOX.max.x : CITY_BOX.min.x,
          i&2 ? CITY_BOX.max.y : CITY_BOX.min.y,
          i&4 ? CITY_BOX.max.z : CITY_BOX.min.z).sub(HOME_TGT);
    const pz = p.dot(zA);
    d = Math.max(d, pz + Math.abs(p.dot(xA))/htF, pz + Math.abs(p.dot(yA))/vt);
  }
  d *= 1.04;
  /* the campaign panel covers the left third of the screen, so slide the whole
     view sideways (camera and target together) to keep the city clear of it */
  const shift = xA.clone().multiplyScalar(-d*ht*F);
  const tgt = HOME_TGT.clone().add(shift);
  return { pos: tgt.clone().add(HOME_DIR.clone().multiplyScalar(d)).toArray(), tgt };
}
const homeCam = () => homeView().pos;
const goHome  = () => { const h = homeView(); flyTo(h.pos, h.tgt); };
camera.position.set(...homeCam());

const controls = new OrbitControls(camera, renderer.domElement);
controls.target.copy(HOME_TGT);
controls.enableDamping = true;
controls.dampingFactor = 0.075;
controls.maxPolarAngle = Math.PI/2 - 0.045;
controls.minDistance = 34;
controls.maxDistance = 720;   // must exceed the widest homeCam() fit
controls.update();


/* ============================================================
   3b. light
   ------------------------------------------------------------
   Three sources plus an image-based fill. The fill is what makes the
   primitives read as objects instead of flat swatches: a box lit only by a
   hemisphere light carries the same value on every vertical face, which is
   exactly the "CAD screenshot" look this had. A studio gradient in the
   environment gives each face its own reflection and each edge a highlight,
   for the cost of one 32×128 canvas.

   The gradient is white → the page background → grey-10 → grey-20: four
   existing brand tokens. No colour is invented — it is the page's own light,
   arriving from above.
   ============================================================ */
function studioEnvironment(){
  const cv = document.createElement('canvas');
  cv.width = 32; cv.height = 128;
  const ctx = cv.getContext('2d');
  const g = ctx.createLinearGradient(0, 0, 0, 128);
  g.addColorStop(0.00, '#FFFFFF');   // zenith
  g.addColorStop(0.46, '#F7F8F8');   // the page's own background
  g.addColorStop(0.54, '#EAEBED');   // grey-10, at the horizon
  g.addColorStop(1.00, '#BBBDBF');   // grey-20, bounced off the ground
  ctx.fillStyle = g; ctx.fillRect(0, 0, 32, 128);
  const tex = new THREE.CanvasTexture(cv);
  tex.mapping = THREE.EquirectangularReflectionMapping;
  tex.colorSpace = THREE.SRGBColorSpace;
  const pmrem = new THREE.PMREMGenerator(renderer);
  const env = pmrem.fromEquirectangular(tex).texture;
  pmrem.dispose(); tex.dispose();
  return env;
}
scene.environment = studioEnvironment();

/* hemisphere pulled back from 1.05: the environment does that job now, and
   leaving both at full strength flattens everything out again */
scene.add(new THREE.HemisphereLight(0xffffff, 0xD8DCDE, 0.42));
const sun = new THREE.DirectionalLight(0xffffff, 1.25);
/* Fill from the camera's own side, so the faces you are looking at never go
   muddy now that the key light has moved behind the city. This is where the sun
   used to be. */
const rim = new THREE.DirectionalLight(0xCFE9F0, 0.32);
rim.position.set(-90, 70, 110); scene.add(rim);

/* One shadow-casting light, aimed at the city's actual centre and framed by its
   actual bounds, so adding a district or a node cannot push geometry outside
   the shadow camera. Only near-opaque meshes cast (SHADOW_MIN in mesh.js):
   three has no partial shadow, so the glass district shells would otherwise
   paint solid slabs across the ground and the districts would stop being
   readable — which is the one thing shadows are not allowed to cost.

   The direction matters more than the intensity. The old key light sat at
   (-70,130,90), which is almost exactly HOME_DIR — i.e. directly behind the
   viewer. That is why the city read as flat: every shadow a building cast was
   hidden behind the building casting it. Moving the key to the far side puts
   the shadows between the districts and the camera, where they do the work of
   telling you what is standing on the ground and how tall it is. */
{
  const centre = CITY_BOX.getCenter(new THREE.Vector3());
  const r = CITY_BOX.getBoundingSphere(new THREE.Sphere()).radius;
  sun.position.copy(centre).add(new THREE.Vector3(120,150,-95).normalize().multiplyScalar(r*1.7));
  sun.target.position.copy(centre);
  sun.castShadow = true;
  sun.shadow.mapSize.set(2048, 2048);
  const sc = sun.shadow.camera;
  sc.left = -r; sc.right = r; sc.top = r; sc.bottom = -r;
  sc.near = r*0.15; sc.far = r*3.4;
  sc.updateProjectionMatrix();
  sun.shadow.bias = -0.0004;
  sun.shadow.normalBias = 0.5;
  scene.add(sun, sun.target);
}


/* ============================================================
   4. ground + district floors
   ============================================================ */
const world = new THREE.Group(); scene.add(world);

const ground = new THREE.Mesh(
  new THREE.PlaneGeometry(340, 240),
  new THREE.MeshStandardMaterial({color:0xFCFCFC, roughness:0.93, metalness:0,
                                  envMapIntensity:0.55})
);
ground.rotation.x = -Math.PI/2; ground.position.y = -0.06;
ground.receiveShadow = true;
world.add(ground);

/* one step darker than it was (grey-10 on the majors): the ground is the only
   thing giving the empty half of the frame a sense of scale, and at #EFF1F2 it
   was invisible past the middle distance */
const grid = new THREE.GridHelper(340, 68, 0xDCDEE0, 0xEAEBED);
grid.position.y = -0.03; world.add(grid);

/* flow road */
(function road(){
  const r = new THREE.Mesh(
    new THREE.PlaneGeometry(178, 15),
    new THREE.MeshBasicMaterial({color:0x2B2D30, transparent:true, opacity:0.055, depthWrite:false})
  );
  r.rotation.x = -Math.PI/2; r.position.set(1,0.01,0); world.add(r);
  for(let x=-78; x<=88; x+=9)
    world.add(chevron(x, 0, 2.7, 0x2B2D30, 0.13));
})();


/* ============================================================
   4b. post — selective bloom + vignette
   ------------------------------------------------------------
   Two renders per frame:

     1. the city, into a 4× multisampled half-float target
     2. BLOOM_LAYER only, on black, at half resolution, blurred

   then one pass that adds (2) onto (1) and applies the vignette, and
   OutputPass for the linear→sRGB conversion.

   The mask is done with `camera.layers` rather than by swapping every other
   material for black, which is the usual recipe. It is one assignment instead
   of two full scene traversals per frame, and the visible difference is that
   glow is NOT occluded by geometry. That is the behaviour we want: it is what
   lets the buildings become solid (mesh.js §solids) without hiding the syscall
   stream running through them.
   ============================================================ */
const BUF = new THREE.Vector2();
const bufSize = () => renderer.getDrawingBufferSize(BUF);
/* captured before the wrapper at the bottom of this file replaces it */
const rawRender = renderer.render.bind(renderer);

const mainRT = new THREE.WebGLRenderTarget(1, 1, {
  type: THREE.HalfFloatType, samples: 4,
  minFilter: THREE.LinearFilter, magFilter: THREE.LinearFilter
});
const composer = new EffectComposer(renderer, mainRT);
/* only the first target needs MSAA; the ping-pong buffer is already resolved */
composer.renderTarget2.samples = 0;

const bloomRT = new THREE.WebGLRenderTarget(1, 1, {
  type: THREE.HalfFloatType,
  minFilter: THREE.LinearFilter, magFilter: THREE.LinearFilter
});
const bloomComposer = new EffectComposer(renderer, bloomRT);
bloomComposer.renderToScreen = false;
/* clear to black: nothing off the glow layer contributes, the sky included */
bloomComposer.addPass(new RenderPass(scene, camera, null, 0x000000, 1));
/* threshold 0 — selection is by layer, so every pixel that survived the mask is
   by definition something we decided is a light */
const bloomPass = new UnrealBloomPass(new THREE.Vector2(1,1), 0.85, 0.9, 0.0);
bloomComposer.addPass(bloomPass);

const CombineShader = {
  uniforms: {
    tDiffuse: {value:null},
    tBloom:   {value:bloomComposer.renderTarget2.texture},
    uBloom:   {value:1.5},
    uVignette:{value:0.30}
  },
  vertexShader: `
    varying vec2 vUv;
    void main(){ vUv = uv; gl_Position = projectionMatrix * modelViewMatrix * vec4(position,1.0); }`,
  fragmentShader: `
    uniform sampler2D tDiffuse;
    uniform sampler2D tBloom;
    uniform float uBloom;
    uniform float uVignette;
    varying vec2 vUv;
    void main(){
      vec4 base = texture2D(tDiffuse, vUv);
      vec3 lit  = base.rgb + texture2D(tBloom, vUv).rgb * uBloom;
      /* a very shallow falloff: the page is nearly white, so anything stronger
         reads as a grey frame drawn round the canvas rather than as depth */
      vec2 d = vUv - 0.5;
      lit *= 1.0 - uVignette * clamp(dot(d,d) * 1.9, 0.0, 1.0);
      gl_FragColor = vec4(lit, base.a);
    }`
};
const combinePass = new ShaderPass(CombineShader);
composer.addPass(new RenderPass(scene, camera));
composer.addPass(combinePass);
composer.addPass(new OutputPass());

/* live knobs, for the screenshot harness — same spirit as window.__city.
   `post` off renders straight to the canvas, which is how you tell a lighting
   problem apart from a composer problem in one step. */
const FX = { post:true };
if(typeof window !== 'undefined') window.__fx = {
  FX, bloomPass, u: CombineShader.uniforms, sun, scene, camera, renderer,
  set(k, v){ if(CombineShader.uniforms[k]) CombineShader.uniforms[k].value = v;
             else bloomPass[k] = v; }
};


/* survive a 0×0 start (background tab / hidden pane) and any later resize */
function onResize(){
  const w = Math.max(1, innerWidth), h = Math.max(1, innerHeight);
  camera.aspect = w/h;
  camera.updateProjectionMatrix();
  renderer.setSize(w, h, false);
  renderer.domElement.style.width = '100%';
  renderer.domElement.style.height = '100%';
  const b = bufSize();
  composer.setSize(b.x, b.y);
  /* bloom is a blur: half resolution is free quality and a quarter of the work */
  const bw = Math.max(2, Math.round(b.x/2)), bh = Math.max(2, Math.round(b.y/2));
  bloomComposer.setSize(bw, bh);
  bloomPass.setSize(bw, bh);
  CombineShader.uniforms.tBloom.value = bloomComposer.renderTarget2.texture;
}
addEventListener('resize', onResize);
new ResizeObserver(onResize).observe(document.documentElement);
onResize();


/* ---- frame ----
   Anything that has to move but does not belong to the simulation registers
   here, so the render call stays in one place and main.js keeps one line. */
const preRender = [];
function onPreRender(fn){
  preRender.push(fn);
  return () => { const i = preRender.indexOf(fn); if(i>=0) preRender.splice(i,1); };
}

const BLOOM_ONLY = new THREE.Layers(); BLOOM_ONLY.set(BLOOM_LAYER);
const ALL_LAYERS = new THREE.Layers();        // layer 0, the default

/* The particle system is the city's light — raw syscalls, enriched events,
   drops, alerts, each carrying its meaning in its colour — so it belongs on the
   glow layer. It is created by sim.js, which is the rules lane's file, so it is
   picked up out of the scene on the first frame instead of imported: every
   THREE.Points in this city is event flow by construction, and doing it this way
   changes no module's load order. */
let glowWired = false;
function wireGlow(){
  glowWired = true;
  scene.traverse(o => { if(o.isPoints) o.layers.enable(BLOOM_LAYER); });
}

/* main.js owns the clock and nothing hands it over, so measure it here. The only
   thing it drives on this side is the plot animation. */
let lastT = 0;
function frameDt(){
  const t = performance.now();
  const dt = lastT ? Math.min(0.05, (t-lastT)/1000) : 0;
  lastT = t;
  return dt;
}

function renderFrame(){
  if(!glowWired) wireGlow();
  const dt = frameDt();
  for(let i=0;i<preRender.length;i++) preRender[i](dt);

  if(!FX.post){ renderer.setRenderTarget(null); rawRender(scene, camera); return; }

  /* pass 2 of the note above: glow sources only, on black, no fog. Fog would
     drag every distant pixel toward #F7F8F8 and bloom the entire frame. */
  const bg = scene.background, fog = scene.fog;
  scene.background = null; scene.fog = null;
  camera.layers.mask = BLOOM_ONLY.mask;
  bloomComposer.render();
  camera.layers.mask = ALL_LAYERS.mask;
  scene.background = bg; scene.fog = fog;

  composer.render(dt);
}

/* `main.js` belongs to the integration lane, so the post chain hooks itself onto
   the renderer rather than asking for a call-site change: `renderer.render(scene,
   camera)` IS this app's frame, and scene.js is where what that means is decided.
   The re-entry guard lets the passes' own inner renders go straight through. */
let inFrame = false;
renderer.render = function(sc, cam){
  if(inFrame || sc !== scene || cam !== camera){ rawRender(sc, cam); return; }
  inFrame = true;
  try { renderFrame(); } finally { inFrame = false; }
};


/* ---- camera flight ---- */
let flight = null;
function flyTo(camPos, target, ms=1050){
  flight = {
    t:0, ms,
    fromP:camera.position.clone(), toP:new THREE.Vector3(...camPos),
    fromT:controls.target.clone(),  toT:target.clone()
  };
}
const easeIO = t => t<0.5 ? 4*t*t*t : 1-Math.pow(-2*t+2,3)/2;
function tickFlight(dt){
  if(!flight) return;
  flight.t += dt*1000;
  const t = Math.min(1, flight.t/flight.ms), e = easeIO(t);
  camera.position.lerpVectors(flight.fromP, flight.toP, e);
  controls.target.lerpVectors(flight.fromT, flight.toT, e);
  if(t >= 1) flight = null;
}

export {
  renderer,
  scene,
  camera,
  controls,
  world,
  CITY_BOX,
  HOME_TGT,
  HOME_DIR,
  homeView,
  homeCam,
  goHome,
  onResize,
  onPreRender,
  renderFrame,
  flyTo,
  tickFlight
};
