/* Generated by the module split. See README §開発の分担. */
import { C } from './palette.js';
import { DISTRICTS } from './layout.js';
import { byDeployId, bufferCount, CPU_MAX, NODE_CPUS } from './districts.data.js';


/* ============================================================
   7. state + the drop model
   (declared before the particle system — spawn() reads S.dead)
   ============================================================ */
/* falco.yaml as this model holds it.
 *
 * `syscallSet` is the preset the panel offers (all / default / custom_set), but
 * base_syscalls is not only a preset, and a scenario has to be able to hand over
 * the real thing:
 *
 *   base_syscalls:
 *     custom_set: [ ..., !syscall, ... ]
 *     repair: false
 *
 * A POSITIVE custom_set cannot create a blind spot — it is traced *in addition
 * to the syscalls the enabled rules require* (Falco Docs). What does create one
 * is a NEGATIVE entry (`!syscall`) or `repair: false`. So the two are carried
 * separately rather than folded into the preset name.
 *
 * Phase 0 records them and does not score them: the drop model still reads the
 * preset only. Phase 1 (noise) is where negatives and repair start biting, and
 * scenarios written before then must not have to be rewritten. */
const TUNE_DEFAULTS = {
  syscallSet:'default', bufPreset:4, cpusPerBuf:2, slowOutput:false, dropAction:'alert',
  syscallCustom:[],     // base_syscalls.custom_set entries; `!x` is a negative spec
  syscallRepair:true    // base_syscalls.repair
};

const S = {
  mode:'oss', driver:'modern_ebpf', deploy:'k8s', load:1.0,
  /* which of the four environments this is, and how many nodes it has. Both are
     set from the scenario (src/scenarios/schema.js §ENVIRONMENTS, itself derived
     from DEPLOYMENTS). `deploy` above is the topology, one-to-one with `env`.
     `nodes` lives here because that is where districts.data.js said it belonged
     once state.js could be touched — the geometry still reads its own
     nodeCount(), so wiring that across is the next step, not this one.

     `cpus` is the size of the node you are standing on. Node COUNT and node SIZE
     do different things and are the whole point of one of the scenarios: adding
     nodes adds agents (and alert volume), while buffers come from CPUs. */
  env:'self-managed-k8s', nodes:3, cpus:NODE_CPUS,
  selected:null, hovered:null,
  tune:{...TUNE_DEFAULTS},
  dead:false,              // syscall_event_drops.actions: exit fired
  /* BOARD #48. Two different endings, and the pipeline stops for both: `dead` is
     the agent having exited on drops, `over` is the run being finished (points
     ran out). The rules lane raises `over`; sim.js only reads it, so sim.js does
     not have to import score.js. */
  over:false,
  deadDrops:0,
  counters:{sys:0, ring:0, drop:0, rules:0, alerts:0},
  shown:{sys:0, ring:0, drop:0, rules:0, alerts:0},
  alertWindow:[]
};

/* campaign progress. Declared here because spawn() and step() read it, and
   they run before section 14b. In explore mode everything is already built.
   `unmet` is the built-is-not-working axis: districtId -> the ids of the
   conditions that district declares and this situation does not satisfy
   (campaign.js §REQUIREMENTS). Empty for every district by default, so nothing
   that does not opt in can be affected by it. */
const GAME = { on:false, built:new Set(DISTRICTS.map(d=>d.id)),
               unmet:{},
               results:null, reveal:0, revealT:0, frontier:Infinity };

/* ------------------------------------------------------------------
   BUILT IS NOT WORKING.

   A district can be standing and still not do its job, because what makes it
   work is a set of conditions the district declares (campaign.js §REQUIREMENTS)
   and a situation may leave some of them unsatisfied — rules fetched but never
   read, a plugin loaded but not in `rules_files`, an output configured but not
   reachable. On a real cluster that is the majority of "we installed it and it
   does not fire".

   Two different questions, two different predicates, and keeping them apart is
   what makes the state expressible at all:

     GAME.built.has(id)   is it standing?     -> the build list, the geometry
     working(id)          is it doing its job? -> every capability check
   ------------------------------------------------------------------ */
const unmetOf = id => GAME.unmet[id] || [];
const working = id => GAME.built.has(id) && !unmetOf(id).length;

const KERNEL_PASS = 0.42;     // fraction of syscalls the default set forwards
const MATCH_RATE  = 0.004;    // of evaluated events, only a sliver rings

/* What the current topology makes observable at all.
 *
 * The attributes themselves are declared once, on DEPLOYMENTS in
 * districts.data.js, because the geometry reads the same facts. This is only the
 * lookup for the current one.
 *
 * Requirements elsewhere are stated in terms of these attributes and never as
 * the name of a topology, because a name is not a reason: `S.deploy === 'k8s'`
 * became wrong the moment `managed` was declared, and it charges a role with a
 * miss the model never caused — a managed cluster has an API server too.
 *
 *   kernelPath  there is a driver and a ring buffer at all
 *   k8sMeta     events can be enriched with k8s metadata
 *   apiServer   there is a control plane to audit
 *   cluster     there is a cluster, so cluster-scoped components exist */
const deployment = () => byDeployId(S.deploy) || null;
/* The environment decides what exists; the agent version can only fail to see
   it. So this is an AND — a newer agent never invents an API server, and an
   older one can lose a field family it used to read (the in-process k8s client
   removed in 0.37, INVARIANTS 3.7 — GATE-FREEPLAY V6). */
const hasCap = cap => {
  if(!deployment()?.[cap]) return false;
  const v = profile().version.caps[cap];
  return v === undefined ? true : !!v;
};

/* buf_size_preset 1..10 — powers of two, preset 4 = the 8 MiB default */

/* ============================================================
   DATA LAYER RECEIVING PORT
   ------------------------------------------------------------
   The data lanes hand over ONE plain-data object and this is where it lands.
   Field names are NOT invented here — they are the ones src/archetypes.js
   already declares, so an industry file does not get rewritten when the entry
   point arrives (that file says so itself: "宣言だけ先に置いてあるのは、入口が
   できた瞬間に業種側を書き直さずに済ませるため").

   Three rules make this safe to depend on:

     1. Injecting nothing reproduces today's numbers exactly. The defaults are
        chosen so that `burstiness:0.5, spike:1.0, perNodeMul:1.0` IS the current
        model, which means an un-merged data file cannot move main.
     2. A profile supplies COEFFICIENTS and CONSTRAINTS, never a result. It
        cannot set `sustained`, `util`, `dropP` or a detection — those stay
        derived. That is what stops a data file bending causality.
     3. The version axis can only TAKE capabilities away. An environment with no
        API server does not grow one because the agent got newer.

   Load-bearing consequence for GATE-FREEPLAY F1 ("業種ごとに主役のレバーが変わる"):
   burstiness is what decides whether raising buf_size_preset does anything.
   High burstiness + spike (game infra) -> the buffer is the answer. Low
   burstiness with the load simply above capacity (web) -> it is not, because
   `sustained` does not read bufPreset at all (INVARIANTS 1.3). Same model, two
   industries, one number moved.
   ============================================================ */
const PROFILE_DEFAULTS = {
  /* load.base        the production NODE LOAD multiplier (sustained pressure)
     load.burstiness  0..1, how much the load waves. 0 = perfectly smooth, so no
                      burst loss at all. 0.5 reproduces today's model.
     load.spike       peak is base x spike. Feeds the BURST term only: a spike is
                      an instant, and `sustained` is by definition not one. */
  load:    { base:1.0, burstiness:0.5, spike:1.0 },
  /* the alert-volume side of the noise model. Nothing here removes a detection */
  alerts:  { perNodeMul:1.0, plugin:1.0, breadth:1.0, triage:1.0 },
  /* which rule artifact sets are installed, and the priority floor the policy
     acts on. Empty maturity list = every set installed, so the gate is open */
  policy:  { maturity:[], minPriority:null },
  /* agent version. `caps` is ANDed with the environment, never ORed */
  version: { id:null, caps:{} },
  /* material for attack generation and for the scoring lane. Read-only here */
  vuln:    { open:0, oldestDays:0, inUseShare:0 },
  /* which stage is being played, and the per-stage overrides the DATA declares.
     Deliberately not hardcoded: a quieter test stage is a claim the data makes */
  stage:   'prod',
  stages:  {}
};

/* burstiness 0..1 -> multiplier on the burst term. 0.5 is the reference, so the
   default profile and an explicit 0.5 agree, and 0 removes burst loss entirely. */
const BURST_REF = 0.5;

const SECTIONS = ['load','alerts','policy','version','vuln','stage','stages'];
const cloneProfile = v => JSON.parse(JSON.stringify(v));

let _base = cloneProfile(PROFILE_DEFAULTS);
let _profile = cloneProfile(PROFILE_DEFAULTS);

/* one level deep per section, so a partial profile is a legal profile */
function mergeProfile(into, from){
  const out = cloneProfile(into);
  for(const k of SECTIONS){
    if(from?.[k] === undefined) continue;
    out[k] = (k === 'stage') ? from[k]
           : (typeof from[k] === 'object' && !Array.isArray(from[k]))
             ? {...out[k], ...from[k]} : from[k];
  }
  return out;
}

/* Report problems instead of throwing: a malformed data file must not take the
   game down, it must surface as a named error the way SCENARIO_ERRORS does. */
function profileErrors(p){
  const e = [];
  if(p === null || typeof p !== 'object' || Array.isArray(p)) return ['profile must be an object'];
  for(const k of Object.keys(p))
    if(!SECTIONS.includes(k)) e.push(`unknown section: ${k}`);
  const num = (v,n,max) => {
    if(v === undefined) return;
    if(!(typeof v === 'number' && Number.isFinite(v) && v >= 0))
      e.push(`${n} must be a finite number >= 0`);
    else if(max !== undefined && v > max) e.push(`${n} must be <= ${max}`);
  };
  num(p.load?.base,'load.base');
  num(p.load?.burstiness,'load.burstiness', 1);
  if(p.load?.spike !== undefined && !(typeof p.load.spike === 'number' && p.load.spike >= 1))
    e.push('load.spike must be a number >= 1 (a peak is not below the baseline)');
  for(const k of ['perNodeMul','plugin','breadth','triage']) num(p.alerts?.[k], `alerts.${k}`);
  if(p.policy?.maturity !== undefined && !Array.isArray(p.policy.maturity))
    e.push('policy.maturity must be an array of maturity ids');
  if(p.version?.caps !== undefined &&
     (typeof p.version.caps !== 'object' || Array.isArray(p.version.caps)))
    e.push('version.caps must be an object of capability -> boolean');
  for(const k of ['open','oldestDays','inUseShare']) num(p.vuln?.[k], `vuln.${k}`);
  if(p.stage !== undefined && typeof p.stage !== 'string') e.push('stage must be a string');
  try { JSON.parse(JSON.stringify(p)); } catch { e.push('profile must survive JSON (plain data only)'); }
  return e;
}

/* hand over a profile. Returns the errors it found; on error nothing changes. */
function setProfile(p){
  const errs = profileErrors(p);
  if(errs.length) return errs;
  _base = mergeProfile(PROFILE_DEFAULTS, p);
  applyStage(_base.stage);
  return [];
}
/* switch stage using the overrides the DATA declared */
function applyStage(name){
  const over = _base.stages?.[name];
  _profile = over ? mergeProfile(_base, over) : cloneProfile(_base);
  _profile.stage = name;
  return _profile.stage;
}
const setStage = applyStage;
const profile = () => _profile;
const resetProfile = () => {
  _base = cloneProfile(PROFILE_DEFAULTS);
  _profile = cloneProfile(PROFILE_DEFAULTS);
};

const PRESET_MIB = p => Math.pow(2, p-1);

/* How much of the syscall stream the driver is told to forward.
   base_syscalls.custom_set is the lever that actually reduces inflow. */
const SET_MUL = { all:1.85, default:1.0, custom:0.40 };

/* ------------------------------------------------------------------
   THE DRAIN SIDE, AND WHERE IT COMES FROM.

   Two separate facts, and conflating them is a units error the model used to
   commit by having neither:

     nCPU       how big the node is. The buffer count is
                ceil(nCPU / cpus_for_each_buffer) and nCPU belongs to ONE NODE
                (INVARIANTS 3.6), so scaling the cluster out adds DaemonSet pods
                and gives the overflowing node no new buffer at all
     buffers    how that memory is cut up. NOT how much drain there is

   The formula itself lives in districts.data.js, because the ring district draws
   its lanes from the same number and the label reads off it — one expression, so
   the picture and the arithmetic cannot disagree. `S.cpus` is the declaration
   (scenarios/schema.js §env.cpus) and it is clamped the same way the geometry
   clamps it, so what the model computes is what the city is showing.
   ------------------------------------------------------------------ */
const nodeCpuCount = () =>
  Math.max(1, Math.min(CPU_MAX, Math.round(S.cpus || NODE_CPUS)));
const buffers = () => bufferCount(S.tune.cpusPerBuf, nodeCpuCount());

/* How much a node of this size can drain, relative to the 8-vCPU node every
   number in README §実測した挙動 was measured on. Sub-linear: the consumer is
   not the only thing running, and a bigger box is not proportionally better at
   keeping up. This is the term that makes a 2-vCPU node a genuinely different
   machine rather than the same machine with fewer troughs drawn. */
const CPU_CAP = [[1,0.30],[2,0.45],[4,0.72],[8,1.00],[16,1.28]];

/* What cutting the same memory into more buffers does. The Docs are explicit
   about the direction and it is the opposite of what this model used to say:
   to fight drops they recommend raising `cpus_for_each_buffer` to 4–6 (FEWER,
   larger buffers) together with a bigger preset, not lowering it. Fewer buffers
   is less for the single consumer to poll. So capacity RISES as the buffer count
   falls — modestly, because this is polling overhead and not the main term.
   4 buffers is 1.00 because that is the default (8 CPU / preset 2), and every
   measured row in the README sits there. */
const BUF_CAP = [[1,1.16],[2,1.08],[4,1.00],[8,0.92],[16,0.85]];

/* piecewise linear in log2 — that is the axis both of these move on */
function interp(anchors, n){
  const x = Math.log2(Math.max(1, n));
  if(x <= 0) return anchors[0][1];
  for(let i=1;i<anchors.length;i++){
    const x1 = Math.log2(anchors[i][0]);
    if(x <= x1){
      const x0 = Math.log2(anchors[i-1][0]);
      const t = (x - x0) / (x1 - x0);
      return anchors[i-1][1] + (anchors[i][1] - anchors[i-1][1]) * t;
    }
  }
  return anchors[anchors.length-1][1];
}
/* the reference node's capacity. Everything else is a ratio against it. */
const CAP_REF = 1.55;
const drainCap = () =>
  CAP_REF * interp(CPU_CAP, nodeCpuCount()) * interp(BUF_CAP, buffers());

/* ------------------------------------------------------------------
   The drop model, and the reason this whole panel exists.

   Two different failure modes, with two different fixes:

   1. SUSTAINED  inflow > drain capacity for a sustained period.
      Fraction lost = 1 - capacity/inflow. A bigger ring buffer does
      NOT help — it fills up and then you lose the same share. The fix
      is to reduce inflow (base_syscalls) or raise capacity.

   2. BURST      inflow fits on average but arrives in spikes.
      The buffer absorbs spikes, so a bigger buf_size_preset genuinely
      fixes this one.

   Conflating the two is why people bump the buffer, see no change, and
   conclude Falco "can't keep up".
   ------------------------------------------------------------------ */
function model(){
  const t = S.tune;
  const P = profile();
  const inflow = S.load * P.load.base * SET_MUL[t.syscallSet];

  /* the drain side is a property of the NODE — its size, and how its buffers are
     cut up — not of how many nodes the cluster grew to. Defaults (8 CPU / preset
     2 = 4 buffers) are sized so a healthy node sits at ~65%. */
  let cap = drainCap();
  if(S.driver==='ebpf') cap *= 0.96;
  if(S.driver==='kmod') cap *= 0.90;
  if(t.slowOutput)      cap *= 0.52;   // userspace blocked writing alerts drains slower

  const util      = inflow / cap;
  const sustained = Math.max(0, 1 - 1/util);
  /* burst loss only bites as you approach capacity, and shrinks as the buffer grows */
  /* burstiness scales it, spike decides how far the peak overshoots capacity,
     and bufPreset is the only thing that answers either. `sustained` above reads
     none of the three — that separation IS invariant 1.3. */
  const burst = 0.020 * (P.load.burstiness / BURST_REF)
                     * Math.min(1.6, Math.max(0, util*P.load.spike - 0.75))
                     / Math.pow(2, (t.bufPreset-1)*0.42);

  return {inflow, cap, util, sustained, burst, dropP:Math.min(0.92, sustained+burst),
          buffers:buffers(), cpus:nodeCpuCount(),
          passRatio:Math.min(0.93, KERNEL_PASS*SET_MUL[t.syscallSet])};
}

/* ------------------------------------------------------------------
   THE SECOND PLACE THE SAME ARITHMETIC BITES.

   The ring buffer is not the only queue in this pipeline. It is only the
   one with a counter on it. Alerts land in a human queue — the SOC — and
   that queue has a rate too, so it has the same failure mode:

                 消える場所            計測
     drop        リングバッファ        syscall_event_drops が上がる
     noise       SOC のキュー          何も上がらない。本物が埋もれる

   Same expression as `sustained`, applied one stage later:

       buried = 1 - triage capacity / alert inflow

   There is deliberately NO burst term here. A ring buffer has
   buf_size_preset and absorbs a spike; a human queue has no such knob, so
   the only two moves are to reduce the input or to raise the capacity.
   That is the whole reason this stage exists: without it the optimum is
   "build everything and let everything ring", and defending is not a
   decision. With it, both directions lose.

   What moves the input, and whose lever each one is:

     nodes / load    ownerless — the shape of the estate and what it is doing
     base_syscalls   SRE. Narrowing removes events NO ENABLED RULE ASKED FOR,
                     so it removes noise without removing coverage. That is
                     not a loophole, it is what the positive custom_set does
                     (INVARIANTS 2.1) — and it is why the blind spot has to
                     come from a NEGATIVE entry instead (2.4)
     09 ルール配布    detection engineer. Following the incubating / sandbox
                     artifacts is how you get detections you did not have —
                     and every one of them also has a false-positive rate
     07 プラグイン入力 detection engineer. Another source is another stream
     drops           an overloaded node is a QUIETER node. Losing events
                     lowers the alert rate. Honest, and horrible

   What moves the capacity:

     08 Sysdig       SOC. Correlation and grouping mean the same alerts are
                     fewer things to look at. Note what this does NOT do:
                     it adds no detection (INVARIANTS 5.2). The stage where
                     Sysdig changes nothing stays in the model
     built outputs   below that there is no queue, because nothing arrives

   Numbers are illustrative, in alerts/min. The ratio is the claim.
   ------------------------------------------------------------------ */
const SOC = {
  perNode:6.0,     // alerts/min a node produces on the default base set at ×1.0
  plugin:4.0,      // alerts/min a plugin source adds, cluster-wide not per node
  follow:1.55,     // incubating + sandbox artifacts widen the ruleset
  cap:40.0,        // alerts/min a SOC queue actually triages
  sysdig:2.1       // correlation: same alerts, fewer things to look at
};

function noise(){
  const M = model();
  const alive = !S.dead && working('rules') && working('outputs');
  /* with no kernel path nothing syscall-derived arrives at all, so the only
     alerts in the queue are the ones the plugin sources bring (INVARIANTS 3.10) */
  const P = profile();
  const base    = hasCap('kernelPath')
    ? SOC.perNode * P.alerts.perNodeMul * Math.max(0, S.nodes) * S.load * P.load.base : 0;
  const breadth = base * (SET_MUL[S.tune.syscallSet] - 1) * P.alerts.breadth;  // the SRE's lever
  const set     = base + breadth;
  const ruleset = set * (working('falcoctl') ? SOC.follow - 1 : 0)
                + (working('plugins') ? SOC.plugin * P.alerts.plugin : 0);  // the detect lever
  /* an overloaded node is a quieter node: what the ring buffer ate never rings */
  const survive = 1 - M.dropP;
  const inflow  = alive ? Math.max(0, (set + ruleset) * survive) : 0;

  const corr = S.mode === 'sysdig' && working('sysdig');
  const cap  = SOC.cap * P.alerts.triage * (corr ? SOC.sysdig : 1);
  const util = inflow / cap;
  const buriedP = Math.max(0, 1 - 1/util);

  return {inflow, cap, util, buriedP, corr,
          /* how much each decision put into the queue, so blame can be derived
             rather than asserted (campaign.js §noiseBlame) */
          parts:{ base:base*survive, breadth:breadth*survive,
                  ruleset:ruleset*survive, capacityGap:SOC.cap*(SOC.sysdig-1) }};
}

export {
  S,
  GAME,
  TUNE_DEFAULTS,
  KERNEL_PASS,
  MATCH_RATE,
  PRESET_MIB,
  SET_MUL,
  SOC,
  CPU_CAP,
  BUF_CAP,
  CAP_REF,
  nodeCpuCount,
  buffers,
  drainCap,
  deployment,
  hasCap,
  unmetOf,
  working,
  model,
  noise,
  PROFILE_DEFAULTS,
  BURST_REF,
  profileErrors,
  setProfile,
  setStage,
  profile,
  resetProfile
};
