/* Generated by the module split. See README §開発の分担. */
import * as THREE from 'three';
import { C } from './palette.js';
import { DISTRICTS, byId, hex6 } from './layout.js';
import { S, model } from './state.js';
import { camera, controls, renderer, scene, homeCam, homeView, goHome,
         HOME_TGT, flyTo, CITY_BOX } from './scene.js';
import { districtObjs, hitTargets } from './city.js';
import { setMode } from './controls.js';
import {
  GAME, DEPS, BUILD_ORDER, SIDES, ROLES, roleById, OWNER, LEVER_OWNER,
  canBuild, canUseLever, roleReport, verdictText, score,
  build, requestBuild, runAttack, setRole, setSide, setUiMode, onCampaignChange
} from './campaign.js';


/* ============================================================
   11. HTML labels anchored to 3D
   ============================================================ */
const tagEls = {};
DISTRICTS.forEach(d=>{
  const el = document.createElement('div');
  el.className = 'tag';
  el.innerHTML = `${d.tag}<span class="cnt">${d.n}</span>`;
  document.body.appendChild(el);
  tagEls[d.id] = el;
});

const v = new THREE.Vector3();
function updateTags(){
  for(const d of DISTRICTS){
    const o = districtObjs[d.id];
    v.copy(o.anchor).project(camera);
    const el = tagEls[d.id];
    const behind = v.z > 1;
    if(behind){ el.style.opacity = 0; continue; }
    const x = (v.x*0.5+0.5)*innerWidth;
    const y = (-v.y*0.5+0.5)*innerHeight;
    el.style.left = x+'px'; el.style.top = y+'px';
    const dist = camera.position.distanceTo(o.anchor);
    el.style.opacity = dist > 780 ? 0 : 1;
    el.classList.toggle('hot', S.hovered===d.id || S.selected===d.id);
    el.classList.toggle('dim',
      d.id==='sysdig' && S.mode!=='sysdig');
    /* a district that has not been built is not on the map at all */
    const unbuilt = GAME.on && !GAME.built.has(d.id);
    el.style.display = unbuilt ? 'none' : '';
    if(unbuilt) el.style.opacity = 0;
  }
}


/* ============================================================
   12. hover / pick
   ============================================================ */
/* districts that are not built cannot be hovered or clicked */
const pickable = () => hitTargets.filter(h =>
  !GAME.on || GAME.built.has(h.userData.district.id));

const ray = new THREE.Raycaster();
const ndc = new THREE.Vector2();
const hoverCard = document.getElementById('hoverCard');
const hcT = hoverCard.querySelector('.hc-t');
const hcN = hoverCard.querySelector('.hc-n');
const hcS = hoverCard.querySelector('.hc-s');
const hcM = hoverCard.querySelector('.hc-m');
let mouse = {x:-1e4,y:-1e4};

renderer.domElement.addEventListener('pointermove', e=>{
  mouse.x = e.clientX; mouse.y = e.clientY;
  ndc.x = (e.clientX/innerWidth)*2-1;
  ndc.y = -(e.clientY/innerHeight)*2+1;
  ray.setFromCamera(ndc, camera);
  const hits = ray.intersectObjects(pickable(), false);
  const d = hits.length ? hits[0].object.userData.district : null;
  if((d?d.id:null) !== S.hovered){
    S.hovered = d ? d.id : null;
    if(d){
      hcT.textContent = d.hoverT;
      hcN.textContent = '+'+d.n;
      hcS.textContent = d.hoverS;
      hcM.innerHTML = d.hoverM.join('<br>');
      hoverCard.classList.add('show');
    } else hoverCard.classList.remove('show');
    renderer.domElement.style.cursor = d ? 'pointer' : 'grab';
  }
  if(S.hovered){
    const w = hoverCard.offsetWidth || 300, h = hoverCard.offsetHeight || 90;
    hoverCard.style.left = Math.min(innerWidth-w-14, e.clientX+18)+'px';
    hoverCard.style.top  = Math.max(12, e.clientY-h-16)+'px';
  }
});
renderer.domElement.addEventListener('pointerleave', ()=>{
  S.hovered=null; hoverCard.classList.remove('show');
});

let downAt = null;
renderer.domElement.addEventListener('pointerdown', e=>{ downAt={x:e.clientX,y:e.clientY,t:performance.now()}; });
renderer.domElement.addEventListener('pointerup', e=>{
  if(!downAt) return;
  const moved = Math.hypot(e.clientX-downAt.x, e.clientY-downAt.y);
  const quick = performance.now()-downAt.t < 420;
  downAt = null;
  if(moved > 6 || !quick) return;
  ndc.x = (e.clientX/innerWidth)*2-1;
  ndc.y = -(e.clientY/innerHeight)*2+1;
  ray.setFromCamera(ndc, camera);
  const hits = ray.intersectObjects(pickable(), false);
  if(hits.length) select(hits[0].object.userData.district.id);
  else closeDrawer();
});


/* ============================================================
   13. camera flight + drawer
   ============================================================ */

const drawer = document.getElementById('drawer');
function select(id){
  const d = DISTRICTS.find(x=>x.id===id);
  if(!d) return;
  S.selected = id;
  flyTo(d.cam, districtObjs[id].center);
  document.getElementById('dEyebrow').textContent = `stage ${d.n} — ${d.tag.toLowerCase()}`;
  document.getElementById('dTitle').textContent = d.jp;
  document.getElementById('dEn').textContent = d.en;
  const mHtml = d.metrics.map(([k,val])=>
    `<div class="metric"><div class="k">${k}</div><div class="v">${val}</div></div>`).join('');
  document.getElementById('dBody').innerHTML =
    `<div class="metrics">${mHtml}</div>` + d.body;
  document.getElementById('dBody').scrollTop = 0;
  drawer.classList.add('open');
  [...document.querySelectorAll('#tour button')].forEach(b=>
    b.classList.toggle('on', b.dataset.id===id));
  document.getElementById('hint').classList.add('gone');
  if(id==='sysdig') setMode('sysdig');
}
function closeDrawer(){
  S.selected=null; drawer.classList.remove('open');
  [...document.querySelectorAll('#tour button')].forEach(b=>b.classList.remove('on'));
}
document.getElementById('dclose').onclick = closeDrawer;

/* tour bar */
const tour = document.getElementById('tour');
DISTRICTS.forEach(d=>{
  const b = document.createElement('button');
  b.dataset.id = d.id;
  b.innerHTML = `<span class="n">${d.n}</span>${d.jp}`;
  b.onclick = ()=>select(d.id);
  tour.appendChild(b);
});
const reset = document.createElement('button');
reset.innerHTML = `<span class="n">↺</span>全体`;
reset.onclick = ()=>{ closeDrawer(); goHome(); };
tour.appendChild(reset);


/* ============================================================
   14d. CAMPAIGN PANEL — the receiving side
   ------------------------------------------------------------
   campaign.js decides; this renders. It subscribes to the change feed and
   redraws, so the two can be worked on without sharing a line. Every DOM
   reference for the campaign lives here and nowhere else.
   ============================================================ */
const elCmp   = document.getElementById('campaign');
const elTitle = document.getElementById('cmpTitle');
const elSides = document.getElementById('cmpSides');
const elRoles = document.getElementById('cmpRoles');
const elHint  = document.getElementById('cmpHint');
const elBuild = document.getElementById('cmpBuild');
const elRun   = document.getElementById('cmpRun');
const elRes   = document.getElementById('cmpResults');
const elScore = document.getElementById('cmpScore');

const DEFAULT_MISSION = '検知パイプラインを一から建てる';
const EMPTY_PLOT = 'いまは空き地。ワークロードは syscall を出しているが、受け止めるものが何も無い。';

/* lever group -> the panel it lives in. campaign.js names the group; only this
   file knows which node that is. */
const LEVER_NODE = {
  deploy:'#deploySeg', driver:'#drvSeg', tuning:'.panel.tune', stack:'#modeSeg'
};

function setHint(html, good){
  elHint.className = 'cmp-hint' + (good ? ' good' : '');
  elHint.innerHTML = html;
}

/* ---- a lever you do not own is visible but untouchable ---- */
function applyRoleLocks(){
  for(const [group, sel] of Object.entries(LEVER_NODE)){
    const el = document.querySelector(sel);
    if(!el) continue;
    const lock = !canUseLever(group);
    el.classList.toggle('dutylock', lock);
    if(lock) el.dataset.owner = `${roleById(LEVER_OWNER[group]).short} 担当`;
    else delete el.dataset.owner;
  }
}

/* ---- side picker: defence is playable, offence is shown as not yet ---- */
function renderSides(){
  elSides.innerHTML = '';
  SIDES.forEach(sd=>{
    const b = document.createElement('button');
    b.textContent = sd.chip;
    if(GAME.side === sd.id) b.className = 'on';
    if(!sd.enabled){
      b.disabled = true;
      b.title = sd.jp + '— まだ実装されていません';
    } else b.onclick = ()=> setSide(sd.id);
    elSides.appendChild(b);
  });
  const auto = document.createElement('span');
  auto.className = 'ask';
  auto.textContent = GAME.side === 'defense' ? '攻撃 Auto' : '';
  elSides.appendChild(auto);
}

/* ---- role picker ---- */
function renderRoles(){
  elRoles.innerHTML = '';
  const add = (id, label, color)=>{
    const b = document.createElement('button');
    if(GAME.role === id) b.className = 'on';
    if(color){
      const i = document.createElement('i');
      i.style.background = color;
      b.appendChild(i);
    }
    b.appendChild(document.createTextNode(label));
    b.onclick = ()=> setRole(id);
    elRoles.appendChild(b);
  };
  add(null, '全役');
  ROLES.forEach(r => add(r.id, r.chip, r.color));
  const ask = document.createElement('span');
  ask.className = 'ask';
  ask.textContent = GAME.asks ? `依頼 ${GAME.asks}件` : '';
  elRoles.appendChild(ask);
}

/* ---- build list: rows carry their owner, other teams' stages are asked for ---- */
function renderBuildList(){
  elBuild.innerHTML = '';
  BUILD_ORDER.forEach(id=>{
    const d = byId(id);
    const owner = roleById(OWNER[id]);
    const done = GAME.built.has(id), open = !done && canBuild(id);
    const mine = !GAME.role || !owner || GAME.role === owner.id;

    const row = document.createElement('div');
    row.className = 'cmp-row ' + (done ? 'done' : open ? '' : 'locked')
                  + (owner && GAME.role === owner.id ? ' mine' : '');
    row.innerHTML = `<span class="n">${d.n}</span><span class="nm">${d.jp}</span>`;

    if(owner){
      const badge = document.createElement('span');
      badge.className = 'own';
      badge.textContent = owner.short;
      badge.style.borderLeftColor = owner.color;
      row.appendChild(badge);
    }

    if(done) row.insertAdjacentHTML('beforeend', '<span class="tick">✓</span>');
    else if(open){
      const b = document.createElement('button');
      if(mine){
        b.textContent = '建設';
        b.onclick = ()=> build(id);
      } else {
        b.textContent = `${owner.short} に依頼`;
        b.className = 'askbtn';
        b.onclick = ()=> requestBuild(id);
      }
      row.appendChild(b);
    } else {
      row.insertAdjacentHTML('beforeend',
        `<span class="lk">要 ${DEPS[id].map(k=>byId(k).jp).join('・')}</span>`);
    }
    elBuild.appendChild(row);
  });
}

/* ---- results, with the role each miss is charged to ---- */
function renderRoleReport(){
  const rep = roleReport();
  const wrap = document.createElement('div');
  wrap.className = 'rrep';
  wrap.innerHTML = '<h5>role scorecard</h5>';
  rep.roles.forEach(r=>{
    const row = document.createElement('div');
    row.className = 'rrow ' + (r.misses ? 'blamed' : r.built === r.owns ? 'clean' : '');
    row.style.borderLeftColor = r.color;
    row.innerHTML =
      `<span class="rn">${r.jp}${r.mine ? '（あなた）' : ''}</span>`+
      `<span class="rv">${r.built}/${r.owns} 建設${r.misses ? ` · 見逃し ${r.misses}` : ''}</span>`;
    wrap.appendChild(row);
  });
  rep.notes.forEach(html=>{
    const n = document.createElement('div');
    n.className = 'rnote';
    n.innerHTML = html;
    wrap.appendChild(n);
  });
  elRes.appendChild(wrap);
}

function renderResults(){
  elRes.innerHTML = '';
  elScore.textContent = score();
  if(!GAME.results) return;
  GAME.results.slice(0, GAME.reveal).forEach((r,i)=>{
    const el = document.createElement('div');
    el.className = 'cmp-res ' + (r.caught ? 'hit' : 'miss');
    el.innerHTML =
      `<span class="st">${r.response ? '対処' : 'step '+(i+1)} · ${r.caught ? '検知' : '見逃し'}</span>`+
      `<span class="ac">${r.jp}</span>`+
      `<span class="rl">${r.rule}</span>`+
      (r.why ? `<span class="wy">${r.why}</span>` : '');
    const b = roleById(r.blame);
    if(b){
      const s = document.createElement('span');
      s.className = 'bl';
      s.style.borderLeftColor = b.color;
      s.textContent = `起因 · ${b.jp}`;
      el.appendChild(s);
    }
    elRes.appendChild(el);
  });
  const done = GAME.reveal >= GAME.results.length;
  if(done){
    const v = verdictText();
    if(v) setHint(v.html, v.good);
    renderRoleReport();
  }
  elRun.disabled = !done;
  elRes.scrollTop = elRes.scrollHeight;      /* follow the reveal */
}

/* ---- the change feed ---- */
function renderCampaignAll(){
  renderSides();
  renderRoles();
  renderBuildList();
  applyRoleLocks();
  renderResults();
}

onCampaignChange(ev=>{
  switch(ev.type){
    case 'mode':
      elCmp.classList.toggle('on', GAME.on);
      [...document.querySelectorAll('#uiModeSeg button')].forEach(b=>
        b.classList.toggle('on', b.dataset.ui === ev.mode));
      document.getElementById('hint').classList.add('gone');
      elScore.textContent = '0';
      elRun.disabled = false;
      setHint(EMPTY_PLOT, false);
      elTitle.textContent = GAME.role ? roleById(GAME.role).mission : DEFAULT_MISSION;
      renderCampaignAll();
      closeDrawer();
      goHome();
      break;
    case 'role': {
      const r = ev.id ? roleById(ev.id) : null;
      elTitle.textContent = r ? r.mission : DEFAULT_MISSION;
      setHint(r ? `<b>${r.jp}</b>として参加する。${r.brief}` : EMPTY_PLOT, false);
      renderSides(); renderRoles(); renderBuildList(); applyRoleLocks();
      break;
    }
    case 'side':
      setHint(`<b>${SIDES.find(s=>s.id===ev.id).jp}</b>。`+
              SIDES.find(s=>s.id===ev.id).brief, false);
      renderSides();
      break;
    case 'build':
      setHint(ev.unlock, true);
      renderBuildList();
      renderResults();
      flyTo(byId(ev.id).cam, districtObjs[ev.id].center);
      break;
    case 'asks':
      renderRoles();
      break;
    case 'run':
    case 'reveal':
      renderResults();
      break;
  }
});

document.querySelectorAll('#uiModeSeg button').forEach(b=>
  b.onclick = ()=> setUiMode(b.dataset.ui));
elRun.onclick = runAttack;


/* ============================================================
   15. minimap
   ============================================================ */
const mm = document.getElementById('mmc');
const mctx = mm.getContext('2d');
const MM_W = mm.width, MM_H = mm.height;
const MM = {x0:CITY_BOX.min.x-8, x1:CITY_BOX.max.x+8, z0:CITY_BOX.min.z-8, z1:CITY_BOX.max.z+8};
function mx(x){ return (x-MM.x0)/(MM.x1-MM.x0)*MM_W; }
function mz(z){ return (z-MM.z0)/(MM.z1-MM.z0)*MM_H; }

/* colours follow each district's own `color` — no second list to maintain */
const MM_FILL = Object.fromEntries(DISTRICTS.map(d => [d.id, hex6(d.color)]));
function drawMinimap(){
  mctx.clearRect(0,0,MM_W,MM_H);
  mctx.fillStyle = '#FAFBFB'; mctx.fillRect(0,0,MM_W,MM_H);

  // flow spine
  mctx.strokeStyle='rgba(43,45,48,.10)'; mctx.lineWidth=7;
  mctx.beginPath(); mctx.moveTo(mx(-80),mz(0)); mctx.lineTo(mx(90),mz(0)); mctx.stroke();

  DISTRICTS.forEach(d=>{
    if(GAME.on && !GAME.built.has(d.id)) return;
    const x=mx(d.x0), y=mz(d.z0), w=mx(d.x1)-mx(d.x0), h=mz(d.z1)-mz(d.z0);
    const active = S.selected===d.id || S.hovered===d.id;
    const dim = d.id==='sysdig' && S.mode!=='sysdig';
    mctx.globalAlpha = dim ? 0.2 : (active ? 0.9 : 0.42);
    mctx.fillStyle = MM_FILL[d.id];
    mctx.beginPath(); mctx.roundRect(x,y,w,h,3); mctx.fill();
    mctx.globalAlpha = dim ? 0.3 : 1;
    mctx.strokeStyle = active ? '#000' : 'rgba(0,0,0,.14)';
    mctx.lineWidth = active ? 1.4 : 0.8;
    mctx.beginPath(); mctx.roundRect(x,y,w,h,3); mctx.stroke();
    mctx.globalAlpha = dim ? 0.35 : 0.85;
    mctx.fillStyle = active ? '#000' : '#535557';
    mctx.font = '400 7.5px "Share Tech Mono", monospace';
    mctx.fillText(d.n, x+3, y+9.5);
  });
  mctx.globalAlpha = 1;

  // camera position + look direction
  const cpx = mx(camera.position.x), cpz = mz(camera.position.z);
  const tx = mx(controls.target.x), tz = mz(controls.target.z);
  mctx.strokeStyle='rgba(0,0,0,.28)'; mctx.lineWidth=1;
  mctx.beginPath(); mctx.moveTo(cpx,cpz); mctx.lineTo(tx,tz); mctx.stroke();
  mctx.fillStyle='#000';
  mctx.beginPath(); mctx.arc(cpx,cpz,3.4,0,7); mctx.fill();
  mctx.fillStyle='#BDF78B';
  mctx.beginPath(); mctx.arc(tx,tz,2.4,0,7); mctx.fill();

  mctx.fillStyle='rgba(0,0,0,.32)';
  mctx.font='400 7px "Share Tech Mono", monospace';
  mctx.fillText('N ▲', 5, MM_H-6);
}
if(!CanvasRenderingContext2D.prototype.roundRect){
  CanvasRenderingContext2D.prototype.roundRect = function(x,y,w,h,r){
    this.moveTo(x+r,y); this.arcTo(x+w,y,x+w,y+h,r);
    this.arcTo(x+w,y+h,x,y+h,r); this.arcTo(x,y+h,x,y,r);
    this.arcTo(x,y,x+w,y,r); this.closePath(); return this;
  };
}


/* ============================================================
   16. HUD numbers
   ============================================================ */
const els = {
  sys:document.getElementById('mSys'), ring:document.getElementById('mRing'),
  drop:document.getElementById('mDrop'), rules:document.getElementById('mRules'),
  alert:document.getElementById('mAlert')
};
const T0 = performance.now();
let hudT = 0, lastC = {...S.counters};
function updateHud(dt){
  hudT += dt;
  if(hudT < 0.42) return;
  const k = 1/hudT;
  // scale the visual sim up to a plausible busy-node range (illustrative)
  const SCALE = 145;
  const sysRate  = (S.counters.sys  - lastC.sys ) * k * SCALE;
  const ringRate = (S.counters.ring - lastC.ring) * k * SCALE;
  const dropRate = (S.counters.drop - lastC.drop) * k * SCALE;
  const ruleRate = (S.counters.rules- lastC.rules)* k * SCALE;
  lastC = {...S.counters}; hudT = 0;

  const sm = (a,b)=> a + (b-a)*0.35;
  S.shown.sys  = sm(S.shown.sys, sysRate);
  S.shown.ring = sm(S.shown.ring, ringRate);
  S.shown.drop = sm(S.shown.drop, dropRate);
  S.shown.rules= sm(S.shown.rules, ruleRate);

  const now = performance.now();
  S.alertWindow = S.alertWindow.filter(t=> now-t < 60000);
  /* alerts/min — extrapolate until a full 60s window has actually elapsed */
  const win = Math.min(60000, Math.max(5000, now - T0));
  const apm = S.alertWindow.length * (60000/win);

  els.sys.textContent   = fmt(S.shown.sys);
  els.ring.textContent  = fmt(S.shown.ring);
  const dropPct = S.shown.ring>0 ? (S.shown.drop/(S.shown.ring+S.shown.drop))*100 : 0;
  els.drop.textContent  = fmt(S.shown.drop) + '  (' + dropPct.toFixed(2) + '%)';
  els.rules.textContent = fmt(S.shown.rules);
  els.alert.textContent = Math.round(apm);
  els.drop.className = dropPct > 0.2 ? 'red' : 'dark';
  updateVerdict(model());
}

/* The teaching payload: name WHICH failure mode you are looking at,
   because the two have different fixes. */
const elUtil = document.getElementById('mUtil');
const elVerdict = document.getElementById('mVerdict');
function updateVerdict(M){
  elUtil.textContent = Math.round(M.util*100)+'%';
  elUtil.className = M.util > 1 ? 'red' : 'dark';
  let cls, txt;
  if(S.dead){
    cls = 'dead';
    txt = 'falco が <b>exit</b> しました。検知はゼロです。負荷か設定を変えると再起動します。';
  } else if(M.sustained > 0.004){
    cls = 'sustained';
    txt = `持続的な入力超過（消費能力の <b>${Math.round(M.util*100)}%</b>）。`
        + `<b>バッファを増やしても直りません</b> — base_syscalls を custom_set に絞る、`
        + `cpus_for_each_syscall_buffer を 1 にする、slow output を外す。`;
  } else if(M.burst > 0.0015){
    cls = 'burst';
    txt = 'バースト起因のドロップ。平均は足りているので <b>buf_size_preset を上げれば効きます</b>。';
  } else {
    cls = 'ok';
    txt = 'ドロップなし。消費が入力に追いついています。';
  }
  elVerdict.className = 'verdict '+cls;
  elVerdict.innerHTML = txt;
}
function fmt(n){
  if(n >= 1e6) return (n/1e6).toFixed(2)+'M';
  if(n >= 1e3) return (n/1e3).toFixed(1)+'k';
  return Math.round(n).toString();
}

export {
  tagEls,
  applyRoleLocks,
  renderCampaignAll,
  updateTags,
  select,
  closeDrawer,
  drawer,
  drawMinimap,
  updateHud,
  updateVerdict,
  pickable
};
