/* Generated by the module split. See README §開発の分担. */
import * as THREE from 'three';
import { C } from './palette.js';
import { DISTRICTS, byId, hex6 } from './layout.js';
import { S, model, noise, hasCap } from './state.js';
import { camera, controls, renderer, scene, homeCam, homeView, goHome,
         HOME_TGT, flyTo, CITY_BOX } from './scene.js';
import { districtObjs, hitTargets } from './city.js';
import { setMode } from './controls.js';
import {
  GAME, DEPS, BUILD_ORDER, SIDES, ROLES, roleById, OWNER, LEVER_OWNER,
  canBuild, canUseLever, roleReport, verdictText, score,
  build, requestBuild, runAttack, setRole, setSide, setUiMode, onCampaignChange,
  SCENARIOS, activeScenario, activeEnv, activeChain, startScenario, goalStatus,
  allowedDeploys, allowedDrivers,
  projection, passResults, activeWaves
} from './campaign.js';
import { resetLog } from './log.js';
import { initMenu, plotTag, plotStyle } from './menu.js';
import { initAudio, setMuted, audioState } from './audio.js';
/* progress is read here and written in main.js: save.js decides the shape, this
   file only renders it. Nothing below computes a grade or a ladder itself. */
import { isCleared, bestFor, unlockedIds, progressSummary, storageOk } from './save.js';


/* ============================================================
   11. HTML labels anchored to 3D
   ============================================================ */
const tagEls = {};
DISTRICTS.forEach(d=>{
  const el = document.createElement('div');
  el.className = 'tag';
  el.innerHTML = `${d.tag}<span class="cnt">${d.n}</span>`;
  document.body.appendChild(el);
  tagEls[d.id] = el;
});

const v = new THREE.Vector3();
function updateTags(){
  for(const d of DISTRICTS){
    const o = districtObjs[d.id];
    v.copy(o.anchor).project(camera);
    const el = tagEls[d.id];
    const behind = v.z > 1;
    if(behind){ el.style.opacity = 0; continue; }
    const x = (v.x*0.5+0.5)*innerWidth;
    const y = (-v.y*0.5+0.5)*innerHeight;
    el.style.left = x+'px'; el.style.top = y+'px';
    const dist = camera.position.distanceTo(o.anchor);
    el.style.opacity = dist > 780 ? 0 : 1;
    el.classList.toggle('hot', S.hovered===d.id || S.selected===d.id);
    el.classList.toggle('dim',
      d.id==='sysdig' && S.mode!=='sysdig');
    /* A district that has not been built is drawn as a plot, not removed:
       menu.js owns what "not built yet" looks like. */
    const unbuilt = GAME.on && !GAME.built.has(d.id);
    plotTag(el, d, unbuilt);
  }
}


/* ============================================================
   12. hover / pick
   ============================================================ */
/* districts that are not built cannot be hovered or clicked */
const pickable = () => hitTargets.filter(h =>
  !GAME.on || GAME.built.has(h.userData.district.id));

const ray = new THREE.Raycaster();
const ndc = new THREE.Vector2();
const hoverCard = document.getElementById('hoverCard');
const hcT = hoverCard.querySelector('.hc-t');
const hcN = hoverCard.querySelector('.hc-n');
const hcS = hoverCard.querySelector('.hc-s');
const hcM = hoverCard.querySelector('.hc-m');
let mouse = {x:-1e4,y:-1e4};

renderer.domElement.addEventListener('pointermove', e=>{
  mouse.x = e.clientX; mouse.y = e.clientY;
  ndc.x = (e.clientX/innerWidth)*2-1;
  ndc.y = -(e.clientY/innerHeight)*2+1;
  ray.setFromCamera(ndc, camera);
  const hits = ray.intersectObjects(pickable(), false);
  const d = hits.length ? hits[0].object.userData.district : null;
  if((d?d.id:null) !== S.hovered){
    S.hovered = d ? d.id : null;
    if(d){
      hcT.textContent = d.hoverT;
      hcN.textContent = '+'+d.n;
      hcS.textContent = d.hoverS;
      hcM.innerHTML = d.hoverM.join('<br>');
      hoverCard.classList.add('show');
    } else hoverCard.classList.remove('show');
    renderer.domElement.style.cursor = d ? 'pointer' : 'grab';
  }
  if(S.hovered){
    const w = hoverCard.offsetWidth || 300, h = hoverCard.offsetHeight || 90;
    hoverCard.style.left = Math.min(innerWidth-w-14, e.clientX+18)+'px';
    hoverCard.style.top  = Math.max(12, e.clientY-h-16)+'px';
  }
});
renderer.domElement.addEventListener('pointerleave', ()=>{
  S.hovered=null; hoverCard.classList.remove('show');
});

let downAt = null;
renderer.domElement.addEventListener('pointerdown', e=>{ downAt={x:e.clientX,y:e.clientY,t:performance.now()}; });
renderer.domElement.addEventListener('pointerup', e=>{
  if(!downAt) return;
  const moved = Math.hypot(e.clientX-downAt.x, e.clientY-downAt.y);
  const quick = performance.now()-downAt.t < 420;
  downAt = null;
  if(moved > 6 || !quick) return;
  ndc.x = (e.clientX/innerWidth)*2-1;
  ndc.y = -(e.clientY/innerHeight)*2+1;
  ray.setFromCamera(ndc, camera);
  const hits = ray.intersectObjects(pickable(), false);
  if(hits.length) select(hits[0].object.userData.district.id);
  else closeDrawer();
});


/* ============================================================
   13. camera flight + drawer
   ============================================================ */

const drawer = document.getElementById('drawer');
function select(id){
  const d = DISTRICTS.find(x=>x.id===id);
  if(!d) return;
  S.selected = id;
  flyTo(d.cam, districtObjs[id].center);
  document.getElementById('dEyebrow').textContent = `stage ${d.n} — ${d.tag.toLowerCase()}`;
  document.getElementById('dTitle').textContent = d.jp;
  document.getElementById('dEn').textContent = d.en;
  const mHtml = d.metrics.map(([k,val])=>
    `<div class="metric"><div class="k">${k}</div><div class="v">${val}</div></div>`).join('');
  document.getElementById('dBody').innerHTML =
    `<div class="metrics">${mHtml}</div>` + d.body;
  document.getElementById('dBody').scrollTop = 0;
  drawer.classList.add('open');
  [...document.querySelectorAll('#tour button')].forEach(b=>
    b.classList.toggle('on', b.dataset.id===id));
  document.getElementById('hint').classList.add('gone');
  if(id==='sysdig') setMode('sysdig');
}
function closeDrawer(){
  S.selected=null; drawer.classList.remove('open');
  [...document.querySelectorAll('#tour button')].forEach(b=>b.classList.remove('on'));
}
document.getElementById('dclose').onclick = closeDrawer;

/* tour bar */
const tour = document.getElementById('tour');
DISTRICTS.forEach(d=>{
  const b = document.createElement('button');
  b.dataset.id = d.id;
  b.innerHTML = `<span class="n">${d.n}</span>${d.jp}`;
  b.onclick = ()=>select(d.id);
  tour.appendChild(b);
});
const reset = document.createElement('button');
reset.innerHTML = `<span class="n">↺</span>全体`;
reset.onclick = ()=>{ closeDrawer(); goHome(); };
tour.appendChild(reset);


/* ============================================================
   14d. CAMPAIGN PANEL — the receiving side
   ------------------------------------------------------------
   campaign.js decides; this renders. It subscribes to the change feed and
   redraws, so the two can be worked on without sharing a line. Every DOM
   reference for the campaign lives here and nowhere else.
   ============================================================ */
const elCmp   = document.getElementById('campaign');
const elEyebrow = elCmp && elCmp.querySelector('.cmp-eyebrow');
const elTitle = document.getElementById('cmpTitle');
const elSides = document.getElementById('cmpSides');
const elRoles = document.getElementById('cmpRoles');
const elHint  = document.getElementById('cmpHint');
const elBuild = document.getElementById('cmpBuild');
const elRun   = document.getElementById('cmpRun');
const elRes   = document.getElementById('cmpResults');
const elScore = document.getElementById('cmpScore');
const elScoreOf = document.getElementById('cmpScoreOf');

const DEFAULT_MISSION = '検知パイプラインを一から建てる';

/* labels for things the rules layer only names. campaign.js hands over keys and
   numbers; the sentences the player reads are written here, and the sentences a
   scenario needs are written in the scenario. Neither lives in the logic. */
const GOAL_LBL = {
  detect: (i) => `検知 ${i.actual}/${i.of} — ${i.target} 段以上`,
  contain:(i) => `封じ込め — ${i.actual ? '成立' : '未成立'}`,
  asks:   (i) => `他チームへの依頼 ${i.actual}件 — ${i.target}件まで`,
  drop:   (i) => `ドロップ ${i.actual}% — ${i.target}% まで`,
  /* the wave layer's four. `runs` is passes started, so the ceiling is on brute
     force; `buried` is the share of alerts the SOC queue lost; `pass` is how much
     of the traffic reaches the rule engine at all; `load` exists so a scenario
     can say "solve it at the load you were handed" instead of letting the
     slider make the symptom go away. */
  runs:   (i) => `試行 ${i.actual}回目 — ${i.target}回まで`,
  buried: (i) => `アラートの埋没 ${i.actual}% — ${i.target}% まで`,
  pass:   (i) => `ルールに届く割合 ${i.actual}% — ${i.target}% 以上`,
  load:   (i) => `NODE LOAD ×${i.actual} — 渡された ×${i.target} を下げずに`
};

/* the goal as an INSTRUCTION rather than as a score, for the pre-run preview:
   before a pass there is no `actual` worth showing, and "依頼は3件まで" is the
   part the player needed before spending the fourth one. */
const GOAL_ASK = {
  detect: (i) => `${i.target} 段以上を検知する`,
  contain:( ) => '封じ込めを成立させる',
  asks:   (i) => `他チームへの依頼は ${i.target}件まで`,
  drop:   (i) => `ドロップは ${i.target}% まで`,
  runs:   (i) => `試行は ${i.target}回まで`,
  buried: (i) => `アラートの埋没は ${i.target}% まで`,
  pass:   (i) => `ルールに届く割合を ${i.target}% 以上に保つ`,
  load:   (i) => `NODE LOAD ×${i.target} を下げない`
};

/* lever group -> the panel it lives in. campaign.js names the group; only this
   file knows which node that is. `load` is here because a scenario hands you a
   load as part of the situation: with the slider free, two of the drop scenarios
   were solved by dragging it left, which is not a diagnosis. campaign.js decides
   whether it is locked (loadLocked / canUseLever); this only knows the node. */
const LEVER_NODE = {
  deploy:'#deploySeg', driver:'#drvSeg', tuning:'.panel.tune', stack:'#modeSeg',
  load:'#loadWrap'
};

/* The hint carries scenario prose now, and prose has no length limit while the
   panel does — 1280×720 leaves the column 420px in total, which is the floor the
   game supports. So the hint gets a floor (a setup that collapses to one clipped
   line is not readable) and a ceiling (a long one must not push the build list or
   the run button out of the panel), and the two lists give up the difference.
   Beyond the ceiling the hint scrolls, and nothing below it moves. */
Object.assign(elHint.style, {flex:'0 0 auto', minHeight:'48px', maxHeight:'104px',
                             overflowY:'auto'});
elBuild.style.minHeight = '68px';

/* The results reserve no room until there are results. Before the first run
   that space belongs to the build list, which is the only thing on screen that
   says what you may do next — and at 1280×720 it was showing 68px of a 252px
   list, so the last stage (08 Sysdig Secure, the correct move in more than one
   scenario) sat permanently below the fold. */
function sizeResults(){
  const has = !!(GAME.results && GAME.reveal);
  elRes.style.minHeight = has ? '76px' : '0px';
  elRes.style.flex      = has ? '1 1 auto' : '0 0 auto';
}
sizeResults();

/* The panel and the minimap are both fixed to the left edge, one from the top
   and one from the bottom, so at the supported minimum of 1280×720 they overlap
   — the minimap paints last and lands on top of the run button, which makes it
   unclickable. Nothing in the CSS can know how much room there is, so measure.
   When there is not enough for both, the panel wins: it is the game, and the
   minimap is a convenience. Visibility rather than display, so the element
   still has a box to measure and the decision cannot oscillate. */
/* head + the two chip rows + a full-height hint + the build list + the run
   button + a results list, measured. Below this the panel has to take the
   minimap's space rather than shrink the hint into an unreadable strip. */
const PANEL_NEEDS = 480;
const elMini = document.getElementById('minimap');

function fitCampaignPanel(){
  if(!elCmp.classList.contains('on')){
    elCmp.style.maxHeight = '';
    if(elMini) elMini.style.visibility = '';
    return;
  }
  const top = elCmp.getBoundingClientRect().top;
  const room = (elMini ? elMini.getBoundingClientRect().top : innerHeight) - top - 12;
  const tight = room < PANEL_NEEDS;
  if(elMini) elMini.style.visibility = tight ? 'hidden' : '';
  elCmp.style.maxHeight = Math.round(tight ? innerHeight - top - 20 : room) + 'px';
}

/* ============================================================
   §fitRightColumn — the levers, the symptoms and the evidence
   ------------------------------------------------------------
   THE BUG THIS EXISTS FOR. The right edge carries two stacks anchored to
   opposite corners: #topRight (HUD, node load, TUNING, legend) from the top, and
   #consoleWrap from the bottom. Nothing measured either, so at 1280x720 the
   console's 215px box landed on top of the bottom half of TUNING and — because
   an overlay in .ui.interactive takes pointer events — ate every click aimed at
   it. `buf_size_preset`, `cpus_for_each_buffer`, `syscall_event_drops.actions`,
   `reset` and the `slow output` checkbox were all unreachable. `slow-output`'s
   only correct move is that checkbox, so the scenario was unsolvable in the
   default state at the resolution we call the supported minimum, while two
   WRONG levers still scored it as cleared. That is not a difficulty problem.

   `#consoleBox` is now transparent to the mouse (index.html), which alone makes
   the levers clickable and also gives the tour bar its buried buttons back. But
   a lever you cannot SEE is still a lever you cannot use, so the two stacks are
   also measured against each other here, and the shortfall is spent in a stated
   order:

     1. the legend goes.      A colour key. It teaches nothing you act on, and at
                              720p it was already below the fold — this only
                              makes that a decision instead of an accident.
     2. the console shrinks.  Down to CLOG_FLOOR and no further.
     3. the console goes.     Bar only. The toggle is still there, and opening it
                              now overlays without stealing a single click.

   HUD and TUNING are never touched. Same principle as fitCampaignPanel: when
   two things cannot both fit, the one that is the game wins.
   ============================================================ */
const elRight   = document.getElementById('topRight');
const elLegend  = document.getElementById('legendPanel');
const elConWrap = document.getElementById('consoleWrap');
const elConBox  = document.getElementById('consoleBox');
const elCbar    = document.querySelector('#consoleBox .cbar');
const elClog    = document.getElementById('clog');
const elCtog    = document.getElementById('ctoggle');

/* The log is a ticker — #clog is justify-content:flex-end, so what survives a
   shrink is the newest lines, which is the part anyone reads. Three of them plus
   its padding is thin but it is still evidence; below that it is a decoration,
   and a decoration is not worth covering a lever for. At 1280x720 this is what
   the right edge can actually spare, and it grows back toward CLOG_FULL as soon
   as the window is taller. */
const CLOG_FLOOR = 48;
const CLOG_FULL  = 186;

/* the fixed offsets the two stacks are pinned with, from index.html */
const EDGE = 20;      // #topRight top / #consoleWrap bottom
const COLGAP = 10;    // gap between panels inside #topRight
const WRAPGAP = 8;    // #consoleWrap's own gap, box -> toggle
const CLEAR = 8;      // breathing room between the column and the console

/* docked, the console floats over the city instead of under the column, so the
   only thing bounding it is taste. Seven lines. */
const CLOG_DOCKED = 132;

function fitRightColumn(){
  if(!elRight || !elClog || !elConBox) return;

  /* Measure the roomiest state, so what comes out is a property of the layout
     rather than of the last decision this function made. */
  if(elLegend) elLegend.hidden = false;
  elConBox.classList.add('open');
  elConWrap.classList.remove('docked');
  document.body.classList.remove('condocked');
  elClog.style.setProperty('--clogh', CLOG_FULL + 'px');

  const columnH = () => {
    let h = 0;
    for(const p of elRight.children){
      if(p.hidden) continue;
      h += p.getBoundingClientRect().height + COLGAP;
    }
    return h ? h - COLGAP : 0;
  };
  const barH = elCbar ? Math.round(elCbar.getBoundingClientRect().height) : 29;
  const togH = elCtog ? Math.round(elCtog.getBoundingClientRect().height) : 34;

  /* what is left for the console BOX once the column, both edges, the toggle
     and the gaps have taken theirs */
  const boxRoom = () =>
    innerHeight - EDGE*2 - CLEAR - WRAPGAP - togH - columnH();

  /* 1. everything fits, legend included */
  if(boxRoom() >= barH + CLOG_FULL) return;

  /* 2. the legend is the first thing spent */
  if(elLegend){
    elLegend.hidden = true;
    if(boxRoom() >= barH + CLOG_FULL) return;
  }

  /* 3. shrink the log to what is left, down to the floor */
  const h = Math.floor(boxRoom() - barH);
  if(h >= CLOG_FLOOR){ elClog.style.setProperty('--clogh', h + 'px'); return; }

  /* 4. the right edge cannot hold a legible log at all — which is the case at
        1280x720, by ~95px. Move it to the bottom strip rather than choosing
        between the evidence and the levers: see the .docked note in index.html. */
  elConWrap.classList.add('docked');
  document.body.classList.add('condocked');
  elClog.style.setProperty('--clogh', CLOG_DOCKED + 'px');
}
addEventListener('resize', fitRightColumn);

/* The column's height is not constant: the verdict is one or two lines depending
   on the failure mode, and controls.js rebuilds the DEPLOY / DRIVER rows when the
   environment changes. So re-fit when it actually moved, and not on a timer —
   fitRightColumn() resets to the roomiest state to measure, and running that
   every frame would flash the legend. Neither of the two things it changes is in
   the signature, so this cannot oscillate. */
let fitSig = '';
function maybeFitRight(){
  const tune = document.querySelector('.panel.tune');
  const sig = [innerHeight,
               elVerdict ? Math.round(elVerdict.getBoundingClientRect().height) : 0,
               tune ? Math.round(tune.getBoundingClientRect().height) : 0].join('/');
  if(sig === fitSig) return;
  fitSig = sig;
  fitRightColumn();
}

function setHint(html, good){
  elHint.className = 'cmp-hint' + (good ? ' good' : '');
  elHint.innerHTML = html;
  elHint.scrollTop = 0;
}

/* ---- storage ------------------------------------------------------------
   file://, private mode and a full quota all refuse localStorage, and save.js
   answers that by demoting itself to an in-memory store that behaves the same
   for the rest of the session. So this is not an error and must not read as
   one: the game is unaffected, only the *outliving the tab* part is gone. Said
   once, and only when it is true — which is also why it costs no height in the
   normal case: the node is hidden, so the panel is the size it always was. */
const elSaveNote = document.getElementById('cmpSaveNote');
if(elSaveNote) elSaveNote.hidden = storageOk();

/* the eyebrow already carries who you are, and it has room to spare, so the
   campaign count goes there rather than into a row of its own — at 1280x720
   every new line in this column comes out of the build list. */
function setEyebrow(){
  if(!elEyebrow) return;
  const role = GAME.role ? roleById(GAME.role) : null;
  const p = progressSummary(scenarioOrder());
  elEyebrow.textContent = ['mission', role ? role.chip : '',
                           p.total ? `${p.cleared}/${p.total} クリア` : '']
                          .filter(Boolean).join(' · ');
}

/* ---- a lever you do not own is visible but untouchable ----
   Two different reasons a lever can be shut, and the veil has to say which:
   another ROLE owns it (`sre 担当`), or the SCENARIO owns it — NODE LOAD has no
   owner in LEVER_OWNER at all, because the load is the situation you were handed
   rather than anybody's decision, and goal.lockLoad says so. */
function applyRoleLocks(){
  for(const [group, sel] of Object.entries(LEVER_NODE)){
    const el = document.querySelector(sel);
    if(!el) continue;
    const lock = !canUseLever(group);
    el.classList.toggle('dutylock', lock);
    if(!lock){ delete el.dataset.owner; continue; }
    const owner = roleById(LEVER_OWNER[group]);
    el.dataset.owner = owner ? `${owner.chip} 担当` : 'シナリオ固定';
  }
}

/* ---- scenario picker ------------------------------------------------------
   A select rather than chips: the content lane is unbounded, so the control has
   to survive N scenarios. It shares the sides row so the panel gains no height
   — at 1280×720 there is none to spare. */
const elScen = document.createElement('select');
elScen.id = 'cmpScen';
Object.assign(elScen.style, {
  font:'inherit', fontFamily:'var(--font-mono)', fontSize:'9.5px',
  padding:'4px 6px', borderRadius:'7px', border:'1px solid var(--grey-10)',
  background:'transparent', color:'var(--grey-50)', maxWidth:'150px', cursor:'pointer'
});
elScen.onchange = ()=> startScenario(elScen.value);

/* the ordered id list save.js takes as an argument, so it can stay import-free */
const scenarioOrder = () => SCENARIOS.map(s => s.id);

/* one option's label: cleared gets a tick and the best run's numbers, locked
   says so in words rather than only being grey — "why can I not pick this" is
   the actual question, and a <select> has no room for a tooltip. */
function scenarioLabel(s, open){
  const b = bestFor(s.id);
  return (isCleared(s.id) ? '✓ ' : '')
       + s.title
       + (b ? `  (${b.detect}/${b.of}・依頼${b.asks}・${b.attempts}回目)` : '')
       + (open ? '' : '  — 未解放');
}

function renderScenarioPicker(){
  const cur = activeScenario();
  const order = scenarioOrder();
  /* the ladder: first is always open, clearing one opens the next, cleared
     stays open. save.js owns that rule; this only asks. */
  const open = unlockedIds(order);
  elScen.innerHTML = '';
  SCENARIOS.forEach(s=>{
    const o = document.createElement('option');
    const unlocked = open.includes(s.id) || !!(cur && cur.id === s.id);
    o.value = s.id;
    o.textContent = scenarioLabel(s, unlocked);
    o.disabled = !unlocked;
    if(cur && cur.id === s.id) o.selected = true;
    elScen.appendChild(o);
  });
  elScen.disabled = SCENARIOS.length < 2;
  /* the closed select is 150px of a full column, so the whole label — which is
     wider than that — is also on the hover */
  const p = progressSummary(order);
  elScen.title = (cur ? scenarioLabel(cur, true) + '\n' : '')
               + `${p.total} 本中 ${p.cleared} 本クリア（選べるのは ${p.unlocked} 本）`;
}

/* ---- levers: reflect what the scenario handed over, and what it forbids ----
   controls.js owns these widgets while the player drives them; when a scenario
   sets them, somebody has to push the values back into the DOM, and that is
   this side of the split. */
function syncLeverWidgets(){
  const on = (sel, attr, val)=> document.querySelectorAll(sel+' button').forEach(b=>
    b.classList.toggle('on', b.dataset[attr] === String(val)));
  on('#segSet','set',S.tune.syscallSet);
  on('#segCpu','cpu',S.tune.cpusPerBuf);
  on('#segAct','act',S.tune.dropAction);
  on('#deploySeg','dep',S.deploy);
  on('#drvSeg','drv',S.driver);
  on('#modeSeg','mode',S.mode);
  const buf = document.getElementById('rngBuf');
  if(buf) buf.value = S.tune.bufPreset;
  const slow = document.getElementById('chkSlow');
  if(slow) slow.checked = S.tune.slowOutput;
  const lr = document.getElementById('loadRange');
  if(lr) lr.value = Math.round(S.load*100);
  const lv = document.getElementById('loadVal');
  if(lv) lv.textContent = '×'+S.load.toFixed(1);

  /* an environment forbids what it has no room for: no cluster, no DaemonSet;
     no node of your own, no kernel module. Not a rule of the game — a fact
     about the place, so the button is simply not available. */
  const deploys = allowedDeploys(), drivers = allowedDrivers();
  const gate = (sel, attr, allowed)=>
    document.querySelectorAll(sel+' button').forEach(b=>{
      const ok = !GAME.on || allowed.includes(b.dataset[attr]);
      b.disabled = !ok;
      b.style.opacity = ok ? '' : '.35';
      b.style.cursor  = ok ? '' : 'not-allowed';
    });
  gate('#deploySeg','dep',deploys);
  /* where there is no kernel path controls.setDeploy has already closed the
     driver row, and it is closed for a stronger reason than ours */
  if(hasCap('kernelPath')) gate('#drvSeg','drv',drivers);
}

/* ---- side picker: defence is playable, offence is shown as not yet ---- */
function renderSides(){
  elSides.innerHTML = '';
  elSides.appendChild(elScen);
  SIDES.forEach(sd=>{
    const b = document.createElement('button');
    b.textContent = sd.chip;
    if(GAME.side === sd.id) b.className = 'on';
    if(!sd.enabled){
      b.disabled = true;
      b.title = sd.jp + '— まだ実装されていません';
    } else b.onclick = ()=> setSide(sd.id);
    elSides.appendChild(b);
  });
  const auto = document.createElement('span');
  auto.className = 'ask';
  auto.textContent = GAME.side === 'defense' ? '攻撃 Auto' : '';
  elSides.appendChild(auto);
}

/* ---- role picker ---- */
function renderRoles(){
  elRoles.innerHTML = '';
  const add = (id, label, color)=>{
    const b = document.createElement('button');
    if(GAME.role === id) b.className = 'on';
    if(color){
      const i = document.createElement('i');
      i.style.background = color;
      b.appendChild(i);
    }
    b.appendChild(document.createTextNode(label));
    /* a scenario can fix the role — then this is a readout, not a choice */
    if(GAME.roleLocked){
      b.disabled = true;
      b.style.opacity = GAME.role === id ? '' : '.35';
      b.style.cursor = 'default';
      b.title = 'このシナリオでは役割が固定されています';
    } else b.onclick = ()=> setRole(id);
    elRoles.appendChild(b);
  };
  add(null, '全役');
  ROLES.forEach(r => add(r.id, r.chip, r.color));
  const ask = document.createElement('span');
  ask.className = 'ask';
  const env = activeEnv();
  ask.textContent = [env ? `${env.jp}${env.nodes ? ` · ${env.nodes}ノード` : ''}` : '',
                     GAME.asks ? `依頼 ${GAME.asks}件` : ''].filter(Boolean).join(' · ');
  elRoles.appendChild(ask);
}

/* ---- build list: rows carry their owner, other teams' stages are asked for ---- */
function renderBuildList(){
  elBuild.innerHTML = '';
  BUILD_ORDER.forEach(id=>{
    const d = byId(id);
    const owner = roleById(OWNER[id]);
    const done = GAME.built.has(id), open = !done && canBuild(id);
    const mine = !GAME.role || !owner || GAME.role === owner.id;

    const row = document.createElement('div');
    row.className = 'cmp-row ' + (done ? 'done' : open ? '' : 'locked')
                  + (owner && GAME.role === owner.id ? ' mine' : '');
    row.innerHTML = `<span class="n">${d.n}</span><span class="nm">${d.jp}</span>`;

    if(owner){
      const badge = document.createElement('span');
      badge.className = 'own';
      badge.textContent = owner.chip;
      badge.style.borderLeftColor = owner.color;
      row.appendChild(badge);
    }

    if(done) row.insertAdjacentHTML('beforeend', '<span class="tick">✓</span>');
    else if(open){
      const b = document.createElement('button');
      if(mine){
        b.textContent = '建設';
        b.onclick = ()=> build(id);
      } else {
        b.textContent = `${owner.chip} に依頼`;
        b.className = 'askbtn';
        b.onclick = ()=> requestBuild(id);
      }
      row.appendChild(b);
    } else {
      row.insertAdjacentHTML('beforeend',
        `<span class="lk">要 ${DEPS[id].map(k=>byId(k).jp).join('・')}</span>`);
    }
    elBuild.appendChild(row);
  });
  keepActionableVisible();
}

/* The list is in dependency order, which is the teaching, so the row you can
   press is wherever the pipeline says it is — for 08 Sysdig Secure that is
   last. If the scroller cannot show everything, it has to show *that* row:
   a build list scrolled past the only legal move reads as "no options". */
function keepActionableVisible(){
  const more = elBuild.scrollHeight > elBuild.clientHeight + 1;
  elBuild.classList.toggle('more', more);
  if(!more) return;
  const act = elBuild.querySelector('.cmp-row:not(.done):not(.locked)');
  if(!act) return;
  const r = act.getBoundingClientRect();
  const view = elBuild.getBoundingClientRect();
  if(r.bottom > view.bottom)  elBuild.scrollTop += r.bottom - view.bottom + 4;
  else if(r.top < view.top)   elBuild.scrollTop -= view.top - r.top + 4;
}

/* ---- your own best run -----------------------------------------------------
   main.js writes the clear, on the same 'reveal' event this file renders. It
   subscribed to the feed after us, so at render time bestFor() still holds the
   PREVIOUS best — which is exactly the number "new best" is measured against.
   So: snapshot it, then read again one turn later, once the write has happened.
   The difference is the answer, and nothing here reimplements save.js's ranking
   (detections, then asks, then drops, then attempts) — a second copy of that
   order would drift from the one that decides what is stored.
   If the order of the two listeners ever flips, both reads return the new best
   and the panel says 自己ベスト instead of 自己ベスト更新. Wrong word, right
   numbers: it degrades, it does not lie about the grade. */
let bestNote = null;      // { id, best, first, improved }

const sameGrade = (a, b) => a.detect === b.detect && a.asks === b.asks
                         && a.dropPct === b.dropPct && a.attempts === b.attempts;

function captureBest(){
  bestNote = null;
  const sc = activeScenario(), st = goalStatus();
  if(!sc || !st || !st.cleared) return;
  const id = sc.id, prev = bestFor(id);
  setTimeout(()=>{
    const now = bestFor(id);
    if(!now) return;         /* the clear was not recorded — say nothing */
    bestNote = { id, best:now, first:!prev,
                 improved:!prev || !sameGrade(prev, now) };
    const cur = activeScenario();
    if(!cur || cur.id !== id) return;
    /* clearing this one may have opened the next, so the picker is stale too */
    renderScenarioPicker();
    setEyebrow();
    renderResults();
    renderDebrief();
  }, 0);
}

/* At 1280x720 the results scroller is 78px tall and holds ~1000px, and it is
   pinned to the bottom to follow the reveal — so a line appended to the report
   is a line the player has to go looking for. The grade is the one thing they
   came back for, so it is ALSO stated in the hint, which has a fixed place near
   the top of the panel and is already where the verdict lands. */
function bestLine(){
  if(!bestNote) return '';
  const b = bestNote.best;
  const head = bestNote.first ? '初クリア'
             : bestNote.improved ? '自己ベスト更新' : '自己ベスト';
  return `<br><b>${head}</b> — 検知 ${b.detect}/${b.of} · 依頼 ${b.asks}件`
       + ` · ${b.attempts}回目`;
}

/* ---- did you clear it, and the one misdiagnosis this scenario is about ---- */
function renderScenarioReport(){
  const sc = activeScenario();
  const st = goalStatus();
  if(!sc || !st) return;

  const wrap = document.createElement('div');
  wrap.className = 'rrep';
  wrap.innerHTML = `<h5>${st.cleared ? 'クリア' : '未クリア'}</h5>`;
  st.items.forEach(i=>{
    const row = document.createElement('div');
    row.className = 'rrow ' + (i.ok ? 'clean' : 'blamed');
    row.style.borderLeftColor = i.ok ? 'var(--lumin)' : 'var(--red-ui)';
    row.innerHTML = `<span class="rn">${i.ok ? '達成' : '未達'}</span>`+
                    `<span class="rv">${GOAL_LBL[i.key] ? GOAL_LBL[i.key](i) : i.key}</span>`;
    wrap.appendChild(row);
  });
  /* the grade that survives the tab closing, and what it just opened */
  if(bestNote && bestNote.id === sc.id){
    const b = bestNote.best;
    const row = document.createElement('div');
    row.className = 'rrow ' + (bestNote.improved ? 'clean' : '');
    row.style.borderLeftColor = bestNote.improved ? 'var(--lumin)' : 'var(--grey-20)';
    row.innerHTML =
      `<span class="rn">${bestNote.first ? '初クリア'
                        : bestNote.improved ? '自己ベスト更新' : '自己ベスト'}</span>`+
      `<span class="rv">検知 ${b.detect}/${b.of} · 依頼 ${b.asks}件 · ${b.attempts}回目`+
      `${b.clears > 1 ? ` · ${b.clears}回クリア` : ''}</span>`;
    wrap.appendChild(row);

    const p = progressSummary(scenarioOrder());
    const nx = p.next ? SCENARIOS.find(s => s.id === p.next) : null;
    const prog = document.createElement('div');
    prog.className = 'rnote';
    prog.innerHTML = `<b>進行:</b> ${p.total} 本中 ${p.cleared} 本クリア。`
      + (p.complete ? '全シナリオ制覇。'
         : nx ? `次は「${nx.title}」が選べます。` : '')
      + (storageOk() ? ''
         : '<br>この環境では保存できないので、この記録はタブを閉じるまでです。');
    wrap.appendChild(prog);
  }

  const ins = document.createElement('div');
  ins.className = 'rnote';
  ins.innerHTML = `<b>踏みがちな読み:</b> ${sc.insight.wrong}<br><b>実際は:</b> ${sc.insight.truth}`;
  wrap.appendChild(ins);
  elRes.appendChild(wrap);
}

/* ---- results, with the role each miss is charged to ---- */
function renderRoleReport(){
  const rep = roleReport();
  const wrap = document.createElement('div');
  wrap.className = 'rrep';
  wrap.innerHTML = '<h5>役割別</h5>';
  rep.roles.forEach(r=>{
    const row = document.createElement('div');
    row.className = 'rrow ' + (r.misses ? 'blamed' : r.built === r.owns ? 'clean' : '');
    row.style.borderLeftColor = r.color;
    /* 全役 means every one of these is you. roleReport() derives `mine` from
       GAME.role, which is null there, so nothing was marked and the tutorial
       read its own misses as somebody else's. */
    const mine = r.mine || !GAME.role;
    /* the chip is how this role is named everywhere else in the panel — the
       badge on a build row, the 依頼 button, the lever veil. Showing it beside
       the full name here is what stops the player needing a lookup table. */
    const chip = (roleById(r.id) || {}).chip || '';
    row.innerHTML =
      `<span class="rn">${chip ? chip + ' · ' : ''}${r.jp}${mine ? '（あなた）' : ''}</span>`+
      `<span class="rv">${r.built}/${r.owns} 建設${r.misses ? ` · 見逃し ${r.misses}` : ''}</span>`;
    wrap.appendChild(row);
  });
  rep.notes.forEach(html=>{
    const n = document.createElement('div');
    n.className = 'rnote';
    n.innerHTML = html;
    wrap.appendChild(n);
  });
  elRes.appendChild(wrap);
}

function renderResults(){
  elRes.innerHTML = '';
  elScore.textContent = score();
  sizeResults();
  if(!GAME.results){ keepActionableVisible(); return; }

  /* WHICH WAVE, AND WHICH STEP OF THE WHOLE ATTACK.
     GAME.results holds the wave on screen, not the pass, so numbering rows from
     its own index restarted at "step 1" when wave 2 arrived — while the score
     above it kept counting the pass. passResults() is the pass, so the offset is
     everything it already holds minus what is being revealed right now. */
  const waves = activeWaves();
  const shown = Math.min(GAME.reveal, GAME.results.length);
  const step0 = Math.max(0, passResults().length - shown);
  if(waves.length > 1 && GAME.wave >= 0){
    const h = document.createElement('div');
    h.className = 'cmp-wave';
    h.textContent = `波 ${GAME.wave+1} / ${waves.length}`
                  + (waves[GAME.wave] && waves[GAME.wave].jp ? ` · ${waves[GAME.wave].jp}` : '');
    elRes.appendChild(h);
  }

  GAME.results.slice(0, GAME.reveal).forEach((r,i)=>{
    const el = document.createElement('div');
    el.className = 'cmp-res ' + (r.caught ? 'hit' : 'miss');
    el.innerHTML =
      `<span class="st">${r.response ? '対処' : (step0+i+1)+'段目'} · ${r.caught ? '検知' : '見逃し'}</span>`+
      `<span class="ac">${r.jp}</span>`+
      `<span class="rl">${r.rule}</span>`+
      (r.why ? `<span class="wy">${r.why}</span>` : '');
    const b = roleById(r.blame);
    if(b){
      const s = document.createElement('span');
      s.className = 'bl';
      s.style.borderLeftColor = b.color;
      s.textContent = `起因 · ${b.jp}`;
      el.appendChild(s);
    }
    elRes.appendChild(el);
  });
  const done = GAME.reveal >= GAME.results.length;
  if(done){
    const v = verdictText();
    if(v) setHint(v.html + bestLine(), v.good);
    renderScenarioReport();
    renderRoleReport();
  }
  elRun.disabled = !done;
  elRes.scrollTop = elRes.scrollHeight;      /* follow the reveal */
  /* the results just took their space back, so re-check the build list against
     the height it actually has now */
  keepActionableVisible();
}

/* ============================================================
   §goal — what you are being asked for, BEFORE you are scored on it
   ------------------------------------------------------------
   goalStatus() is null until the pass is over, and renderScenarioReport() only
   draws into the results, so on entry the panel showed the title, the blurb, the
   build list and a run button — and nothing about what winning is. `依頼は3件
   まで` in particular is unrecoverable once spent (GAME.asks never goes down),
   and players were spending the fourth without ever having been told there was a
   third. campaign.js §projection() answers this without running anything:
   evaluate() is pure, so the same scoreGoal() that grades the pass can grade the
   board as it stands.
   The strip is always on screen, not just on entry, because setHint() gets
   overwritten by every build unlock — a goal you are shown once and then lose is
   the same bug in slow motion.
   ============================================================ */
const elGoal = document.getElementById('cmpGoal');

function renderGoal(){
  if(!elGoal) return;
  const sc = activeScenario();
  if(!sc || !GAME.on){ elGoal.hidden = true; return; }
  /* the pass is scored: the results and the debrief own the verdict, and this
     strip goes back to stating the ask so a re-run knows what it is chasing */
  const st = goalStatus() || projection();
  if(!st || !st.items.length){ elGoal.hidden = true; return; }
  elGoal.hidden = false;
  const live = !!goalStatus();
  elGoal.innerHTML = `<span class="gl">${live ? '結果' : '目標'}</span>`
    + st.items.map(i=>{
        const txt = live
          ? (GOAL_LBL[i.key] ? GOAL_LBL[i.key](i) : i.key)
          : (GOAL_ASK[i.key] ? GOAL_ASK[i.key](i) : i.key);
        /* before a run, `ok` is a projection: it says "as things stand", which is
           a hint and not a score, so it is marked differently from a result */
        return `<span class="gi ${i.ok ? 'met' : 'unmet'}">${txt}</span>`;
      }).join('');
  elGoal.title = (live ? '達成状況' : 'いまの盤面での見込み')
    + '\n' + st.items.map(i => (i.ok ? '○ ' : '× ')
      + (GOAL_ASK[i.key] ? GOAL_ASK[i.key](i) : i.key)).join('\n');
}

/* ============================================================
   §page — the full-page shell, and the debrief that lives in it
   ------------------------------------------------------------
   See the markup note in index.html. What changed and why:

   The debrief was an overlay card because the panel could not hold it. Pages may
   now be as large as they need (GAME-DESIGN §5.5), so it is a page — opaque,
   860px of measure, and it scrolls as a page rather than as a 78px window.

   openPage() / closePage() are deliberately generic. The setup pages coming next
   are the same header, body and footer with different content, and the reason
   this is a shell is that otherwise each of them invents its own.

   The rule about WHEN each part appears has not changed:
     always      cleared / not cleared, every goal row with its numbers, and what
                 got past you — the not-cleared case needs something to act on
     on a clear  the misdiagnosis (insight.wrong / insight.truth) and the grade
   The insight is the answer to the question the scenario asked, so it is a reward
   for having answered it, not something the game says on the way in.
   ============================================================ */
const elPage  = document.getElementById('page');
const elPgKick  = document.getElementById('pgKick');
const elPgStep  = document.getElementById('pgStep');
const elPgTitle = document.getElementById('pgTitle');
const elPgStamp = document.getElementById('pgStamp');
const elPgBody  = document.getElementById('pgBody');
const elPgNext  = document.getElementById('pgNext');
const elPgAgain = document.getElementById('pgAgain');
const elPgNote  = document.getElementById('pgNote');
const elToDebrief = document.getElementById('toDebrief');

/* which page is open, so the feed knows whether to redraw it */
let pageOpen = null;

function closePage(){
  pageOpen = null;
  if(elPage) elPage.classList.remove('show');
}
function openPage(name){
  if(!elPage) return;
  pageOpen = name;
  elPage.classList.add('show');
  elPage.scrollTop = 0;      /* a page always opens at its top */
}

/* one wordmark asset in the document, cloned rather than duplicated — same
   discipline menu.js uses for the entrance cards */
if(elPage){
  const mark = document.querySelector('.brandbar svg');
  const head = elPage.querySelector('.pghead');
  if(mark && head) head.insertBefore(mark.cloneNode(true), head.firstChild);
}

/* ---- the debrief ---------------------------------------------------------- */
function hideDebrief(){ if(pageOpen === 'debrief') closePage(); }

function renderDebrief(){
  if(pageOpen !== 'debrief') return;
  const sc = activeScenario(), st = goalStatus();
  if(!sc || !st){ closePage(); return; }

  elPgKick.textContent = 'debrief';
  elPgStep.textContent = `試行 ${GAME.runs} 回目 · ${activeWaves().length} 波`;
  elPgTitle.innerHTML = st.cleared
    ? `<b>${sc.title}</b> を通した。`
    : `<b>${sc.title}</b> は、まだ通っていない。`;
  elPgStamp.className = 'pgstamp ' + (st.cleared ? 'win' : 'lose');
  elPgStamp.textContent = st.cleared ? 'クリア' : '未クリア';

  const html = [];

  html.push('<div class="pgsec">この回の採点</div>');
  html.push('<div class="pggrid">');
  for(const i of st.items){
    const txt = GOAL_LBL[i.key] ? GOAL_LBL[i.key](i) : i.key;
    html.push(`<div class="rrow ${i.ok ? 'clean' : 'blamed'}"`
      + ` style="border-left-color:${i.ok ? 'var(--lumin)' : 'var(--red-ui)'}">`
      + `<span class="rn">${i.ok ? '達成' : '未達'}</span>`
      + `<span class="rv">${txt}</span></div>`);
  }
  html.push('</div>');

  /* what got past you. On a page this can say the whole reason, which is the
     part the 81px window was eating. */
  const missed = passResults().filter(r => !r.caught);
  if(missed.length){
    html.push(`<div class="pgsec">抜けた ${missed.length} 段 — なぜ抜けたか</div>`);
    for(const r of missed){
      const b = roleById(r.blame);
      html.push('<div class="pgmiss">'
        + `<b>${r.jp}</b>${r.rule ? ` <span style="color:var(--grey-30)">${r.rule}</span>` : ''}`
        + (r.why ? `<br>${r.why}` : '')
        + (b ? `<span class="who">起因 · ${b.jp}</span>` : '')
        + '</div>');
    }
  }

  /* THE PAYLOAD — only once it has been earned */
  if(st.cleared && sc.insight){
    html.push('<div class="pgsec">この現場が誘う誤診</div>');
    html.push('<div class="pgins">'
      + `<span class="q"><span class="lbl">踏みがちな読み</span>${sc.insight.wrong}</span>`
      + `<span class="lbl">実際は</span>${sc.insight.truth}</div>`);
  }

  if(bestNote && bestNote.id === sc.id){
    const b = bestNote.best;
    const head = bestNote.first ? '初クリア'
               : bestNote.improved ? '自己ベスト更新' : '自己ベスト';
    html.push('<div class="pgsec">記録</div>');
    html.push(`<div class="rrow ${bestNote.improved ? 'clean' : ''}"`
      + ` style="border-left-color:${bestNote.improved ? 'var(--lumin)' : 'var(--grey-20)'}">`
      + `<span class="rn">${head}</span>`
      + `<span class="rv">検知 ${b.detect}/${b.of} · 依頼 ${b.asks}件 · ${b.attempts}回目`
      + `${b.clears > 1 ? ` · ${b.clears}回クリア` : ''}</span></div>`);
  }

  /* V5 — why the score moved — plugs in HERE, as its own section, once score.js
     exists. It is not stubbed: an empty "点の内訳" heading would be a promise the
     game cannot keep yet. The shape this needs is on BOARD as #S5. */

  elPgBody.innerHTML = html.join('');

  /* one click onward. `もう一度流す` is the other half: a not-cleared pass has to
     be able to leave this page straight into another attempt. */
  const p = progressSummary(scenarioOrder());
  const nx = st.cleared && p.next ? SCENARIOS.find(s => s.id === p.next) : null;
  elPgNext.hidden = !nx;
  if(nx){
    elPgNext.textContent = `次へ — ${nx.title} →`;
    elPgNext.onclick = ()=>{ closePage(); startScenario(nx.id); };
  }
  elPgAgain.hidden = !!nx;
  elPgAgain.onclick = ()=>{ closePage(); runAttack(); };

  elPgNote.innerHTML = st.cleared
    ? `${p.total} 本中 ${p.cleared} 本クリア`
      + (p.complete ? '<br>全シナリオ制覇' : '')
      + (storageOk() ? '' : '<br>この環境では保存されません')
    : 'もう一度流すと試行が1回増えます';
}

function showDebrief(){
  if(!elPage || !goalStatus()) return;
  openPage('debrief');
  renderDebrief();
}

/* the debrief survives being closed: the insight is the thing worth going back
   for, and losing it to one stray click was the old overlay's real cost */
function syncDebriefEntry(){
  if(elToDebrief) elToDebrief.disabled = !goalStatus();
}
if(elToDebrief) elToDebrief.onclick = showDebrief;

if(elPage){
  document.getElementById('pgClose').onclick = closePage;
  addEventListener('keydown', ev => {
    if(ev.key === 'Escape' && pageOpen){
      ev.stopPropagation();
      closePage();
    }
  }, true);
}

/* ---- the change feed ---- */
function renderCampaignAll(){
  renderScenarioPicker();
  renderSides();
  renderRoles();
  renderGoal();
  renderBuildList();
  applyRoleLocks();
  syncLeverWidgets();
  renderResults();
}

/* the situation as the scenario hands it over */
function showScenario(){
  const sc = activeScenario();
  elTitle.textContent = sc ? sc.title
                       : GAME.role ? roleById(GAME.role).mission : DEFAULT_MISSION;
  elScore.textContent = '0';
  /* the denominator belongs to the scenario, not to this file: waves and new
     scenarios change how many steps come, and score() counts detections only —
     containment is a separate component, and stage 08 exists to say so */
  if(elScoreOf) elScoreOf.textContent = `/ ${activeChain().length} 検知`;
  elRun.disabled = false;
  /* who you are, and how far the campaign is, go in the eyebrow, which costs no
     height. The hint is for the setup only — at 720p every line of prose here is
     a line the build list or the results give up. */
  setEyebrow();
  setHint(sc ? sc.blurb : '', false);
  renderCampaignAll();
  fitCampaignPanel();
}

onCampaignChange(ev=>{
  switch(ev.type){
    case 'mode':
      bestNote = null;
      hideDebrief();
      syncDebriefEntry();
      /* the console is evidence about the situation you are in — carrying the
         last one's lines across makes the new premise false on arrival */
      resetLog();
      elCmp.classList.toggle('on', GAME.on);
      [...document.querySelectorAll('#uiModeSeg button[data-ui]')].forEach(b=>
        b.classList.toggle('on', b.dataset.ui === ev.mode));
      document.getElementById('hint').classList.add('gone');
      resetHudBaseline();
      if(GAME.on) showScenario();
      /* leaving campaign gives every lever back — the role only binds in play */
      else { elTitle.textContent = DEFAULT_MISSION;
             renderGoal(); applyRoleLocks(); syncLeverWidgets(); fitCampaignPanel(); }
      closeDrawer();
      goHome();
      break;
    case 'scenario':
      bestNote = null;
      hideDebrief();
      syncDebriefEntry();
      resetLog();
      resetHudBaseline();
      showScenario();
      closeDrawer();
      goHome();
      break;
    case 'role': {
      const r = ev.id ? roleById(ev.id) : null;
      const sc = activeScenario();
      setEyebrow();
      setHint(r ? `<b>${r.jp}</b>として参加する。${r.brief}`
                : (sc ? sc.blurb : ''), false);
      renderSides(); renderRoles(); renderGoal(); renderBuildList(); applyRoleLocks();
      break;
    }
    case 'side':
      setHint(`<b>${SIDES.find(s=>s.id===ev.id).jp}</b>。`+
              SIDES.find(s=>s.id===ev.id).brief, false);
      renderSides();
      break;
    case 'build':
      setHint(ev.unlock, true);
      renderGoal();
      renderBuildList();
      renderResults();
      flyTo(byId(ev.id).cam, districtObjs[ev.id].center);
      break;
    /* every one of these moves the projection, so the goal strip is re-read */
    case 'asks':
      renderRoles();
      renderGoal();
      break;
    case 'requirement':
      renderGoal();
      renderBuildList();
      break;
    case 'run':
      /* a new attempt: last run's verdict on the best is no longer this run's */
      bestNote = null;
      renderResults();
      renderGoal();
      syncDebriefEntry();
      break;
    case 'reveal':
      if(ev.done) captureBest();
      renderResults();
      break;
    case 'waveEnd':
      renderGoal();
      break;
    /* the pass is scored. THIS is where the debrief belongs: goalStatus() is
       non-null only in the `over` phase, and it is the one moment the player has
       earned the answer to the question the scenario asked. */
    case 'over':
      renderGoal();
      syncDebriefEntry();
      showDebrief();
      break;
  }
});

document.querySelectorAll('#uiModeSeg button[data-ui]').forEach(b=>
  b.onclick = ()=> setUiMode(b.dataset.ui));
elRun.onclick = runAttack;


/* ============================================================
   15. minimap
   ============================================================ */
const mm = document.getElementById('mmc');
const mctx = mm.getContext('2d');
const MM_W = mm.width, MM_H = mm.height;
const MM = {x0:CITY_BOX.min.x-8, x1:CITY_BOX.max.x+8, z0:CITY_BOX.min.z-8, z1:CITY_BOX.max.z+8};
function mx(x){ return (x-MM.x0)/(MM.x1-MM.x0)*MM_W; }
function mz(z){ return (z-MM.z0)/(MM.z1-MM.z0)*MM_H; }

/* colours follow each district's own `color` — no second list to maintain */
const MM_FILL = Object.fromEntries(DISTRICTS.map(d => [d.id, hex6(d.color)]));
function drawMinimap(){
  mctx.clearRect(0,0,MM_W,MM_H);
  mctx.fillStyle = '#FAFBFB'; mctx.fillRect(0,0,MM_W,MM_H);

  // flow spine
  mctx.strokeStyle='rgba(43,45,48,.10)'; mctx.lineWidth=7;
  mctx.beginPath(); mctx.moveTo(mx(-80),mz(0)); mctx.lineTo(mx(90),mz(0)); mctx.stroke();

  DISTRICTS.forEach(d=>{
    const x=mx(d.x0), y=mz(d.z0), w=mx(d.x1)-mx(d.x0), h=mz(d.z1)-mz(d.z0);
    /* PLAN is where an empty plot should read best: keep the outline, drop the
       fill. menu.js decides which stage is the one to build next. */
    if(GAME.on && !GAME.built.has(d.id)){
      const up = plotStyle(d.id) !== 'plot';
      mctx.setLineDash([3,2.5]);
      mctx.globalAlpha = up ? 0.95 : 0.5;
      mctx.strokeStyle = up ? '#000' : 'rgba(0,0,0,.34)';
      mctx.lineWidth = up ? 1.3 : 0.8;
      mctx.beginPath(); mctx.roundRect(x,y,w,h,3); mctx.stroke();
      mctx.setLineDash([]);
      mctx.fillStyle = up ? '#000' : 'rgba(0,0,0,.34)';
      mctx.font = '400 7.5px "Share Tech Mono", monospace';
      mctx.fillText(d.n, x+3, y+9.5);
      mctx.globalAlpha = 1;
      return;
    }
    const active = S.selected===d.id || S.hovered===d.id;
    const dim = d.id==='sysdig' && S.mode!=='sysdig';
    mctx.globalAlpha = dim ? 0.2 : (active ? 0.9 : 0.42);
    mctx.fillStyle = MM_FILL[d.id];
    mctx.beginPath(); mctx.roundRect(x,y,w,h,3); mctx.fill();
    mctx.globalAlpha = dim ? 0.3 : 1;
    mctx.strokeStyle = active ? '#000' : 'rgba(0,0,0,.14)';
    mctx.lineWidth = active ? 1.4 : 0.8;
    mctx.beginPath(); mctx.roundRect(x,y,w,h,3); mctx.stroke();
    mctx.globalAlpha = dim ? 0.35 : 0.85;
    mctx.fillStyle = active ? '#000' : '#535557';
    mctx.font = '400 7.5px "Share Tech Mono", monospace';
    mctx.fillText(d.n, x+3, y+9.5);
  });
  mctx.globalAlpha = 1;

  // camera position + look direction
  const cpx = mx(camera.position.x), cpz = mz(camera.position.z);
  const tx = mx(controls.target.x), tz = mz(controls.target.z);
  mctx.strokeStyle='rgba(0,0,0,.28)'; mctx.lineWidth=1;
  mctx.beginPath(); mctx.moveTo(cpx,cpz); mctx.lineTo(tx,tz); mctx.stroke();
  mctx.fillStyle='#000';
  mctx.beginPath(); mctx.arc(cpx,cpz,3.4,0,7); mctx.fill();
  mctx.fillStyle='#BDF78B';
  mctx.beginPath(); mctx.arc(tx,tz,2.4,0,7); mctx.fill();

  mctx.fillStyle='rgba(0,0,0,.32)';
  mctx.font='400 7px "Share Tech Mono", monospace';
  mctx.fillText('N ▲', 5, MM_H-6);
}
if(!CanvasRenderingContext2D.prototype.roundRect){
  CanvasRenderingContext2D.prototype.roundRect = function(x,y,w,h,r){
    this.moveTo(x+r,y); this.arcTo(x+w,y,x+w,y+h,r);
    this.arcTo(x+w,y+h,x,y+h,r); this.arcTo(x,y+h,x,y,r);
    this.arcTo(x,y,x+w,y,r); this.closePath(); return this;
  };
}


/* ============================================================
   16. HUD numbers
   ============================================================ */
const els = {
  sys:document.getElementById('mSys'), ring:document.getElementById('mRing'),
  drop:document.getElementById('mDrop'), rules:document.getElementById('mRules'),
  alert:document.getElementById('mAlert'), buried:document.getElementById('mBuried')
};
const T0 = performance.now();
let hudT = 0, lastC = {...S.counters};

/* Switching mode or scenario zeroes S.counters, and every rate here is a delta
   against the previous sample — so without dropping the baseline the first tick
   after the switch reports a large *negative* syscall rate. That is one of the
   frames a new player sees on the way in, and it reads as a broken instrument. */
function resetHudBaseline(){
  lastC = {...S.counters};
  hudT = 0;
  S.shown = {sys:0, ring:0, drop:0, rules:0, alerts:0};
  S.alertWindow = [];
}
function updateHud(dt){
  hudT += dt;
  if(hudT < 0.42) return;
  const k = 1/hudT;
  // scale the visual sim up to a plausible busy-node range (illustrative)
  const SCALE = 145;
  const sysRate  = (S.counters.sys  - lastC.sys ) * k * SCALE;
  const ringRate = (S.counters.ring - lastC.ring) * k * SCALE;
  const dropRate = (S.counters.drop - lastC.drop) * k * SCALE;
  const ruleRate = (S.counters.rules- lastC.rules)* k * SCALE;
  lastC = {...S.counters}; hudT = 0;

  /* clamped at zero: the smoothing overshoots on the way down, and a rate of
     -0.2 rendered as `0  (-0.00%)` reads as a broken instrument */
  const sm = (a,b)=> Math.max(0, a + (b-a)*0.35);
  S.shown.sys  = sm(S.shown.sys, sysRate);
  S.shown.ring = sm(S.shown.ring, ringRate);
  S.shown.drop = sm(S.shown.drop, dropRate);
  S.shown.rules= sm(S.shown.rules, ruleRate);

  const now = performance.now();
  S.alertWindow = S.alertWindow.filter(t=> now-t < 60000);
  /* alerts/min — extrapolate until a full 60s window has actually elapsed */
  const win = Math.min(60000, Math.max(5000, now - T0));
  const apm = S.alertWindow.length * (60000/win);

  const M = model();
  els.sys.textContent   = fmt(S.shown.sys);
  els.ring.textContent  = fmt(S.shown.ring);
  /* THE RATE COMES FROM THE MODEL, NOT FROM THE PARTICLE COUNTERS (GAP 6.3).
     Two bugs in one line, and both put a number on screen that disagreed with
     the number the same screen was scoring the player against:
       - the denominator was counted twice. sim.js increments `ring` when an
         event passes the kernel gate and THEN increments `drop` for the same
         event, so a dropped event is already inside `ring`; `drop/(ring+drop)`
         divides by the drops a second time.
       - it was a ratio of two EMA-smoothed rates, so the same configuration
         rendered anywhere from 14.00% to 16.30% while the scoring row sat still
         at 16.59%.
     model().dropP is the figure campaign.js scores `goal.maxDropPct` on, so
     taking it here is what makes the instrument and the scoreboard the same
     claim. The absolute events/s keeps coming from the counters — that is a
     volume, and it is honestly a smoothed one. */
  const dropPct = M.dropP * 100;
  els.drop.textContent  = fmt(S.shown.drop) + '  (' + dropPct.toFixed(2) + '%)';
  els.rules.textContent = fmt(S.shown.rules);
  els.alert.textContent = Math.round(apm);
  els.drop.className = dropPct > 0.2 ? 'red' : 'dark';

  /* the second queue. Read straight from noise() rather than smoothed, for the
     same reason the drop rate now is: this is the figure goal.maxBuriedPct is
     scored on, and an instrument that disagrees with the scoreboard is worse
     than no instrument. */
  if(els.buried){
    const Nz = noise();
    const bp = Nz.buriedP * 100;
    els.buried.textContent = bp.toFixed(2) + '%'
      + (Nz.util > 1 ? `  (${Math.round(Nz.inflow)}/${Math.round(Nz.cap)} 件/分)` : '');
    els.buried.className = bp > 0.5 ? 'red' : 'dark';
  }
  updateVerdict(M);
  maybeFitRight();
}

/* The teaching payload: name WHICH failure mode you are looking at,
   because the two have different fixes. */
const elUtil = document.getElementById('mUtil');
const elVerdict = document.getElementById('mVerdict');

/* THE BAND MUST NOT ANSWER THE SCENARIO.
 * -----------------------------------------------------------------------------
 * Two scenarios (`inherited-all-syscalls`, `slow-output`) exist to be
 * MISDIAGNOSED: you see drops, you reach for buf_size_preset, it does nothing,
 * and that is how you learn the difference between a burst and a sustained
 * overload. This band used to print the whole remedy — "バッファを増やしても
 * 直りません — base_syscalls を custom_set に絞る、…" — from the first frame
 * after entry, which denied the misdiagnosis before it could be made and left
 * those two scenarios with nothing left to diagnose.
 *
 * So each row below is split into the two things it was conflating, and they no
 * longer appear at the same time:
 *
 *   sym   the SYMPTOM. Which of the two failure modes this is, and the numbers
 *         it is measured by. Always shown — telling the two modes apart IS the
 *         skill, and a symptom is what an instrument is for.
 *   fix   WHICH LEVER MOVES IT. Explore only. Explore is the explanation of the
 *         model, there is no scenario there to spoil, and this is the one place
 *         the remedy is supposed to be readable straight off the panel.
 *
 * The third statement of the same subject — `insight.wrong` / `insight.truth`,
 * the misdiagnosis this particular situation invites — belongs to the scenario
 * file and is rendered by renderScenarioReport() only once the pass has been
 * scored. One fact, one owner, one moment each: the instrument reports, Explore
 * explains, the scenario debriefs. Before this, the band and the scenario were
 * both making the same claim, and the band was making it first. */
const VERDICT = {
  dead: {
    /* recovery is not a scenario's answer — no scenario's misdiagnosis is "the
       agent exited" — and a player with a dead agent and no way back is stuck,
       so this one sentence stays in both modes */
    sym: () => 'falco が <b>exit</b> しました。検知はゼロです。'
             + '負荷か設定を変えると再起動します。',
    fix: () => '' },
  sustained: {
    sym: M => `持続的な入力超過 — 入力は消費能力の <b>${Math.round(M.util*100)}%</b>。`
            + 'ドロップが続いています。',
    /* The advice itself was wrong twice, and it was on screen every frame:
       `cpus_for_each_syscall_buffer` is not a key that exists (it is
       `engine.<engine>.cpus_for_each_buffer`), and "set it to 1" is the
       direction the Falco docs argue AGAINST — INVARIANTS 1.4. Dropping events
       is fought by making buffers FEWER and LARGER (4–6 CPUs each, with a
       bigger preset), which is also the direction state.js §BUF_CAP now
       models, so the panel and the model finally say the same thing. */
    fix: () => '<b>バッファを細かく割っても直りません</b> — '
             + '<code>base_syscalls</code> を <code>custom_set</code> に絞って入力を減らす、'
             + '<code>engine.&lt;engine&gt;.cpus_for_each_buffer</code> を <b>4</b> に上げて'
             + '（バッファは少なく大きく）<code>buf_size_preset</code> と組ませる、'
             + 'slow output を外す。' },
  burst: {
    sym: M => 'バースト起因のドロップ。平均は消費能力の内側'
            + `（<b>${Math.round(M.util*100)}%</b>）で、山だけが溢れています。`,
    fix: () => '平均は足りているので <code>buf_size_preset</code> を上げれば効きます。' },
  ok: {
    sym: () => 'ドロップなし。消費が入力に追いついています。',
    fix: () => '' }
};

function verdictKind(M){
  if(S.dead) return 'dead';
  if(M.sustained > 0.004) return 'sustained';
  if(M.burst > 0.0015) return 'burst';
  return 'ok';
}

function updateVerdict(M){
  elUtil.textContent = Math.round(M.util*100)+'%';
  elUtil.className = M.util > 1 ? 'red' : 'dark';
  const cls = verdictKind(M);
  const v = VERDICT[cls];
  /* GAME.on is the whole gate: in a scenario the band reports, in Explore it
     also explains. Nothing else about the band changes between the two. */
  const fix = GAME.on ? '' : v.fix(M);
  elVerdict.className = 'verdict ' + cls;
  elVerdict.innerHTML = v.sym(M) + (fix ? ' ' + fix : '');
}
function fmt(n){
  if(n >= 1e6) return (n/1e6).toFixed(2)+'M';
  if(n >= 1e3) return (n/1e3).toFixed(1)+'k';
  return Math.round(n).toString();
}

/* ============================================================
   18. sound switch
   ------------------------------------------------------------
   The whole point of this control is *where the call happens*: an AudioContext
   may only be created inside a real user gesture, so setMuted(false) runs in
   the click handler itself and nowhere else. Default is off, so silence is the
   correct state — what has to work is being able to turn it on.
   ============================================================ */
const elSnd = document.getElementById('soundSeg');
function renderSound(){
  const on = !audioState().muted;
  elSnd.querySelectorAll('button').forEach(b =>
    b.classList.toggle('on', (b.dataset.snd === 'on') === on));
}
if(elSnd){
  elSnd.querySelectorAll('button').forEach(b => b.onclick = ()=>{
    setMuted(b.dataset.snd !== 'on');   /* creates the context, in this gesture */
    initAudio();                        /* and resumes it if it was suspended */
    renderSound();
  });
  renderSound();
  /* The returning visitor whose saved preference is "on" still has no context:
     it cannot exist before they touch something. One gesture, once. */
  addEventListener('pointerdown', function armAudio(){
    removeEventListener('pointerdown', armAudio, true);
    initAudio();
  }, true);
}

/* The entrance goes up last, so the button it adds to #uiModeSeg is wired after
   the handlers above have already claimed that segment. */
initMenu();

export {
  tagEls,
  applyRoleLocks,
  renderCampaignAll,
  updateTags,
  select,
  closeDrawer,
  drawer,
  drawMinimap,
  updateHud,
  updateVerdict,
  pickable
};
